assimp/assimp

include/assimp/metadata.h

INT_MAX is defined in limits.h, not stdint.h

Use correct header for INT_MAX

---

code/FBXParser.cpp

Check the return code of inflateInit() indicates success to avoid
crashing later when zstream contains invalid data.

Check that zlib initialized correctly in FBX parser

---

code/IFCCurve.cpp
code/IFCGeometry.cpp
code/IFCOpenings.cpp

Replace calls to abs with a float to calls to std::abs. Before int abs(int) was being called.

Fix incorrect abs usage

---

include/assimp/quaternion.inl

The function rotates a point to opposite direction.
Conjugate() should be applied to inverse of the quaternion.

Fixed error of aiQuaterniont::Rotate()

---

code/PlyParser.cpp
code/STLLoader.cpp

Fixes some (but nowhere near all) of hanging inputs in #454. No new testsuite regressions on Linux which is not very useful since 81 cases currently fail even without any modifications.
Also you might want to add these testcases to the suite since at least one of them hits an error path that appears to have been completely untested until now.

Fix some infinite loops

---

code/IFCUtil.cpp

There are at least two other places where division by zero happens during processing of test/models/IFC/AC14-FZK-Haus.ifc
In PolyTools.h line 86 function PointInTriangle2D is called from TriangulateProcess.cpp line 392.
It seems that the triangle is almost but not quite degenerate. Dumping the variables I get this:
p0: 0.000000 0.680000
p1: 1.800000 0.679900
p2: 1.800000 0.680000
pp: 0.000000 0.000000
v0: 1.800000 -0.000100
v1: 1.800000 0.000000
v2: 0.000000 -0.680000
dot00: 3.240000
dot01: 3.240000
dot02: 0.000068
dot11: 3.240000
dot12: 0.000000
denom: 0.000000
Is it correct to change PointInTriangle2D to avoid divzero (by always adding FLT_MIN to denominator) or should the conditions in TriangulateProcess be changed?
In vector3.inl line 100 function Normalize() is called from …

Fix division by zero

---

code/3DSExporter.cpp
code/ASEParser.cpp
code/ASEParser.h
code/AssbinExporter.cpp
code/B3DImporter.cpp
code/B3DImporter.h
code/BVHLoader.cpp
code/BVHLoader.h
code/COBLoader.cpp
code/COBLoader.h
code/ColladaExporter.cpp
code/ColladaParser.cpp
code/ColladaParser.h
code/ComputeUVMappingProcess.cpp
code/FBXBinaryTokenizer.cpp
code/FBXConverter.cpp
code/FBXDocument.h
code/FBXParser.cpp
code/FBXTokenizer.cpp
code/MD5Parser.cpp
code/MD5Parser.h
code/OgreXmlSerializer.cpp
code/TextureTransform.cpp
code/XFileParser.cpp
code/XFileParser.h
code/irrXMLWrapper.h
include/assimp/Importer.hpp
include/assimp/ProgressHandler.hpp
include/assimp/defs.h
tools/assimp_cmd/CompareDump.cpp

Cleans up some compiler warnings. No new regression failures on Linux with GCC. Review and run testsuite on a working config before merging. Also the recent changes to the test suite seem to have made mode cases fail (101 currently vs 96 previous).

Clean up some warnings

---

code/Subdivision.cpp

Reduces peak memory use by about 10 MB during load of SuzanneSubdiv_252.blend.
No new regression failures however this file is one of the cases which fails on Linux to begin with so take it with a grain of salt.
Also should I fix the indentation afterwards?

Free edges map before recursive calls to reduce memory consumption

---

code/ParsingUtils.h

This one sets "in" to point to terminating 0 character on EOF. Causes no new regression failures.

Fix read past end of buffer after call to TokenMatch

---

code/IFCUtil.cpp

This doesn't build on clang as-is. I don't speak C++ but the net said adding "const" is the solution, and it now appears to build fine now for iOS and OS X.

Added 'const' to () operator on CompareVector

---

port/jassimp/jassimp-native/src/jassimp.cpp
port/jassimp/jassimp-native/src/jassimp.h
port/jassimp/jassimp/src/jassimp/AiNodeAnim.java
port/jassimp/jassimp/src/jassimp/Jassimp.java

looks like there is no padding on cast a c-struct into jni bytebuffer

Fixes assimp/assimp#509

---

code/FBXParser.cpp
code/fast_atof.h

correctly parses a negative int64 value from text

add strtol10_64 and fix FBX text parsing for int_64 (for animation KTime)

---

code/OpenGEXImporter.cpp

by leaving this uninitialized, the delete in destructor will cause corruptions
(causes .NET applications to crash)

[OpenGEXImporter] Correctly initialize m_textureCoords array

---

.travis.yml

- Currently, the mingw linker crashes linking unit.exe, causing failing assimp CI.
- Significant increase in build time for testing an exotic platform - Mingw crosscompile on linux. Assimp does not have many system dependencies so I feel we can omit this.
- Only compiles because MinGW headers are patched before compiling.
- Confusion since 2 build combinations appear in Travis but are disabled.
- Travis file grows overly complex.
- For multiple months this build did nothing and no one noticed.
As a side note, I'd love to run a significantly larger build matrix, but Travis does not currently seem suited for it.
Also, @arris69, @kimkulling

Remove WINDOWS builds.

---

code/ObjFileParser.cpp
code/Q3BSPZipArchive.cpp

Compilation errors when using libc++:
```
assimp/code/ObjFileParser.cpp:360:30: error: use of
undeclared identifier 'atoi'
const int iVal = atoi( pPtr );
```
```
assimp/code/Q3BSPZipArchive.cpp:143:13: error: use of undeclared identifier 'malloc'
m_Buffer = malloc(m_Size);
^
assimp/code/Q3BSPZipArchive.cpp:147:2: error: use of undeclared identifier 'free'
free(m_Buffer);
```
Steps to reproduce:
* Compile with libc++ library

Fix compilation with libc++

---

CMakeLists.txt
code/BaseImporter.cpp
code/Bitmap.cpp
code/ByteSwapper.h
code/CMakeLists.txt
code/FBXBinaryTokenizer.cpp
code/FBXParser.cpp
code/IFF.h
code/LWOLoader.cpp
code/LWOMaterial.cpp
code/MD2Loader.cpp
code/MD2Loader.h
code/MD3Loader.cpp
code/MD3Loader.h
code/MDCLoader.h
code/MDLFileData.h
code/PlyParser.cpp
code/STLExporter.cpp
code/StreamReader.h
code/StreamWriter.h
code/XFileParser.cpp
doc/dox.h
workspaces/xcode3/assimp.xcodeproj/project.pbxproj

Changing add_definitions() to set(CMAKE_CXX_FLAGS) where I know it is appropiate. Also adding a top-level line so that cygwin cmake stops complaining when trying to build assimp.
Renamed ByteSwap.h -> ByteSwapper.h
** Also changed file in:
workspaces/xcode3/assimp.xcodeproj/project.pbxproj
although I'm not sure how that file works, is it created by xcode?
Just noticed my emacs erased all whitespace on some lines, I apologize, I can correct this if it is a problem.

Modifying files to let assimp build under cygwin.

---

code/CMakeLists.txt

I don't see a reason for forcing the value of LIBRARY_SUFFIX. 
Removing the force attribute would allow experienced users to specify their own suffix format. The default behavior doesn't change with this patch.

Removed FORCE attribute from CMake variable LIBRARY_SUFFIX

---

code/CMakeLists.txt

this allows to disable/enable importers via config setting. when disabled the .cpp isn't compiled at all which will reduce file size and compile time.
(again) a proof of concept:
very likely most combinations will fail atm, but the default shouldn't change anything at all.
thoughts about this?

allow to compile only enabled importers

---

cmake-modules/AddGTest.cmake
code/AssbinLoader.cpp

File reads were used in ai_assert. The function has side effects, so it should not be used in an assert.
Fixed AddGTest.cmake.
There was an issue regarding Xcode project file. The path of libgtest.a was incorrectly set.

Fixed AssBin loader.

---

CMakeLists.txt

Append the necessary flags to CMAKE_CXX_FLAGS, rather than replacing
the previous values. It's critical that that flags are preserved to
ensure proper and consistent compilation.

Fix issue with CMAKE_CXX_FLAGS initialization

---

code/assbin_chunks.h

Documentation of `.assbin` seems to be out of date / incorrect / misinformed
I would like to (politely) submit a patch to correct this
[Pull Request](https://github.com/assimp/assimp/pull/575)
[Issue](https://github.com/assimp/assimp/issues/576)
[Travis](https://travis-ci.org/assimp/assimp/builds/64743988)
* corrected note saying that the header was 500 bytes long (512 bytes are written and the number 512 is given elsewhere)
* altered confusing language about how long the chunks are ("length of chunk" implies the number includes the chunk-header. chunk-data-length less so, and reflects the fact that the number written doesn't include the chunk-header)
* removed mistake about how texture coordinates are encoded (the last release, and the current master, both [write texture coordinates as 3 …

ASSBIN comments seem incorrect

---

code/FBXImporter.cpp

We had an issue when loading fbx files without any debugger attached (or `_NO_DEBUG_HEAP=1` set, so memory is not filled with predefined values), because there was no trailing `\0` set when reading the fbx file.
This fixes it.
Without this fix sometimes more tokens where generated than there are actually in this file (depending on what was in the memory before), causing the parser to fail at the last tokens.

Fixes random crash when loading fbx files

---

code/XFileHelper.h
code/XFileImporter.cpp
code/XFileParser.cpp

assimp doesn't import mesh names from the ascii .X format.
You can verify this by viewing [this model](https://gist.github.com/zippers/c742cff8483e52cc6cc5) in the assimp viewer and observing it contains two meshes named *Mesh 0* and *Mesh 1*.
After applying the patch, you can observe the names *ninja* and *blade* are used instead.

Added mesh name importing to .X ascii format.

---

code/ACLoader.cpp
code/DefaultLogger.cpp
code/MD3Loader.cpp
code/ObjFileImporter.cpp
code/ObjFileParser.cpp
code/XFileImporter.cpp

Fixes most of the remaining crashes from #454. The only one left after this is the one in #488.
No new regression failures. Please review before merge. Especially the assertion to exception and the last (too many vertices) patches. Also the last patch might require a different limit since it's still sometimes too much for Valgrind.

More crash fixes

---

test/unit/utColladaExportLight.cpp

This fixes the only test that fails for me when I run them.

Fixed: Remove absolute path from exported file

---

code/FBXUtil.cpp

cppcheck gives false positives for use of the comma operator, so use << operator.

Prefer Format::operator<< over Format::operator,

---

CMakeLists.txt
samples/SimpleOpenGL/CMakeLists.txt

This lets the code build out of the box on my Windows machine, where it cannot find DirectX.  It also fixes a library issue (libm.a) on Visual Studio, where this library is not needed; this lets it build once I turn on ASSIMP_BUILD_SAMPLES and find GLUT.

Windows build improvements

---

code/FixNormalsStep.cpp

It includes the same part `fDelta1_y * fDelta1_z` (`fDelta1_yz` defined above as `fDelta1_yz = fDelta1_y * fDelta1_z`) on both sides of comparison, that makes no sense. The comment above shows the original intention to compare volumes. No doubt, the copy-paste issue is here.

Fix volume calculation

---

port/AndroidJNI/AndroidJNIIOSystem.cpp

I was integrating Assimp into an android project that uses native-activity, and ran into a few issues with the AndroidJNIIOSystem. These are the changes I had to make to get it working.
- AssimpPCH.h appears to have been removed in #536 
- There was a bug where if your model data had a null terminator, AndroidJNIIOSystem would incorrectly calculate the number of bytes it needed to write to the file (since it reads a compressed file from the Android assets, and then writes it to the internalDataPath directory for later importing)

Include correct headers, fix string length bug

---

code/LWOLoader.cpp

Fixes hangs/14fa1793a3beb6e7db761f7cbfcd3f0c and ef7d28a7282aa3d29fad4fbadba7a29f from #454 . No (new) regression failures on Linux. Please test on windows before merge. @acgessler how's that regression suite fix coming along? Also feel free to change the error message to something more descriptive.

Fix out-of-bounds write on malformed input

---

code/ACLoader.cpp

Without this the code will try to loop through the specified number
of surfaces which could be very large even though none will succeed.
This helps crashes/cb821dbb50a427d2954c6dd12b9132a9 from #454. It was taking excessively long time since it declares 10 million surfaces and then EOFs. The code would loop 10 million times and not do anything useful.
Also someone who can update the test suite might want to turn that one into a real test case.

Abort early when hitting unexpected EOF in AC3D loader

---

code/STLLoader.cpp

Since IsSpaceOrNewLine returns true on '\0' we might try to read past
end of buffer on line 310. Add explicit check to avoid this.
A better fix might be to change IsSpaceOrNewLine to not accept '\0' but that might break other things.
Fixes crashes/9be812f32156c36fc89b4498b5d54ac2 from #454. No new regression failures but STL is one of the tests which always fails on Linux so check on a supported platform before merge.

Avoid reading past EOF when encountering a malformed STL file

---

code/STLLoader.cpp

aiNode was created twice, sorry about that.
This fixes all STL regression errors concerning the node names. There are still some STL regression errors, all of them say something like "Files are different at aiMesh.mFaces. Error is: Expected 4115780318, but actual is 2985128783". Is it possible that the tool is comparing pointers? All models load fine...

Fixed issue in STLLoader that lead to wrong node names.

---

code/IFCOpenings.cpp

This is not legal in any way and should never have worked.
This actually caused GCC to generate bad code when optimization was on. Reduces regression failures on Linux from 54 to 49. You should probably update the regression whitelist too.

IFC: Don't store temporary values by reference

---

include/assimp/types.h

Some embedded (or exotic) systems won't provide this header, and it seems to be unused (since memcpy is in string.h).
Tested on MinGW and VS2015.

remove memory.h dependancy

---

code/PlyParser.cpp

Yes, I just added a 'u'... It was probably due to a miscopypaste.
The point is; I was working with a binary .ply using uint16 for storing colors and I got a problem for loading it. Every value above (UINT16_MAX/2) was misparsed. After investigating I found the problem was from this fixed line.
If you desire, I could make a sample of a .ply using uint16. Actually a simple triangle using uint16 for colors can be used for demonstrating this. It should be encoded in binary. (but this looks so obvious...)

Fixed issue in PlyParser (uint16 values misparsed)

---

code/AssimpCExport.cpp

aiGetExportFormatDescription() now creates an Exporter object at the beginning of the function, so that a call to `GetExportFormatDescription()` doesn't access free'd memory.

aiGetExportFormatDescription() no longer uses free'd memory

---

code/FBXConverter.cpp

I was having problems importing FBX files created with blender after I changed from old blender ASCII FBX exporter to the newer binary exporter. Animation was not being imported correctly by assimp.
The problem is that if an animation only animates some components of a position, scale or rotation (for example only the x-axis is animated) the other axes were always reported to be 0.0 (1.0 for scale).
Here's a patch that fixed the problem for me.
I haven't messed with assimp internals before and I'm not really an expert on FBX so there were a couple of things I'm unsure of:
- Values from different "key lists" were being combined before. Is it really possible to have an animation that defines overlapping key values like that? I had to remove this to make the default values work. …

FBX import: If animation is not defining keys for all vector components (x, y and z), use the node transform as the default value.

---

code/BaseImporter.cpp
code/BaseImporter.h
code/ObjFileParser.cpp

Some programs such as Silo export an empty .MTL file if you export a
.OBJ that doesn't use any materials. This patch allows the loading of
such files without error.

Added support for empty .MTL files.

---

port/jassimp/jassimp-native/src/jassimp.cpp

- Add SmartLocalRef class in jassimp.cpp
- Use it to automatically delete localrefs of Java objects, generated
by FindClass, createInstance, getField, NewStringUTF, etc.
- Tested with models with more than 512 nodes.
Fixes https://github.com/assimp/assimp/issues/712

Use SmartLocalRef to automatically release localrefs in jassimp.cpp

---

code/FBXMeshGeometry.cpp

Fixes an error when an Element has no data.
Example from (Cinema4D export):
LayerElementNormal: 0 {
Version: 101
Name: ""
MappingInformationType: "NoMappingInformation"
ReferenceInformationType: "Direct"
}
What's missing here is the "Normals" data block.
Cinema4D outputs this with NoMappingInformation which does not
export the "Normals" datablock. This can happen for other LayerElement* types.

FBX Import fix

---

code/FBXParser.cpp

Some FBX Exporters (Cinema4D plugin for example) do not write a Comma between
two Numbers when there is a new Line.
Example:
LayerElementColor: 0 {
Version: 101
Name: "colorSet1"
MappingInformationType: "ByPolygonVertex"
ReferenceInformationType: "IndexToDirect"
Colors: *45640 {
a: 0.0,0.0,0.0,1.0
0.0,0.0,0.0,1.0
}
}
A better fix would be that the Tokenizer would create Comma placeholder tokens.
But this fixes it too.

Fix for FBX Files that do not have a Comma on a new line in a data block

---

code/GenVertexNormalsProcess.cpp
include/assimp/vector3.h
include/assimp/vector3.inl

This has been discussed here #485 and as we met the issue again, here is the fix that you were agree to merge in.
Basically, normal generator produces invalid results when it has to normalize a zero vector. Say if you have a look at the test sample `number_formats.obj`:
```
v 0 0 0
v 1 2. 3.0
v +1 +2. +3.0
v -1 -2. -3.0
f 1 2 4
```
So when you ask it to compute normals, it adds 1st, 2nd and 4th vectors and get `(0, 0, 0)` as a result, then it normalizes it by dividing by zero and bad stuff happens.
The proposed fix introduces a "safe" version of the normalization code that takes care about that specific case. Both calls in normalizer have been replaced, it is probably a good idea to review other code and replace some other normalizations, too.

GenVertexNormalsProcess produces invalid results for specific input

---

code/ColladaExporter.cpp

When there are multiple uv channels used by multiple textures, <bind_vertex_input> specifies what channels to use. Without <bind_vertex_input>, at least some importers use wrong uv channels for textures.

Collada exporter: bind uv channel numbers with <bind_vertex_input>.

---

contrib/rapidjson/include/rapidjson/document.h

For a 64-bit architecture, unsigned long and size_t are the same.
This causes a compilation error due to duplicate constructors in document.h.
Fixed issue https://github.com/assimp/assimp/issues/738

Fix compilation error for Mac OS X and 64-bit architecture

---

code/3DSHelper.h
code/Assimp.cpp
code/Importer.cpp
code/ImporterRegistry.cpp
code/MaterialSystem.cpp
code/MemoryIOWrapper.h
code/OpenGEXImporter.cpp
code/RemoveVCProcess.cpp
code/SkeletonMeshBuilder.cpp
code/StepExporter.cpp
test/unit/utColladaExportLight.cpp
test/unit/utNoBoostTest.cpp
test/unit/utRemoveRedundantMaterials.cpp
test/unit/utSharedPPData.cpp
test/unit/utSplitLargeMeshes.cpp

I run the test using valgrind and remove all the memory leaks that it found.
And fix some compile warnings.
Now there is only one problem with the [here](https://github.com/assimp/assimp/blob/master/test/unit/utSharedPPData.cpp#L106) since you will do a delete instead of delete[].
but I don't know how specialize the class Assimp::SharedPostProcessInfo::THeapData for hendle object pointer and array pointer.

Valgrin free

---

code/ColladaExporter.cpp

Old code exported "c:/foo.jpg" path as "c%3a/foo.jpg".
Replacing : with %3a was probably legal, but it made paths unreadable for existing Max importers.

Collada exporter: improve compatibility when exported path contains ':'.

---

code/ObjFileMtlImporter.cpp

We don't handle reflection textures during MTL import. This allowed a NULL
ptr to be used. Simply return in the case of a reflection texture.

ObjFileMtlImporter: Fixed a segfault due to NULL ptr access.

---

code/ObjFileImporter.cpp
code/ObjFileParser.cpp
code/ObjFileParser.h
code/ObjTools.h

Commit "ObjFileParser: Moved the parsing of line continuations (backslashes) … " is the main change, the other is just a minor change that was needed so that I could use ConstDataArrayIt instead of DataArrayIt.
I've tested this as best I can, but the .obj files I have are by no means extensive.

Fix issue: OBJ import takes forever (#759)

---

code/SIBImporter.cpp

C-style cast has a higher precedence than & -operator so this was getting
parsed differently than Kim assumed. Thou shalt not use C-style casts.

SIBImporter: Properly fix C++11 issues for Clang

---

cmake-modules/AddGTest.cmake

Here the problem:
Old url to gtest used https://chromium.googlesource.com/external/googletest not working any more.
Updated gtest to work with google repository on GitHub.
See:
http://stackoverflow.com/questions/35219589/building-assimp-3-2-does-not-work-anymore

updated gtest repository to github

---

code/Q3BSPZipArchive.cpp

This fixes loading of pk3 maps.  The pk3 files contain directory entries with a size of 0, which triggered the following assertion:
Q3BSPZipArchive.cpp:142: Assimp::Q3BSP::ZipFile::ZipFile(size_t): Assertion `m_Size != 0' failed.
The fix ignores "files" with size of 0, which seems to work perfectly for me.

Fix loading of pk3 q3bsp maps

---

code/SmoothingGroups.inl

This started here #485 and was partially fixed here #713, but I've just found one more place that needs attention for the same reason: `SmoothingGroups.inl`, which is used by 3DS loader and maybe by some other code, as well.
The problem is absolutely the same: the code computes some normals, sums them up and then normalizes, but in some cases the sum is zero, so normalization a zero vector gives unpredictable results.
That's why we've added `NormalizeSafe` and the one-line patch switches from the unsafe `Normalize` to a safer `NormalizeSafe()`.

use NormalizeSafe to prevent NaN when normalizing zero vectors

---

CMakeLists.txt

If CMAKE_BUILD_TYPE equal "" as it is in default it will add "d" to library in cmake config.

Resolves #802

---

include/assimp/metadata.h

No changes to functionality, only removing a warning due to unhandled value in a switch statement. The missing value is not of any interest there, so let the default block handle it. Found while building an application with assimp static library + headers on Xcode 7.2.1.

Fix warning when compiling using -Wswitch-enum

---

workspaces/xcode6/Assimp.xcodeproj/project.pbxproj

Seems like the xcode6 project got slightly outdated. Three of the loaders wouldn't compile, but it was just a matter of adding the required files to the project, along with adding a required dependency to the headers search path.
It now builds successfully on Xcode 7.2.1 with a single warning (I'll make another pull request later for that).

Add missing files  so that xcode6 project builds successfully

---

code/ObjFileImporter.cpp

Also got rid of an assertion that would never trigger because the same test was already performed two lines above.
The aiMesh object returned by this function leaked if it had zero faces, because the caller doesn't do anything with the returned value in that case (https://github.com/assimp/assimp/blob/master/code/ObjFileImporter.cpp#L261), which means it never gets deleted.
I don't actually have a file with a mesh that has no faces. The root cause of the issue for me seems to be poor handling of the group (g) keyword, since it triggers creation of a new mesh. Something like this:
```
...
mtllib materials.mtl
g everything
usemtl mat01
...
```
The result for me was a mesh named "g everything" with zero faces and a mesh called mat01 with whatever faces defined right after that. I don't have …

Fix memory leak in OBJ loader when a mesh has no faces.

---

code/PlyParser.cpp

When the "comment" field of a .ply is empty like "comment\n", assimp field skip all the "comment\n" (call of TokenMatch) with the next line too (call of SkipLine).
By Trying to convert the following .ply file, an error is returned
$ assimp export cube.ply a.obj
assimp export: select file format: 'obj' (Wavefront OBJ format)
Launching asset import ...           OK
Validating postprocessing flags ...  OK
ERROR: Failed to load file: Invalid .ply file: No vertices found. Unable to parse the data format of the PLY file.
"""
ply
format ascii 1.0
comment
element vertex 8
property float x
property float y
property float z
element face 12
property list uchar int vertex_indices
end_header
-1 -1 -1 
-1 1 -1 
0.999999 -1 1 
-1 -1 1 
-1 1 1 
1 0.999999 1 
1 1 -1 
1 -1 -1 
3 7 0 1 
3 4 3 2 
3 5 2 7 
3 …

PlyParser: fix invalid loading when comment is empty.

---

code/ObjFileImporter.cpp
code/ObjFileParser.cpp
code/ObjFileParser.h

* this fallback strategy for cases when a .mtl file is not found serves two use cases:
* 1.): workaround for a common user mistake: we occasionally get renamed .obj/.mtl files where the creator didn't know that this breaks the reference in the .obj file to the .mtl file
* 2.): workaround for file name encoding issue: on a debian system that we use, a "Köln.obj" refering to "Köln.mtl" is within assimp processed as "KÃ¶ln.obj" (file open works with this badly encoded file name containing "Ã¶", but not with the correct "ö"). but opening the refered .mtl file also only works when m_pIO->Open() is called with "KÃ¶ln.mtl"

Vcs 1030/obj mtl filename fallback

---

port/PyAssimp/pyassimp/core.py

This is a fix that sets xrange to range in Python 3.0 and above. In Python 3 xrange was renamed range and the original range function was removed.

Python 3 compatibility fix for xrange in PyAssimp

---

CMakeLists.txt
code/BaseImporter.h
code/CMakeLists.txt
code/glTFAsset.h
code/glTFAsset.inl
code/glTFAssetWriter.h
code/glTFAssetWriter.inl
code/glTFExporter.cpp
code/glTFExporter.h
code/glTFImporter.cpp

Should solve  #785, #818, #833, #865, and a pair of other bugs I found.
Also, two small changes to the CMakeList.txt:
- Added a compilation flag "/bigobj" for MSVC to the file "IFCReaderGen.cpp", as when I tried compiling ASSIMP on VS2015 64bit, it failed with:
1>D:\assimp\code\IFCReaderGen.cpp : fatal error C1128: number of sections exceeded object
file format limit: compile with /bigobj
- Added a cmake option to manually disable building `assimp_view` on windows (in my system it was finding only some of the DirectX libs, so it was enabled but failed to compile)

Fixed a few GLTF importer/exporter bugs

---

code/SceneCombiner.cpp

After performing a deep copy of a scene, the mParent fields of the nodes of the new scene were pointing to the nodes of the original scene.

fix SceneCombiner copy of aiNode not setting mParent field

---

code/ColladaExporter.cpp
code/ColladaExporter.h

Allows skeleton information to be exported to Collada by adding the node 'type' field with options 'NODE" and 'JOINT'.

Added 'joint' node type to Collada export

---

code/ObjFileData.h
code/ObjFileImporter.cpp
code/ObjFileParser.cpp
code/ObjFileParser.h

This add the option to parse OBJ files for per-vertex colors, specified in the `v <xx> <yy> <zz> <rr> <gg> <bb>` format.
This format is used by Meshlab and MeshMixer, which are very popular.
Also will then close issue #809

adding support for per-vertex colors in OBJ files.

---

contrib/rapidjson/include/rapidjson/document.h
port/iOS/build.sh

This fixes two different issues when generating iOS static libs.
1. Building for any targets using clang-703.0.31 failed with multiple errors. Using c++11 or c++14 as -std builds successfully for me. Added option to change the -std via command line, even though I still don't understand why c++03 is supposed to work.
2. Building for arm64 failed compilation due to duplicate constructors in rapidjson's document.h.
This is the command I used to build (from ports/iOS): $ ./build.sh --archs="x86_64 arm64"
Compiler version: Apple LLVM version 7.3.0 (clang-703.0.31)

Fix compilation of iOS static libraries

---

CMakeLists.txt

Use CMAKE_CURRENT_LIST_DIR for revision.h: better for in source builds.

CMake: use CMAKE_CURRENT_LIST_DIR instead of CmakeSourceDir.

---

CMakeLists.txt

Currently, `assimp`'s `cmake` automatically tries to find `zlib` and reverts to building an internal version if the library was not found. There is no easy option to force the internal build to go ahead. Preventing the `find_package(zlib)` call can also be useful to use another, externally build zlib version when embedding `assimp` into a larger project.

Allowing to enable building of zlib manually through CMake option.

---

code/ColladaExporter.cpp
code/ObjExporter.cpp
code/PlyExporter.cpp
code/STLExporter.cpp
code/StepExporter.cpp
code/XFileExporter.cpp

It appears like a good idea to increase the export precision to a consistent number (discussed below), so (`stl`, `obj`, `ply`, etc) exporters are not cutting values of the models. Currently, some exporters did define higher precisions, but most did not - this will fix that and ensure you don't loose too much precision upon export. _It may be a good idea to also allow double precision in general (#638)._
_from: http://stackoverflow.com/questions/554063/how-do-i-print-a-double-value-with-full-precision-using-cout_
> The precision needs to be 17 (or std::numeric_limits<double>::digits10 + 2) because 2 extra digits are needed when converting from decimal back to the binary representation to ensure the value is rounded to the same original value. Here is a paper with some details: …

setting default export precision to 17 for all exporters

---

code/ObjFileParser.cpp

Delete reduntal 'g ' from actual name of Group. (we don't have 'usemtl' in material name)
Fixed issue in case 'usemtl' goes straight after 'g'.

Fixes for obj parser

---

code/PlyExporter.cpp
include/assimp/types.h

There are still a whole bunch of `conversion from 'double' to 'ai_real', possible loss of data` warnings on MSVC2015, but the first commit fix already removes many.
The second fix a prevent a collision with the gcc "keyword" `typeof` by renaming it to `type_of`.

Fixes a few build issues with MSVC 2015 and gcc

---

code/BlenderDNA.inl
code/BlenderLoader.cpp
code/BlenderScene.h
contrib/openddlparser/code/OpenDDLExport.cpp

Blender vertex color was importing as negative values. This was because it was being converted to a signed char. Needed to be unsigned.
Also aiColor4 specifies that the color will be 0 to 1, but blender importer was dumping out -128 to +127. Rescaled it so that it is now 0 to 1

Fix blender vertex colors being negative, and fix blender vertex colors scaling to be 0 to 1

---

include/assimp/material.h

Added to the documentation of aiMaterial::GetTexture that the returned path string is a '*' followed by the texture id if the texture is embedded.
I searched quite a while on how to handle embedded textures and could not find anything in the docs. I think such a hint would be quite useful.
Maybe I was just to stupid to find the place this is already documented, then feel free to tell me so and close this request.
I additionally fixed some indentation issues for the documentation of the GetTexture function.

Added documentation for embedded textures

---

code/CMakeLists.txt

When using the internal version of unzip we need to add the unzip folder to the includes.

closes https://github.com/assimp/assimp/issues/967: add unzip include path

---

code/glTFAsset.inl

This package failed to build for big-endian architectures with the following error:
> In file included from /«PKGBUILDDIR»/code/glTFAsset.h:65:0,
from /«PKGBUILDDIR»/code/glTFImporter.cpp:55:
/«PKGBUILDDIR»/code/glTFAsset.inl: In member function 'void glTF::Asset::ReadBinaryHeader(Assimp::IOStream&)':
/«PKGBUILDDIR»/code/ByteSwapper.h:217:24: error: 'ByteSwap' has not been declared
^
/«PKGBUILDDIR»/code/glTFAsset.inl:906:5: note: in expansion of macro 'AI_SWAP4'
AI_SWAP4(header.version);
^~~~~~~~
/«PKGBUILDDIR»/code/ByteSwapper.h:217:24: error: 'ByteSwap' has not been declared
^
/«PKGBUILDDIR»/code/glTFAsset.inl:912:5: note: in expansion of macro 'AI_SWAP4'
AI_SWAP4(header.sceneFormat);
^~~~~~~~
/«PKGBUILDDIR»/code/ByteSwapper.h:217:24: error: 'ByteSwap' has not been declared
^ …

Use Assimp namespace to fix build for big-endian architectures

---

code/glTFAssetWriter.inl

On the Mac, there were ambiguous constructor errors, see: <https://github.com/assimp/assimp/issues/980>

Add typecasts in glTFAssetWriter.inl to fix compile errors

---

CMakeLists.txt
code/glTFAsset.inl

Some of the files from the internally built zlib are too big to be placed in a .so when compiled without -fPIC on 64 bit platform. Tested on up to date Arch Linux, running virtualized on x86_64.
CMake 3.6.1
GNU make 4.2.1
gcc 6.1.1 20160802

Building own zlib on 64bit Linux shared library requires -fPIC for C compiler.

---

code/glTFExporter.cpp

Get around 65k openGL vertex limit by splitting mesh before exporting as glTF.

Split mesh before exporting gltf. Fixes #995

---

code/glTFExporter.cpp

Rather than creating one buffer per mesh, which is unnecessary, add all data to a single buffer.

Add all glTF data to single buffer

---

code/glTFExporter.cpp

Related to #883. Fixes texture flipping problem, but not hierarchy.

Flip UVs in glTFExporter

---

code/Exporter.cpp

Fixes #1002.
However, it doesn't address a similar issue where a single mesh contains both lines and triangles.

Add Triangulate post-processing step to glTF exporters

---

code/glTFAsset.h
code/glTFAssetWriter.h
code/glTFAssetWriter.inl
code/glTFExporter.cpp

Changes:
* Export a `.bin` file containing buffer data, and reference that file in the `.gltf`, rather than embedding a base64 blob
* Factor GLB file logic out of `AssetWriter::WriteFile` into its own function
* Split meshes in constructor to cover GLB files
* use file name as base for buffer IDs (instead of 'buffer')

Export glTF buffer data in a separate .bin file

---

appveyor.yml

I've noticed that the build script used by appveyor was always generating x86 binaries no matter what platform was defined. I fixed this in this PR. 
I made sure the generated DLL was indeed x64 by opening it in Depends then by using it from the Assimp-net wrapper.
You can check the generated binaries here: https://ci.appveyor.com/project/odalet/assimp/build/job/ulygh9s2j99sx9d8/artifacts
Hope this helps!

Fixed Appveyor x64 builds

---

code/glTFAsset.inl
code/glTFAssetWriter.inl
code/glTFExporter.cpp

Currently, `Material.transparency` is ignored by the importer and exporter for glTF.
NOTE: the transparency is only exported if it's different from the default value of `1.0`.

glTF: Read and write transparency values

---

code/Exporter.cpp

Currently the glTF exporter [assumes](https://github.com/assimp/assimp/blob/master/code/glTFExporter.cpp#L382) that every face in a given mesh has the same number of indices. This assumption fails when a mesh contains e.g. both lines and triangles, and causes the exported geometry to be corrupted.
This change fixes that problem by setting `aiProcess_SortByPType` on the glTF exporter.
A potential alternative would be to separate mesh primitives by primitive type in the exporter itself.

Sort by primitive type before exporting as glTF

---

CHANGES
code/glTFAsset.h
code/glTFAsset.inl
code/glTFAssetWriter.inl
code/glTFExporter.cpp
code/glTFExporter.h

This PR attempts to fix the errors when reading an exported glTF file into the glTF validator (Live drag-n-drop tool).
The validator can be found here.
githuh: https://github.com/KhronosGroup/glTF-Validator
Live drag-n-drop tool: http://github.khronos.org/glTF-Validator/
However, this PR is not finished and I am hoping somebody can help me with a few issues:
* In `struct Accessor`,
* `max` and `min` are `std::vector<float>` however they may be another type.
* In `inline Ref<Accessor> ExportData`, 
* the Large value number is hard-coded as `float float_MAX = 10000000000000;` however I assume there is a macro constant somewhere in the code defined for a large value.
* In `struct Sampler`,
* `magFilter` and `minFilter` are hard-coded because I can not find where this information is stored in …

Fix glTF validator errors

---

code/ObjFileParser.cpp
code/ObjFileParser.h

This change allows import of OBJ files that define vertex positions in homogeneous coordinates (as allowed by the [OBJ spec](http://www.martinreddy.net/gfx/3d/OBJ.spec)).

Parse homogeneous vertex coordinates in OBJs

---

code/MD5Parser.cpp

When trying to load md5 models with string that has spaces in bones or shaders assimp can not load this model.
Fix this by read the string with the spaces inside the quote/

fix bug when reading strings in quote in MD5 models

---

include/assimp/cfileio.h

Otherwise building with cfileio.h would result in:
/usr/include/assimp/cfileio.h:61:58: error: unknown type name ‘aiOrigin’
typedef aiReturn (*aiFileSeek)(C_STRUCT aiFile*, size_t, aiOrigin);
^~~~~~~~
/usr/include/assimp/cfileio.h:64:9: error: unknown type name ‘aiFile’
typedef aiFile* (*aiFileOpenProc)  (C_STRUCT aiFileIO*, const char*, const char*);
^~~~~~
/usr/include/assimp/cfileio.h:122:5: error: unknown type name ‘aiFileSeek’
aiFileSeek SeekProc;
^~~~~~~~~~

cfileio: fix function typedefs to have struct/enum

---

code/CInterfaceIOWrapper.cpp
code/CInterfaceIOWrapper.h
code/CMakeLists.txt

Numerous importers rely on the default C++ IOSystem implementation
having the destructor close the file for them.  The C IOSystem wrapper
wasn't and instead assumed that the Close() method was going to be
called.
This brings the C IOSystem wrapper in line with the default C++ IOSystem
by having the destructor close the file.

cfileio: fix leaks by not closing files in the destructor

---

code/glTFAsset.h
code/glTFExporter.cpp
code/glTFExporter.h

This PR is in regard to skins in glTF export.
* Iterating over the aiMeshes, all the bones are collected into one skin.
* `parent` node reference member is added to the glTF asset Node to help when traversing up the node hierarchy.
* A vertex can only have at most four joint weights. After the first four, all extras are ignored.
| Model  | Export Success |
| ------------- | ------------- |
| `gltf/sampleModels/BoxAnimated`  | OK  |
| `gltf/sampleModels/RiggedSimple`  | OK  |
| `gltf/sampleModels/CesiumMilkTruck`  | OK  |
| `gltf/sampleModels/RiggedFigure`  | OK  |
| `gltf/sampleModels/CasiumMan`  | OK  |
| `gltf/sampleModels/Monster`  | OK  |
| `gltf/sampleModels/BrainStem`  | OK  |
| `robot` | OK  |
* `glTFExporter.cpp` needs some code refactoring. Specifically, the `ExportSkins` …

glTF compact skins

---

code/ObjFileParser.cpp

A previous commit used `getName` to parse lines beginning with 'm'. But since `getName` returns the whole line including spaces, the comparisons (e.g. `name == "mtllib"`) always fail, causing the line to be skipped.
In particular, any OBJ imported will be missing its material.
I added some additional parsing to get the correct behaviour back, but it might be best to revert the [commit](https://github.com/assimp/assimp/commit/0359ded94621a4bbba6a021ee5d62314916f6bd2) that introduced the problem.
Fixes #1041

Fix OBJ parser mtllib statement parsing bug.

---

code/FBXBinaryTokenizer.cpp

This add support to read FBX binary file with 64bit header.
Just after the magic word there is a 32 flags mask that was ignored before.
I'm using these flag to check if the file is 32 or 64 bit.
But I'm not 100% sure what these flags do.
Tested on Maya 2017 and 2015, works in both versions.

Added support for 64 bit version header introduced in FbxSdk2016

---

code/AssimpCExport.cpp

The project was built under vs2015. A char array with uninitialized values will cause not null terminated string error when using strncopy. Thus Marshal.PtrToStringAnsi will return garbled text in AssimpNet.

fix strncpy not null terminated string

---

code/ColladaExporter.cpp
code/RemoveRedundantMaterials.cpp

Our workflow requires materials names to stay the same after process/conversion.
RemoveRedundantMaterials generates names "JoinedMaterials_#" and the ColladaExporter renames materials to "m#XXX".
This patch keeps the original materials names when possible.

Keep original materials names in RemoveRedundantMaterials, ColladaExporter

---

contrib/Open3DGC/o3dgcTimer.h

This patch fixes compilation with MSVC 2015.  WIN32 is not a preprocessor symbol that is defined by MSVC, but _WIN32 is.

Fix compile error with MSVC 2015

---

code/FBXConverter.cpp

In line 3073 there was an unproper scope of cast to double.

Keys interpolation fix

---

code/IOStreamBuffer.h
test/unit/utTypes.cpp

Fix obj-performance issue:
- memset will be used to set linebuffer-cache to \n.
- Fix is to set only the last one after end of line was found.

Issue 1059

---

code/ObjFileData.h
code/ObjFileImporter.cpp
code/ObjFileParser.cpp
test/unit/utTriangulate.cpp

The ObjParser uses a special face declarations, where all indices were allocated on the stack for each face. This is fixed now.

ObjImporter: remove unnecessary allocations of std::vector 

---

code/CMakeLists.txt

Fixed a compile error on MSVC14 x64 caused by the /bigobj flag failing to be set
for the 1 and 2-suffixed versions introduced in
commit 0a25b076b8968b7ea2aa96d7d1b4381be2d72ce6.

MSVC14 x64 /bigobj missing causes compile error

---

CMakeLists.txt
code/BaseImporter.cpp
code/BaseImporter.h
code/CMakeLists.txt
code/Importer.h
code/ObjFileParser.cpp
code/ObjTools.h
test/CMakeLists.txt
test/unit/TestIOSystem.h
test/unit/utBatchLoader.cpp
test/unit/utImporter.cpp

Fix the obj file loader by adding a new method which allows
a name to be read considering the space in the middle between two
words and use that for parsing the "mtlib" line in the .obj file
parsing method.
Before, the method used in the obj parsing function would have
returned the string "mtlib NAME_OF_MTL" instead of "mtlib" only,
which resulted in the .mtl file being never parsed.

Fix obj .mtl file loading

---

code/AMFImporter_Postprocess.cpp

Fixed a bug in the AMF Importer Postprocessing where metadata would be incorrectly recorded as having type bool for all entries.
The warning originally surfaced inside of metadata.h, which indicated the original const char* was being interpreted as a bool, rather than an aiString as was obviously intended.

AMF Postprocessed Metadata given type bool regardless of original type

---

code/ObjFileImporter.cpp

Currently the specular exponent in MTL files is being multiplied by 4 on import, causing imported models to be exponentially shinier than specified.
In addition, this scaling isn't matched in the exporter, so, for example, `assimp export my.obj my-new.obj` will yield a model with a much larger specular exponent than the original. Since Assimp isn't the only tool in our pipeline, this is causing us some headaches.
This was previously mentioned in #123, but not implemented. Is there any interest in revisiting this?

Remove scaling of specular exponent in OBJFileImporter.cpp

---

code/ColladaExporter.cpp

This value is handled properly on import, but is inverted in the exporter. Since the default interpretation of this value is such that 0.0 is fully transparent and 1.0 fully opaque, which matches how the importer stores the value, inverting it on export is incorrect.
For example, running `assimp export my.dae my-new.dae` where `my.dae` is in `A_ONE` mode for transparency (the default), will yield a .dae with the transparency inverted from the original. You can also see this happening when converting e.g. OBJs to COLLADA.

Properly export COLLADA <transparency> value

---

code/ObjFileParser.cpp
test/unit/utObjImportExport.cpp

detecting invalid mat definition.

closes https://github.com/assimp/assimp/issues/1111: add warning when

---

include/assimp/metadata.h

Specially for aiString, which does a memcpy.
Found with clazy static analyzer.

Avoid unneeded copy-ctor calls when calling getAiType

---

include/assimp/anim.h
include/assimp/metadata.h

It's fine if assimp uses nullptr internally, but not all projects that use it compile in C++11 mode, so this patch removes the 3 occurrences of nullptr from the public headers.
This allows projects that use assimp to build in C++03 mode.

Replace use of nullptr in headers with NULL

---

code/D3MFImporter.cpp
code/D3MFOpcPackage.cpp

(Pointed out by Antti Määttä in Qt code review.)

{D3MF} Move #ifndefs before #includes

---

Readme.md

this improves the sharpness of the resulting image to match the quality of the other badges.

use SVG in Travis badge

---

port/iOS/build.sh

```
In file included from ~/assimp/code/Importer.cpp:76:
~/assimp/code/Profiler.h:92:83: error: a space is required between consecutive right angle brackets (use '> >')
typedef std::map<std::string,std::chrono::time_point<std::chrono::system_clock>> RegionMap;
^~
> >
~/assimp/code/Profiler.h:86:9: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
auto elapsedSeconds = std::chrono::system_clock::now() - regions[region];
^
[ 16%] Building CXX object code/CMakeFiles/assimp.dir/StandardShapes.cpp.o
1 warning and 1 error generated.
make[3]: *** [code/CMakeFiles/assimp.dir/Importer.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from ~/assimp/code/ImporterRegistry.cpp:150:
~/assimp/code/OpenGEXImporter.h:155:54: warning: deleted function …
```

Fix compiler cpp std version

---

code/ObjTools.h

This patch allows embedded spaces in texture filenames found in MTL files. It only affects the OBJ parser.
Submitted by: Nola Donato nola.donato@samsung.com

OBJParser: Support spaces in texture file names

---

code/ObjFileMtlImporter.cpp

When a new material is parsed from the material library, the name of the current material is set but the old material index remains. This leaves an incorrect material index in the current mesh causing textures to not be associated with the right mesh. This patch updates the material index when changing the material name.
submitted by: Nola Donato nola.donato@samsung.com

OBJParser: set material index when changing current material

---

code/ASEParser.cpp

Stumbled upon this while trying to use vertex colors in ASE files.

Fixed parsing ASE MESH_CFACE

---

port/AndroidJNI/AndroidJNIIOSystem.cpp

We encountered a problem while using assimp on Android Nougat (but it may also happen with older versions, we don't know), so it's tied to the AndroidJNIIOSystem library. On Android, assimp creates a copy of the models on the filesystem (internal storage / data folder of the app), instead of loading them from the Android asset manager each time. 
When we tried to load a model that is located in a folder (or subfolder), assimp was not able to open the output file for extraction from the Android asset manager because the folder (or subfolder) did not exist yet in the app's data folder.
For example, if the model was `models/foo/bar.obj`, assimp will try to create the file `/data/user/0/com.app.sample/files/models/foo/bar.obj` directly without creating the corresponding directory structure. …

Create the directory for the asset's extraction on Android

---

code/CMakeLists.txt
code/ImporterRegistry.cpp

In the case when we want to build assimp with only a few importers (let's say less than 10), it would be shorter to specify the importers in a whitelist manner, instead of disabling every other importer but the 10 we want.
The feature works like that:
```sh
cmake \
-DASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT=OFF \
-DASSIMP_NO_EXPORT=ON \
-DASSIMP_BUILD_3DS_IMPORTER=ON \
-DASSIMP_BUILD_FBX_IMPORTER=ON \
-DASSIMP_BUILD_OBJ_IMPORTER=ON \
-DASSIMP_BUILD_COLLADA_IMPORTER=ON;
```
The new flag here is `ASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT` which is documented in the `CMakeLists.txt` (by default it is TRUE, which mimics the current behavior).
The change in `code/ImporterRegistry.cpp` was because of a fun edge case when no importer was set, which resulted in missing include directives.

Allow to enable importers in a whitelist manner

---

CMakeLists.txt

Commit 125d2ab95581f23908d broke the build process when `-DASSIMP_BUILD_ZLIB=ON`. The main CMake task now uses a macro that is only imported if the FindZlib task is run first. This commit will allow builds with an internally built zlib to progress.

Import FindPkgMacros to main CMake Configuration

---

code/ColladaExporter.cpp

why are you compiling with c++11 but you remove some c++11 things?
by the way the equivalent of unsorted_multimap is multimap not map..
tell me if I can do something to accelerate the merge of this pull request..

use multimap instead of map where an unsorted_multimap was present

---

code/CMakeLists.txt

When installing a RelWithDebInfo build using Visual Studio, the PDB file passed to install() cannot be found because it is missing the library suffix.

Fix PDB file installation in RelWithDebInfo configuration

---

code/glTFExporter.cpp

glTFExporter.cpp:585:35: error: ordered comparison between pointer and zero ('aiVector3D *'
(aka 'aiVector3t<float> *') and 'int')
if(comp_allow && (aim->mNormals > 0)) idx_srcdata_normal = b->byteLength;// Store index of normals array.

Fixed compiler error on clang 4.0 running on OSX

---

CMakeLists.txt
doc/CMakeLists.txt
doc/Doxyfile.in

Current documentation lacks a proper directory handling and switch for
Unix like systems.
The option BUILD_DOCS are added as disable by default, even so the
Doxyfile file is generated for a manual build.
Option HTML_OUTPUT are made cached to be properly replaced, as usually
done by some Linux distributions
Microsoft CHM option is enabled if MSVC is detected.

Enable doxygen been properly used from cmake build and install.

---

code/ObjFileImporter.cpp

After importing an OBJ file, clients cannot not get the UVW index associated with a texture by using `material.Get(AI_MATKEY_UVWSRC(type, i), uvw_index);` because the property is never set by the importer. This change should fix that.

Set UVW index material properties for OBJ files.

---

CMakeLists.txt
doc/CMakeLists.txt

It's nonsense second BUILD_DOCS check on doc/CMakeLists since is already checked on main CMakeLists.
At same time, Doxygen becomes required as no documentation can be built
without it.
Output directory now uses the user defined HTML_OUTPUT instead of
forced dir.
- Added include GNUInstallDirs on same UNIX check, avoiding duplication
of checks

- Fix documentation install process. 

---

CMakeLists.txt
cmake-modules/FindIrrXML.cmake
code/CMakeLists.txt
code/irrXMLWrapper.h
contrib/CMakeLists.txt
contrib/irrXML/CMakeLists.txt

Several distributions usually decide for shared external libraries
instead of an usual embedded, for security reasons, duplicatiion issues.
This change enable the possibility to set SYSTEM_IRRXML=ON for detect
and build against a system installed irrxml.
By default, the internal copy is compiled.
Changes on build:
- Added a FindIrrXML cmake module.
- Moved the source recipe for proper CMakeLists inside contrib directory
- Includes aren't path based anymore, using the provided INCLUDE_DIR
- Compiler options are grouped in a single entry on main CMakeLists
Note: Current internal assimp irrXML is older than upstream irrlicht 1.8.4.
To enable usage of this version, code need to be patched.

- Apply mechanism to decide use for IrrXML external or internal

---

port/PyAssimp/pyassimp/material.py

Keeping the same style of `postprocess.py`, this is a port of the aiTextureType enum in [`material.h`](https://github.com/assimp/assimp/blob/master/include/assimp/material.h).

Adds texture type enum to pyassimp

---

code/OpenGEXImporter.cpp

This fixes a bug that causes a crash when querying the list of supported extensions.
The original code attempts to static-initialise a POD structure using a value obtained from an `std::string`, but C++ guarantees that the dynamic initialisation of `std::string` happens *after* `desc` has been initialised in this case, so it would always initialise in the wrong order.
There is absolutely no purpose in keeping `OpenGexExt` as a statically initialised `std::string` object, so I just took it out, which fixed the crashes we were experiencing on load.

Fix static init ordering bug in OpenGEX importer

---

CMakeLists.txt

This entry was missing due revert of CMAKE_POSITION_INDEPENDENT_CODE
usage. Reported by @Sailsman63

Add missing CFLAGS -fPIC.

---

code/glTFExporter.cpp

Currently the glTF exporter generates a path for the binary file by searching for the first occurrence of `"."` in the glTF's file name, and replacing that and everything following it with a string of the form `"\d+.bin"`. This can fail if, for example, the file name is a path of the form `/path/to/my.dir/example.gltf`. In such cases, the binary's URI will be of the form `/path/to/my.bin`, which is incorrect.
This patch instead looks for the last occurrence of the string ".gltf" in the file name, using that as a base for the binary's URI. It will still fail on an input of the form `/path/to/my.gltf.files/example.xgltf`, again generating a binary URI like `/path/to/my.bin`. This seems like an unlikely case, but it may be worth handling as well.

Fix incorrect truncation of binary URI in glTF exporter

---

code/CMakeLists.txt

Hi everybody!
Thank you for maintaining this amazing project 👍 During compilation I found a tiny little bug, here is my fix. A different way to fix it would be setting a different output of for the configure_file command in the root CMakeLists.txt (I'd say having the generated files separated from the hand-written ones is slightly cleaner, though).
Cheers!
Jonathan.

[One-Line-Change] Fix config.h not being found during cmake --build . --target install

---

code/CMakeLists.txt

This change makes possible to use assimp as subdirectory in another cmake project.

Fix location of config.h

---

code/PlyParser.cpp

Some PLY meshes (such as [JanMichael.zip](https://github.com/assimp/assimp/files/994204/JanMichael.zip) from [trn.io](http://trn.io/b/blEJaQKsLD/)) use `texture_u` and `texture_v` as their UV property names.  But OAI currently only detects properties named `u`/`v`, `s`/`t`, and `tx`/`ty`.  This patch adds `texture_u` and `texture_v`.

Add support for reading texture coordinates from PLY meshes with properties named 'texture_u' and 'texture_v'

---

code/BlenderLoader.cpp

Add TokensForSearch in BlenderLoader to allow CanRead return true for in-memory files.

Add TokensForSearch in BlenderLoader

---

code/ObjExporter.cpp

The previous pull request had an error because the filename string was const and could not be changed. Sorry for that. This one fix that.

Fixed build error in ObjExporter :: GetMaterialLibFileName

---

CMakeLists.txt

This fixes an error introduced by @heliocastro in #1255.  The CMAKE_C_FLAGS string was not quoted, causing CMake to insert a semicolon instead, which would cause a compiler error when additional CMAKE_C_FLAGS are specified.

Fix error when custom CMAKE_C_FLAGS is specified

---

code/Assimp.cpp
code/IOStreamBuffer.h
code/ObjFileParser.cpp
code/ObjFileParser.h
code/ObjTools.h
test/unit/utObjTools.cpp
test/unit/utPMXImporter.cpp

The older linebreak implementation was buggy and really CPU-consuming. In this pull request the continuous lines will be handled directly in the block rad from the file.

Obj with linebreaks

---

port/PyAssimp/pyassimp/helper.py
port/PyAssimp/setup.py

This reverts commit 33bd5cfcfb0f27794a333273b20b60a7a550d184.
Installing the assimp library from setup.py is *not* a good idea as
it will break every packaging effort.
Besides, the original commit relies on an hard-coded path to find the
library that may not exist.

Revert "Installing assimp library as well"

---

code/glTFExporter.cpp

According to the GLTF spec, these buffer view offsets must be a multiple of the accessor's attribute type:
https://github.com/KhronosGroup/glTF/tree/master/specification/1.0#bufferview-and-accessor-byte-alignment
This sprung off of discussion at https://github.com/BabylonJS/Babylon.js/issues/2352.

GLTF exporter: ensure buffer view byte offsets are correctly aligned

---

port/PyAssimp/scripts/3d_viewer.py
port/PyAssimp/scripts/fixed_pipeline_3d_viewer.py
port/PyAssimp/scripts/sample.py

Commit 704e57db4ee640262b8b20f4b687c15231d64354 changed the order of the parameters to `pyassimp.load`.  The new order groups `filename` and `file_type` which is preferable, but the samples and other calls to `load` still point to the old order.  This fixes that with named arguments where necessary.

Fixes parameters to pyassimp.load

---

code/BlenderModifier.cpp
code/FBXDocument.cpp
code/FBXMeshGeometry.cpp
code/LWOAnimation.cpp
code/OgreParsingUtils.h

Fix the compiling problems when using /std:c++latest in VS2017.

Remove std functions deprecated by C++11.

---

code/ColladaLoader.cpp

It looks like unique names are important for correct bone-to-node association:
http://assimp.sourceforge.net/lib_html/data.html#bones

Use unique node names when loading Collada files

---

include/assimp/cimport.h

Linker was throwing unresolved external symbol aiSetImportPropertyFloat

not compiling when using ASSIMP_DOUBLE_PRECISION

---

code/OptimizeMeshes.cpp

Maybe we don't need to shift every mesh 1 position every time we find a match to join meshes. 
I was working with a 3dmodel really huge (>600k meshes), and it took like 2 minutes only with this step , using release flags. Those 2 minutes were like 95% of the whole process.
Here is a grab from the problem:
> 
> Debug, T992: START `postprocess`
> Debug, T992: OptimizeMeshesProcess begin
> Info,  T992: OptimizeMeshesProcess finished. Input meshes: 615321, Output meshes: 10
> Debug, T992: END   `postprocess`, dt= 123.334 s
> 
And the same process after patching this change:
> Debug, T9772: START `postprocess`
> Debug, T9772: OptimizeMeshesProcess begin
> Info,  T9772: OptimizeMeshesProcess finished. Input meshes: 615321, Output meshes: 10
> Debug, T9772: END   `postprocess`, dt= 1.2176 s …

Low performance in OptimizeMeshesProcess with huge number of meshes

---

code/Profiler.h

I was getting this kind of message, instead of seconds when debugging:
Debug, T9224: END postprocess, dt= 11717743 s
Just changed that 'auto' with std::chrono::duration<double>, and it seems to be working:
Debug, T9772: END   `postprocess`, dt= 1.2176 s

Elapsed seconds not shown correctly

---

port/PyAssimp/pyassimp/core.py

When using python3 and running any of the provided scripts I get:
NameError: name 'unicode' is not defined.  Python3 does not have unicode. Using try-except method helps to support python3

Added support for python3

---

code/D3MFOpcPackage.cpp

NDK Compilation failed when using clang (version 5.0.30008):
````
assimp/code/D3MFOpcPackage.cpp:221:16: error: use of undeclared identifier 'malloc'
m_Buffer = malloc(m_Size);
^
````
````
assimp/code/D3MFOpcPackage.cpp:225:5: error: use of undeclared identifier 'free'
free(m_Buffer);
^
````

Fix android build issues

---

code/glTF2Asset.h
code/glTF2Asset.inl
code/glTF2AssetWriter.inl
code/glTF2Exporter.cpp
code/glTFAsset.h
code/glTFAsset.inl
code/glTFAssetWriter.inl
code/glTFExporter.cpp

Outputs the gltf asset field's version string in the pattern `/[0-9]+.[0-9+]/`, instead of an int, per [the GLTF spec](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/asset.schema.json) and [validator](http://github.khronos.org/glTF-Validator)

glTF version

---

CMakeLists.txt
code/X3DImporter.cpp

1. WordIterator's operator== and operator!= must take const WordIterator& as parameter type.
2. OpenMP doesn't work with new two phase lookups. Need to disable twoPhase.

Fix compiling problems under VS2017.3.

---

code/ObjFileParser.cpp

This may be a very specific case, but if the material library file is missing, all material names will also be missing from the final scene, which means that even if materials are stored externally and identified by their names, they will be lost during import. This is a fix to keep material names in such cases.

Fix OBJ discarding all material names if the material library is missing

---

code/MDLFileData.h

When using this compiler:
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
The MDL::Frame is aligned in 8-byte boundaries instead of 4. This generates this error when loading old Quake 1 MDL files:
ERROR: Failed to load file: Invalid MDL file. The file is too small
or contains invalid data (File: MDLLoader.cpp Line: 422)
It seems this error was introduced by commit bd2af6591f20fd8777332d510056a037fbfa0df5 due to compilation warnings.

Re-enabling PACK_STRUCT for MDL files.

---

code/ColladaParser.cpp

Like the summary says: The COLLADA parser could already read line strips but didn't import them. Added the few lines of code necessary to fix that. :)

Collada importer: Add support for line strip primitives

---

code/FBXConverter.cpp

During testing our product I had to find out that some FBX exporters (confirmed with Cinema4D R18) don't fill out the LocalStart/LocalStop properties of an animation, resulting in assimp only importing the key frames at time index zero and discarding all others.
Fix: When LocalStart and LocalStop are both zero, just accept all key frames and calculate offset and duration from the actual min/max time of the imported keys.

FBX importer: Use actual min/max of anim keys when start/stop time is missing

---

code/FBXBinaryTokenizer.cpp

Seems that all FBX 7.5 Binary files uses 64 bits adresses. The code now is taking this in consideration. This commit fixes the #838 issue.

Fixes FBX 7500 binary files loading

---

.gitattributes
code/PlyLoader.cpp
port/PyAssimp/setup.py

these are fixes from the Debian package:
- spelling fix should be self-explanatory
- pyassimp: in Debian we are patching passimp/setup.py to not include any data, as we are including the data by other means, as the setup.py installs them to the "wrong" place (from Debian's POV). this patch makes the Debian specific patch a little easier to handle.

Debian fixes 4.0.1

---

code/PretransformVertices.cpp

copy the name of old meshs and nodes to the new scene.
this PR fix issue #1185

fix name lost when load with PreTransformVertices flag

---

code/AssbinExporter.cpp
code/ColladaExporter.cpp
code/ColladaLoader.cpp
code/IFCProfile.cpp
code/MMDImporter.cpp
code/ObjFileMtlImporter.cpp
code/PlyParser.cpp
code/X3DImporter.cpp
code/glTF2Asset.inl
code/glTF2Exporter.cpp
code/glTFExporter.cpp

This fix addresses all existing warnings under /W3 on MSVC when building for x64.
The only remaining warning identified is under the irrXML project. This warning has not been fixed as it would required changes to the projects preprocessor macros build-wide.

Issue 1065: Fix build warnings under x64 on MSVC

---

.travis.yml

It doesn't actually build anything so it will always pass but the jobs are slow to start and delay the whole thing. Disable it for now. Also you should open an issue in case someone actually knows Travis/OSX and wants to fix it.

Disable Travis OS X build since it doesn't do anything currently

---

code/glTF2Importer.cpp

Previously, only one primitive was supported, in fact memory was corrupted
when more than one primitive was found per glTF mesh.
In this change, each primitive is unrolled as a new Assimp Mesh, resulting
in multiple Assimp meshes per node when multiple primitives exist per
glTF mesh. This is required in the general case, since glTF primitives can
have different material bindings and primitive modes.

Fix glTF 2.0 multi-primitive support

---

code/glTF2Asset.h
code/glTF2Asset.inl
code/glTF2AssetWriter.inl
code/glTF2Exporter.cpp
code/glTF2Exporter.h
code/glTF2Importer.cpp

This PR reverts a commit (a0d9750) where I incorrectly assumed that a glTF2's one mesh per node only ever meant one aiMesh per aiNode (when in reality, assimp data structure stores multiple primitives on a mesh as multiple aiMeshes per aiNode). This PR also adds code that takes multiple meshes on a node and merges their primitives into the first (and only) mesh on a node (as per glTF2 spec).
This fixes exporting models that defined multiple primitives per mesh, such as the Brainstem model (in the glTF2 samples repo), and the [random model of the car](https://github.com/assimp/assimp/issues/1301#issuecomment-330001082) that @jcowles found on Sketchfab. It also fixes missing geometry issues I had with many glTF 1 models being exported to glTF2.
---
With this PR, what happens in a glTF2 -> …

glTF2 primitives fixes

---

code/glTFImporter.cpp

Do not ignore rgba(1,1,1,1) material properties when importing glTF1. While a white diffuse color may be the default value for a default assimp material, `1,1,1,1` is a very explicit color value for ambient/specular/emissive color properties.
Closes #1434

[gltf1] Don’t ignore rgba(1,1,1,1) color properties

---

code/glTF2Exporter.cpp
code/glTF2Importer.cpp

alphaMode is now converted from a std::string to an aiString and back to std::string, since aiString is easier to store and retrieve from aiMaterial properties than std::string
Fixes issues of alphaMode being written out as `\fOPAQUE\0\0\0\0\0\0…`

Fix glTF2 alphaMode storage and reading

---

code/BlenderDNA.h
code/ColladaLoader.cpp
code/FIReader.cpp
code/PlyLoader.cpp
code/glTF2Exporter.cpp
code/glTFExporter.cpp

Mostly simple stuff. The only one which should change behavior is in PLY loader. The previous version could fail on malformed files where the header wasn't complete.

Clean up some more GCC warnings

---

code/glTF2Asset.inl

Some of the postprocessing options generate node names that are crazy long... in the case of one model I was looking at, more than 256 characters. This was causing `glTF2::Asset::FindUniqueID()` to enter an infinite loop.
I can't provide the model unfortunately, but it has a lot of small meshes in it, and the processing flags I used were:
`-cts -jiv -gsn -sbpt -fid -guv -og -om -icl -rrm`

Fix possible infinite loop when exporting to gltf2

---

contrib/unzip/crypt.h
contrib/unzip/unzip.c
test/unit/UnitTestFileGenerator.h
test/unit/utDefaultIOStream.cpp
test/unit/utIOStreamBuffer.cpp

These changes should address build warnings for the project when compiling with gcc. One warning required a change to the interface of some functions in the unzip contribution project. The remainder were internal to the implementation.

Fully addressed identifiable build warnings on gcc

---

CMakeLists.txt
code/MMDPmxParser.cpp
code/glTFAsset.h
contrib/unzip/unzip.c

This is the last remaining thing to be done to address issue #1330 
Only 1 warning remains. This warnings is in the zlib contribution.
`/contrib/zlib/inflate.c:1507:61: warning: 
shifting a negative signed value is undefined [-Wshift-negative-value]
if (strm == Z_NULL || strm->state == Z_NULL) return -1L << 16;`
This is a serious issue. We should consider getting an updated copy of this contribution, if we can't fix it ourselves and it has this issue fixed.

Eliminated warnings when building the project with clang

---

code/BlenderBMesh.cpp
code/BlenderLoader.cpp
code/BlenderTessellator.cpp
code/FBXImporter.cpp
code/IFCLoader.cpp
code/LogAux.h
code/XGLLoader.cpp

Static data members in class templates are a terrible idea. clang 3.9 is the only compiler that managed to identify the obvious issue with this.
This approach is only slightly more code and should also cut down on the number of temporary std::string objects created when logging errors, warnings or general log information.
This ties into the work currently being done to add clang 3.9 to the test matrix.

Fixed warning on clang 3.9 caused by static data member in class template

---

code/FBXDocument.h
code/GenericProperty.h
contrib/Open3DGC/o3dgcAdjacencyInfo.h
contrib/Open3DGC/o3dgcBinaryStream.h
contrib/Open3DGC/o3dgcDynamicVector.h
contrib/Open3DGC/o3dgcFIFO.h
contrib/Open3DGC/o3dgcIndexedFaceSet.h
contrib/Open3DGC/o3dgcTriangleListEncoder.h
contrib/Open3DGC/o3dgcVector.h

Fix some warnings enabled by -Wextra parameter of GCC and Clang. Does not enable -Wextra as part of Travis build since it's not yet clean.

Fix some warnings

---

test/unit/utDefaultIOStream.cpp
test/unit/utIOStreamBuffer.cpp

This issue only appears on MSVC 2013. This is caused by a temporary file being created and written to, but is slow to be flushed to until it is reopened for reading. This is a blocker for #1479. Once this is merged, that work should be ready to merge.

Fixed File Size reported as 0 in tests that use temporary files

---

code/ObjFileMtlImporter.cpp

"map_disp" token added alongside "disp" to identify displacement textures in OBJ MTL file parsing.
Minor indentation and cleaning.

Added alternative displacement texture token in OBJ MTL material.

---

port/jassimp/jassimp-native/src/jassimp.cpp
port/jassimp/jassimp-native/src/jassimp.h
port/jassimp/jassimp/src/jassimp/AiClassLoaderIOSystem.java
port/jassimp/jassimp/src/jassimp/AiIOStream.java
port/jassimp/jassimp/src/jassimp/AiIOSystem.java
port/jassimp/jassimp/src/jassimp/AiInputStreamIOStream.java
port/jassimp/jassimp/src/jassimp/Jassimp.java

To distribute our software easily, we load Java resources from the class loader. This pull request adds the ability to define a custom IOSystem in jassimp.
When importing a model, the C++ IOSystem.open() function will call to the Java code and return a java native ByteBuffer (a continuous memory block accessible from the C++ code). The IOStream acts directly on this memory block. 
Using a memory buffer instead of calling back to the Java code for seeking in the file seems the most straightforward solution, especially considering that no seeking is supported in resources loaded from the class loader. 
A implementation of the Java IO system for loading files from the class loader (classpath) is provided.(AiClassLoaderIOSystem)
To provide support for getting the system path separator and …

Feature/jassimp IO system

---

test/unit/utObjImportExport.cpp

According to OBJ fileformat (http://www.fileformat.info/format/wavefrontobj/egff.htm)
negative indices can be used
> v -0.500000 0.000000 0.400000
> v -0.500000 0.000000 -0.800000
> v -0.500000 1.000000 -0.800000
> v -0.500000 1.000000 0.400000
> f -4 -3 -2 -1
This is already handled in assimp, this PR just add a test to check this and improve coverage.

OBJ : add unit test to validate relative indices

---

port/jassimp/README
port/jassimp/jassimp/src/jassimp/AiClassLoaderIOSystem.java
port/jassimp/jassimp/src/jassimp/AiIOStream.java
port/jassimp/jassimp/src/jassimp/AiIOSystem.java
port/jassimp/jassimp/src/jassimp/AiInputStreamIOStream.java

In my last pull request (feature/ihmc-classloader) I accidentally included our standard Apache 2.0 license template. This pull request removes that template and replaces it with the assimp BSD template.
Also I removed the "* no support for the custom I/O API of assimp" line from the README.
My apologizes for not catching this before making my original PR.

Changed license header for IHMC contributions from Apache 2.0 to BSD

---

code/glTFExporter.cpp

Was writing out “\u0001” instead of “1.0” as the data types were incorrect

Fix output of glTF 1 version string

---

code/ObjFileParser.cpp

On OBJ importer, face indices are parsed with std::atoi function.
This function could return 0 on ill-formed input. Since 0 is not a valid value, I think we should raise an exception if this happen.
This should prevent some crashes happening when fuzzing OBJ importer.

Raise exception when obj file contains invalid face indice

---

code/glTF2Asset.h
code/glTF2Exporter.cpp
code/glTF2Exporter.h
code/glTF2Importer.cpp

TL;DR:
- Diffuse and specular colours and textures are persisted better; and
- glossiness/roughness can be derived from shininess and specularity and vice-versa. 
All of this allows better interoperability between traditional lighting material models and PBR material models.
---
This PR improves importing and exporting some material properties in glTF2. Changes:
- Diffuse Color:
- Importing:
- pbrMetallicRoughness' (pbrMR) baseColorFactor is stored as `$clr.diffuse`, as well as a `$mat.gltf.pbrMetallicRoughness.baseColorFactor`.
- If pbrSpecularGlossiness (pbrSG) is present with a diffuseFactor, it will store and overwrite `$clr.diffuse`
- Exporting:
- pbrMR will read from `$mat.gltf.pbrMetallicRoughness.baseColorFactor` first, then fallback to `$clr.diffuse`
- pbrSG (if present) will …

glTF2 Material Improvements

---

code/glTF2Exporter.cpp

Was accidentally flipping to value (1 - x) twice, thus negating the effect. This reverses that, and makes the code more readable via comments.

[gltf2 export] Fix shininess to roughness conversion

---

code/FindInvalidDataProcess.cpp

When the `aiProcess_FindInvalidData` post processing step is enabled, line 703 in glTF2 exporter crashes:
https://github.com/assimp/assimp/blob/938c02a3587766d0ebbedebba4cb162445cb397c/code/glTF2Exporter.cpp#L701-L705
I tracked it down to texture coordinates being removed in post processing, but `mNumUVComponents` for the corresponding sets not being set to `0`, causing an access error when flipping texture coordinates.
Is this fix correct?

Invalid texture coordinates cleaning fix

---

code/PlyParser.cpp

In cases where the TextureFile name would start with an integer, `strtoul10` would parse that number and incorrectly set `numOccur` to that number. This caused PLY parsing to fail for vertex positions.
For example, a file name like `512.png` would set `numOccur` to `512`, causing issues when continuing to parse. `foo.png` would  keep `numOccur` at `0`. This PR fixes the issues by always keeping `numOccur` at `0` for TextureFile, by returning early.
Since TextureFile is a single line, and does not have any follow-up lines, it’s okay to return early.
Fixes #1324

[PLY] fix for TextureFile with number in file name

---

code/OpenGEXImporter.cpp
contrib/openddlparser/include/openddlparser/OpenDDLParser.h
test/CMakeLists.txt
test/unit/utX3DImportExport.cpp

Add X3D-unittest to check importer for mem leaks or memory access violations.

add unittest for x3d-importer.

---

doc/Doxyfile.in

Put irrXML onto exclucde list for doxygen run.  The second image. will is referenced by the docu generated by doxygen comes from irrXML and we don't want to include this into our own doc.

closes https://github.com/assimp/assimp/issues/1533:

---

code/FIReader.hpp
test/CMakeLists.txt

So it will much easier to see where which kind of tests are located.

unittests: add VS-based source groups for the unittests.

---

code/glTF2Asset.h
code/glTF2Asset.inl
code/glTF2Importer.cpp

This is more or less a copy of the glb code in the glTF1 reader adjusted to the new glTF2 binary format.

[glTF2] Implemented reading binary glTF2 (glb) files

---

code/glTF2Asset.h
code/glTF2Asset.inl
code/glTF2AssetWriter.inl
code/glTF2Exporter.cpp

Bugfix: Moved byteStride member from accessor object to bufferView object. In glTF1, byteStride was part of accessor, but in glTF2, it is part of bufferView. When creating the glTF2 loader/writer by copying the glTF1 loader/writer, someone forgot to move byteStride to the right place.

[glTF2] Moved byteStride from accessor to bufferView

---

test/CMakeLists.txt

This commit adds the assimp dll in the unit test folder when building on windows, like for assimp_cmd tool.

Copy assimp dll to unit folder on windows

---

code/glTF2Asset.inl

Orthographic cameras are not yet supported by assimp, but this fixes the parsing in case we support them in the future.

Fix typo on gltf2 camera parameters

---

code/glTF2Importer.cpp

Per spec. This fixes the output of the [Polly model](https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/polly)
Closes #1568
This work is @awefers' (via a .patch) and I have attributed it to them as such.

[glTF2] Fix transform matrices multiplication order

---

code/D3MFExporter.cpp
code/D3MFExporter.h
code/D3MFImporter.cpp
code/D3MFOpcPackage.cpp
include/assimp/IOSystem.hpp
test/unit/utIOSystem.cpp

- fixed export of relations
- add missing content file
- correct handling with already existent files.
- avoid crashed when expected attribute of relation is not there.
- fix folder naming for subfolders in zip-lib

3MF: fix working test for 3MF-export.

---

contrib/unzip/unzip.c

Fixes "unzip.c:150:11: error: unknown type name 'z_crc_t'"

unzip: fix build with older zlib

---

.travis.yml
code/MDLLoader.cpp
code/StreamReader.h
include/assimp/material.h
include/assimp/vector2.h
include/assimp/vector2.inl

Travis updated clang to 5.0 which broke the build. This fixes some warnings and disables static analysis for now to get the builds back on track.
@kimkulling The changes to aiUVTransform and aiVector2 change the ABI so the next release must be 5.0. There's still a problem in [`MDLLoader.cpp`](https://github.com/assimp/assimp/blob/master/code/MDLLoader.cpp#L419), it does really bad things with pointer casting. Any ideas how to fix it?

Clang 5.0 fixes

---

code/glTFExporter.h

Pretty sure this should be ASSIMP_BUILD_NO_GLTF_EXPORTER

Fix incorrect NO_GLTF_IMPORTER define name in glTFExporter.h

---

code/B3DImporter.cpp
code/B3DImporter.h

Before it crashed if reusing one instance of Importer.
aiNodes should also be stored with unique_ptr but their ownership is complicated. It probably needs a more significant refactor.

Use unique_ptr in B3DImporter

---

code/PlyLoader.cpp
test/unit/utPLYImportExport.cpp

Pointer mGeneratedMesh was not reset to nullptr when transfering ownership
to pScene->mMeshes.

Fix #1623 : crash when loading multiple PLY files

---

code/Exporter.cpp
code/glTF2AssetWriter.h
code/glTF2AssetWriter.inl
code/glTF2Exporter.cpp

- Following [specifications](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#glb-file-format-specification) for the binary format ;
- Verified using Khronos Group's glTF validator : http://github.khronos.org/glTF-Validator/

Added support for generating glb2 (binary glTF 2)

---

code/FBXMaterial.cpp

It looks like it was just saved with a wrong encoding,
as these 0xB4 characters were in place of "'".
Also converted tabs to spaces to match indent in the rest of the file.

Fix non-ascii encoding in comments in FBXMaterial.cpp.

---

code/ColladaLoader.cpp
code/FBXConverter.cpp
code/FBXImportSettings.h
code/FBXImporter.cpp
include/assimp/config.h.in
include/assimp/scene.h
include/assimp/texture.h

FBX files may use a texture reference from an embedded texture that hasn't been loaded yet. This patch fixes this issue, storing all texture filenames, that can be acessed later via "scene::GetEmbeddedTexture", when all textures are already loaded.
Some warnings have been added to other file formats that uses embedded data.

FBX Embedding Fix

---

code/FIReader.hpp
code/MDCLoader.cpp
code/MMDPmxParser.h
code/ObjFileImporter.cpp
code/Q3BSPFileImporter.cpp

Fix some of the new clang 5.0 analyzer warnings and a few virtual destructor issues which will cause a warning on clang 6.0 (still in development).
Doesn't re-enable the analyzer on Travis because it looks like there are some false positives which can't be silenced.

Fix some static analyser warnings

---

code/ObjFileImporter.cpp

The overflow-checking code in ObjFileImporter::createVertexArray is at
the wrong position, allowing buffer overflows in preceding code.
This fix moves the code to the right spot.
An actual overflow can be caused by usign some more bugs and weird
behaviours and injecting a malformed line statement into the object
file, containing only one index. Such a malformed file could for
example look like:
o 1
v 0 0 0
v 1 1 1
v 2 2 2
l 1
f 1 2 3
Because the code in ObjFileImporter::createTopology incorrectly handles
line-type faces containing only one index (in line 364), it
underestimates the number of required indices and therefore causes the
buffer allocated in line 421 to be too small.
I believe, the correct fix for this would be in the parser and
rejecting such faces early. However the overflow …

Fix buffer overflow in obj loader

---

code/MMDImporter.cpp
code/glTFAsset.h
code/glTFAsset.inl
code/glTFImporter.cpp

All the shipped models except irrXML models can now be loaded without memory issues (except leaks).
Testing has been minimal, @dhritzkiv do you want to test this before merge?

Memory management fixes

---

code/glTF2AssetWriter.inl
code/glTF2Exporter.cpp

When exporting, we now export embedded images correctly.

[glTF2] Correctly export images with bufferView

---

.gitignore
port/PyAssimp/pyassimp/helper.py

Also ignore compiled python files that may be generated.
Reference #1667

Remove check for 'assimp' in pyassimp search path

---

code/glTF2Importer.cpp

fixes  #1691 
Creates the default material as last material in the material index and assigns it to nodes without material reference. I decided to use the last index for the default material (the other option would be to use index 0 and shift all material indices by 1), so that the material index from the glTF file is preserved.

glTF 2.0: Assign default material to meshes with no material reference.

---

code/glTF2Importer.cpp
code/glTFImporter.cpp

Always check the signature for glTF 1.0 and glTF 2.0 files to select the correct importer. Fixes #1605

glTF: Always check signature

---

code/glTF2AssetWriter.inl

Requires cast from size_t to uint64_t like in other places, otherwise the implicit call to the GenericValue constructor is ambiguous.
Fixes #1684

macOS build fix

---

doc/dox.h

The statement in the documentation that Assimp uses the same memory layout for matrices
as OpenGL does is wrong. Actually, both OpenGL and DirectX specify a matrix layout where
the base vectors and the translational part is consecutive in memory.
OpenGL uses post-multiplication of column-vectors and stores the matrix in column-major storage format:
| X1  Y1  Z1  T1 |  | a |
| X2  Y2  Z2  T2 |  | b |
| X3  Y3  Z3  T3 |  | c |
|  0   0   0   1 |  | 1 |
DirectX on the other hand uses row-major storage format but also pre-multiplication of
row-vectors
| a b c 1 | | X1  X2  X3  0 |
| Y1  Y2  Y3  0 |
| Z1  Z2  Z3  0 |
| T1  T2  T3  1 |
So a matrix is stored the same way in both frameworks and both times the translational part is consecutive at offsets 12, 13 and 14, which is not the format that …

Clarify the matrix layout in the documentation

---

port/PyAssimp/gen/materialgen.py
port/PyAssimp/pyassimp/material.py

In the style of gen/structsgen.py, we construct a similar method for
keeping the constants in materials.py up to date.

Add pyassimp code generation script for materials

---

code/3DSConverter.cpp
code/3DSHelper.h
code/3DSLoader.cpp
code/ASELoader.cpp
code/ASEParser.cpp
code/ASEParser.h

3DS::Material creates a default name by incrementing a static non-atomic counter. This is neither thread-safe (even with separate Importer instances) nor reproducible in one thread. Refactor it by always passing in a name.

Fix thread-safety issue in 3DS and ASE loaders

---

include/assimp/scene.h

As it stands, an assimp scene created from reading a file (returned as a const aiscene*) cannot call GetEmbeddedTexture() as it is not a const member of the object.

GetEmbeddedTexture should be a const function

---

code/OgreXmlSerializer.cpp
code/OgreXmlSerializer.h

Replace `std::string` with `const char *`. This fixes some race condition false positives from Helgrind. It was also kind of silly to create a `std::string` and immediately pass it as `const char *` to another function.

Fix thread-safety false positives in Ogre importer

---

include/assimp/matrix4x4.inl

The calculation of the rotation matrix was assuming left-handed coordinates with row-vectors, but assimp uses right-handed coordinates and column-vectors.
Previously this was sometimes giving me incorrect rotations when importing and directly exporting an FBX, but with this new code rotations seem to be correctly decomposed.

Fix Matrix4x4t Decompose to rotation vector.

---

code/BlenderIntermediate.h
test/unit/utBlenderIntermediate.cpp

Issue #1776 Fixed potential crash bug in ObjectCompare, because it didn't follow strict weak ordering. As counter-intuitive as it seems, a comparator must return false for equal values. The C++ standard defines and expects this behavior: true if lhs < rhs, false otherwise.

Issue #1776 Fixed potential crash bug in ObjectCompare

---

code/OgreXmlSerializer.cpp

@kimkulling Please don't create static variables (even if const) in function scope. This forces the compiler to allocate memory for them and insert code which will check and initialize if necessary. This will cause issues for anyone trying to debug with Helgrind or DRD. Also in case of a small type like `aiVector3D` it will actually hinder optimization since it now has to do memory fetches instead of just loading a constant `0.0f`.

Fix another thread-safety issue

---

code/FBXConverter.cpp
code/FBXConverter.h
tools/assimp_cmd/Info.cpp

This applies the inverse of FBX "geometric" transforms to child nodes. The transforms are thus applied to any attached meshes, but correctly not applied to child nodes, as FBX intends.
This should fix #1127, and thus also perhaps #1112, #1297, and #1306 (for FBX).
I tested that the example in #1127 behaves correctly - OBJ export looks identical to the FBX loaded in Maya. But i haven't tested any of the example files in the other issues.
There will be a problem if anybody applies a geometric transform with a scale component of zero (i don't know why anone would do that, but i can't say they won't). In this case children will inherit this zero scale transform and results will be wrong, it won't even try to invert it.
There will also be a problem if the geometric transform is animated. …

FBX geometric transforms fix

---

include/assimp/mesh.h

Also elaborated a bit on mOffsetMatrix, and slightly clarified the description of mWeights.
The mOffsetMatrix description was saying that it is a matrix transforming from mesh space to bone space, which was in fact the exact opposite of what it is.
I verified that both FBX import and GLTF export treat it as a transform from *bone* space to *mesh* space.
The extra info i added should make it even more clear.

Fix aiBone->mOffsetMatrix documentation, which was incorrect.

---

CREDITS
code/CMakeLists.txt
code/Exporter.cpp
code/FBXCommon.h
code/FBXConverter.cpp
code/FBXExportNode.cpp
code/FBXExportNode.h
code/FBXExportProperty.cpp
code/FBXExportProperty.h
code/FBXExporter.cpp
code/FBXExporter.h

Supports:
* mesh data with normals and uvs
* lambert and phong materials
* file textures
* bones / skeletons
* skinning
Does not yet support:
* animations
* cameras
* lights
* embedded textures
Most of the work for this was sponsored by my company MyDidimo, whom i have added to the CREDITS file. (I also made the patreon section stand out a little more while i was there...)
I left a (commented out) stub for ascii-fbx export with the "fbxa" tag, but for now only binary fbx is supported, as the new "fbx" export format.
The main section of code in `FBXExporter.cpp` is not the most readable, but it could be worse. The FBX file format itself makes tidy code pretty much impossible.
The two helper classes, `FBX::Node` and `FBX::Property`, do most of the work writing data to the output fbx file. …

Initial FBX Export Support, sponsored by MyDidimo.

---

code/FBXExporter.cpp
code/FBXExporter.h
tools/assimp_cmd/Main.cpp

Previously the export wasn't correctly exporting an entire skeleton, in the case that the mOffsetMatrix wasn't defined for every node in the skeleton.
This happened quite a lot, because the aiBone only exists if it has skinweights on something.
This PR reconstructs the skeleton, if it can, by using bone node transforms to calculate the missing offset matrices.
If the skeleton is not in the bind pose (i.e. this calculated matrix doesn't match the mOffsetMatrix for some bone) then it will still export so long as *all* bones have an mOffsetMatrix defined.
If it can't export, it will throw a DeadlyExportError with an informative error message. This is preferable to exporting something incorrect, as the user can theoretically fix this by ensuring that the skeleton is in the bind pose.

Fbx export skeleton improvements

---

code/BaseImporter.cpp
code/Importer/IFC/IFCLoader.cpp
test/unit/utIFCImportExport.cpp

When looking for tokens to validate, which importer shall be used the tokens of the file will be converted to lower case. The same must be done for the tokens to look for. This pull request will fix this.

BaseImporter: fix lookup for tokens during inmemory imports.

---

code/FBXExporter.cpp

This correctly aligns the footer. The FBX SDK doesn't seem to care when importing (neither does Blender, or probably anything else), but this better matches the footer of officially-exported FBX files.

FBX Export: add missing 0 value to file footer.

---

code/ColladaParser.cpp
code/ColladaParser.h

When blendshapes and bones are applied to a mesh Maya 2018 exports Collada with nested controllers which are not supported in Assimp. I've placed postprocessor which breaks the controllers hierarchy
[torus.zip](https://github.com/assimp/assimp/files/1817949/torus.zip)

Support Maya 2018 Collada Export

---

doc/dox.h

This updates the docs regarding the latest updates (GetEmbeddedTextures). It is based on my experience working with it, so it's not necessarily correct/complete, and might need updates in the future.
I also took the liberty to format the text paragraphs I edited.

Expand the current documentation about loading of embedded textures

---

code/CMakeLists.txt

IFCReaderGen1.cpp has renamed to Importer/IFC/IFCReaderGen1_2x3.cpp . 
Fix #177

Fix mingw compilation

---

test/unit/utMetadata.cpp
test/unit/utPLYImportExport.cpp

pretty minor warnings, but nonetheless

Address some gcc warnings about signed / unsigned comparison.

---

code/Exporter.cpp
code/FBXExportNode.cpp
code/FBXExportNode.h
code/FBXExportProperty.cpp
code/FBXExportProperty.h
code/FBXExporter.cpp
code/FBXExporter.h
include/assimp/StreamWriter.h

Seems to work for my test models. Should make it easier to debug FBX export in general.
It mostly shares the same code with the binary exporter, just with some small divergences as the file structures differ slightly.
Based off the branch with animation support.

Ascii FBX Export

---

code/glTF2Exporter.cpp

Before the PR, when generating a glb2, the embedded textures were duplicated. Thus, it's making a huge output file for no reason when textures are shared between materials.

[glTF2] Not duplicating embedded textures

---

code/COBLoader.cpp

When loading Truespace .cob models into the assimp_QT_viewer the normals are flipped incorrectly. Added a normal flipping call on import to ensure correct orientation of normals.

Updated COB importer plugin to flip normals.

---

code/CalcTangentsProcess.cpp

From #1219.
> In the file CalcTangentsProcess.cpp (line 191), in the function CalcTangentsProcess::ProcessMesh, we test if the 3 points are aligned instead of being at the same place. Because if they are aligned, the tangent and bitangent can't be computed.
Code:
if ( 0 == sx && 0 ==sy && 0 == tx && 0 == ty )
should be replaced with:
if ( sx * ty == sy * tx 
> )
Implemented suggested solution.

Fixed issue#1219. CalcTangentsProcess::ProcessMesh.

---

code/ColladaParser.cpp

DAE file image exemple:
```
<image id="image-1404706686">
<init_from><![CDATA[textures\burgundy.png]]></init_from>
</image>
```

Correction on Collada parser missing textures when the image is in CDATA

---

CMakeLists.txt

There was a typo in the `CMakeLists.txt` where if zlib was not found, it would say "Compiling from souces" instead of "Compiling from sources". Added a 'r' to fix the typo.

Changed 'souces' to 'sources'.

---

assimp-config.cmake.in

Since the ASSIMP_LIB_INSTALL_DIR where this CMake config file is  installed to may contain multiple nested directories, we should not use it to back-calculate the location of the ASSIMP_ROOT_DIR unless we can take the directory depth into account. Instead use the
CMAKE_INSTALL_PREFIX as the ASSIMP_ROOT_DIR at configure-time.
This approach is more flexible with respect to install directories but it means that assimp files are not relocatable after installation and I don't think it works if a DESTDIR option is provided when running `make install` after cmake configuration.
Proposed to resolve #1914.

Use CMAKE_INSTALL_PREFIX as ASSIMP_ROOT_DIR.

---

code/glTF2Exporter.cpp

The vertex colors were not exported when choosing the glTF2 format, so I simply add it to the glTF2Exporter.

Add vertex color support to glTF2 export

---

code/DXFLoader.cpp

A binary FBX file can have an header section `FBXHeaderVersion` which starts around the 70th byte.
Therefore, the token check for DXF file was hitting true because the `SearchFileHeaderForToken` is case insensitive.
We limit the scope of the token search to the first 32 bytes.

Fixes DXF loader false positive on FBX file

---

tools/assimp_view/Display.cpp
tools/assimp_view/Material.cpp
tools/assimp_view/MessageProc.cpp
tools/assimp_view/assimp_view.cpp
tools/assimp_view/assimp_view.h

- Use std::min/max instead of min/max macro in windef.h ( https://github.com/assimp/assimp/issues/952 )
- Use mmsytem.h instead of timeapi.h with MinGW
The changes have been tested with MinGW 5.3 and Visual Studio 2017.

Fix Assimp viewer build with MinGW

---

code/DefaultIOSystem.cpp

I was trying to build Assimp from sources, by adding it as a submodule of my project. Then for some reason it wasn't compiling.
Then I found out that apparently `_stat64` is wrong, and it should be `__stat64`.
It compiled just fine after that.
🤷‍♂️

_stat64 doesn't seem to exist. use __stat64!

---

port/PyAssimp/pyassimp/core.py

As of now, `load`ing and `export`ing a file causes a `UnicodeDecodeError` if the filename is not in ASCII format. 
I'm not sure if we really need this restriction here. One possible solution would be to expect a string here, but this would not be intuitive while using python 3. The other solution, proposed here, is to use the encoding `sys.getfilesystemencoding()` returns.

PyAssimp: Encode filename using file system encoding instead of ASCII

---

port/iOS/build.sh

Building libassimp using the port/iOS/build.sh builds dependencies for different architectures, but they were overwritten for each architecture instead of being merged together using lipo.

Create fat binaries for libIrrXML and libzlibstatic too

---

code/STLLoader.cpp
code/ValidateDataStructure.cpp
test/models/STL/triangle_with_empty_solid.stl
test/unit/utSTLImportExport.cpp

Should fix issue #1970.
Also add more info to assimp_cmd when ValidateDataStructure fails.

Fix #1970 STL Ascii, failed managing "empty solid" 

---

test/unit/utLWSImportExport.cpp

It seems that the validation is now OK.
Also add a bunch of tests to try to import each file we have in this
format.

Fix #1587 : add validation to LWS unit test

---

code/STLLoader.cpp

Hi,
in [STLLoader.cc Line 353](https://github.com/assimp/assimp/blob/master/code/STLLoader.cpp#L353),
the loader checks, if there is data or not.
Everything is fine, when there is data, but when there is no data, the code block continues and executes the memcpy later in line 368. This is not a real problem, since 0 Bytes are copied, but
we also access memory which is out of the containers bound in the same line via `&positionBuffer[0].x`.
Some Debuggers, i.e. VS in Debug mode, check, whether the program accesses out-of-bound memory or not and throw an exception, if so.
This results in a failed unittest (utSTLImporterExporter.test_with_empty_solid) using a debug build.
This PR uses `std::vector::data()` instead of `&positionBuffer[0].x`, trying to have a solution with minimal changes.

Fix STL unittest in Debug mode

---

code/glTF2Importer.cpp
test/models/glTF2/BoxTextured-glTF/BoxTextured.gltf
test/unit/utglTF2ImportExport.cpp

Assimp was returning glTF/2.0 values as address modes instead of aiTextureMapModes.
Also modified text glTF/2.0 model's sampler uv address modes to mirror/clamp respectively, and tests for them in the unit test.

Properly reads in glTF/2.0 sampler address modes.

---

code/FBXConverter.cpp
code/FBXConverter.h

The code for converting an embedded texture was only in the path for FBX Textures, not LayeredTextures, so files using the latter were missing all embedded images. Factored that code out into a new function and made both paths call it.

FBX: LayeredTextures now work with embedded texture data

---

tools/assimp_cmd/CMakeLists.txt

When I generate makefile to a independent build dir by cmake like this
```
cd assimp
mkdir build
cd build
cmake -G "MSYS Makefiles" ..
make
```
It can't build . The error message is
```
E:/assimp/tools/assimp_cmd/assimp_cmd.rc:4:10: fatal error: ../../revision.h: No such file or directory
#include "../../revision.h"
^~~~~~~~~~~~~~~~~~
```
It seems that windres.exe use the source file path rather than current path, so we should add binary directory to include directories.

fix build for independent build dir (mingw)

---

code/Exporter.cpp

- Put it in front of the list of exporters
closes https://github.com/assimp/assimp/issues/2001

Make glTF2 the default exporter for glft

---

port/PyAssimp/pyassimp/helper.py

This error occurred because of error in finding .extension files.
os.path.splitext(filename)[-1].lower() not in ext_whitelist:  ### this line had bugs, failed to select files with extensions .so.x  [.so.1  .so.2  .so.3.1] but worked on simple extensions only. like- .so .dll
Added a mechanism to remove this bug.

Solved pyassimp.errors.AssimpError in conda

---

code/FBXMeshGeometry.cpp
test/unit/utFBXImporterExporter.cpp

Hi Kim,
I noticed that the fbx unit test box.fbx wasn't checking the number of meshes or vertices.
When I added this check, it appeared that this was broken and assimp reported 0 mesh.
Using git bisect, it seems that the regression appeared with PR #1735.
I'm not sure if I understand this code completely, but it seems that the check for `HasElement` has been removed when `isDirect` is true, which doesn't seem intended.

Fix fbx import regression

---

code/PostStepRegistry.cpp
code/TriangulateProcess.cpp

This patch changes two things:
1. Possible small triangles generated during triangulation are not rejected (in that post processing step). FindDegenerates can be used for that.
2. Change order of post processing steps, so that FindDegenerates runs after triangulation
This came up as a problem with one of our models, which had rather detailed geometry based on polygons. I also noted that Triangulation and FindDegenerates use different thresholds to reject triangles - Triangulation uses 1e-5 and FindDegenerates 1e-6.

Keep small triangles in triangulation

---

code/STLLoader.cpp

Add one child node to produce same scene structure as in STLImporter::LoadASCIIFile.
This PR fixes[ issue 2064](https://github.com/assimp/assimp/issues/2064)

STLImporter binary and ASCII files imports differently

---

code/FBXConverter.cpp
code/FBXConverter.h

Hello,
When importing a FBX file with a huge scene tree, the node names are checked to be unique with a time complexity in O(n²). This is the most time consuming task for importing such FBX files, so I rewrote this with a time complexity in O(n*log(n)).
Loïc

Optimisation of FBX node name uniqueness

---

CMakeLists.txt

My 64 bit Visual Studio builds were failing because I was missing /bigobj. The Ninja CMake generator I was using doesn't have Win64 in the generator name, so even though I was doing a 64 bit build, the option wasn't getting added.

Use a more accurate way of checking if the build is 64 bit

---

code/ObjFileImporter.cpp

Hello!
I added point cloud support for OBJ format import. Logic is simple: if imported file has only vertex attributes it is point cloud. Such files can be created by MeshLab for example.
New mesh added directly to root node, no child nodes will be created.
Relates to https://github.com/assimp/assimp/issues/254
[points.zip](https://github.com/assimp/assimp/files/2281356/points.zip)

Add point cloud support for OBJ importer

---

code/BVHLoader.cpp

The BVH standard states that rotation and position components can be in any order.  But the Assimp BVH reader assumes the will always be ordered with position first, followed by rotation.  
This causes BVHs like the one attached to crash.
This change fixes the issue by using a std::map to ensure correct ordering.
[take1.zip](https://github.com/assimp/assimp/files/2272216/take1.zip)

Support out of order channels in BVH

---

code/SplitByBoneCountProcess.cpp

aiNode->mMeshes is allocated with new[] rather than new.  We need to delete via delete[]
mMeshes is allocated in the importers, for example
https://github.com/assimp/assimp/blob/master/code/glTF2Importer.cpp#L753
https://github.com/assimp/assimp/blob/master/code/ACLoader.cpp#L574
etc

Use delete[] instead of delete to clear mMeshes

---

port/PyAssimp/pyassimp/core.py
port/PyAssimp/pyassimp/structs.py

1) The first commit fixes this problem:
>>> from pyassimp import *
>>> s = load('tetra.obj', processing = None)
>>> print(s.mRootNode)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "python3.5/site-packages/pyassimp/core.py", line 128, in <lambda>
target.__class__.__str__ = lambda x: x.name
AttributeError: 'LP_Node' object has no attribute 'name'
2) The second commit updates 'structs.py' with missing metadata fields that are in the C++ header files already.

Pyassimp update

---

code/D3MFImporter.cpp

Was testing out 3mf import and this occurred to me:
The displaycolor property was imported with the values directly converted from hex:
```
#00FF00 -> {0.0, 255.0, 0.0}
```
Whereas other importers use a normalized range:
```
#00FF00 -> {0.0, 1.0, 0.0}
```
Also added option of "#RRGGBB" string in addition to assumed "#RRGGBBAA" string (see chapter 5.1.1 of https://github.com/3MFConsortium/spec_core/blob/master/3MF%20Core%20Specification.md)

Correct 3MF displaycolor import

---

code/glTF2Asset.h
code/glTF2Asset.inl
code/glTF2Importer.cpp
test/unit/utglTF2ImportExport.cpp

Hi Kim, 
This pull request should fix the memory leak on #2079. 
I used mostly the same code as glTFAsset.h

Fix #2079 Memory leak 

---

CMakeLists.txt

When put assimp's code into a large repository, getting branch and commit hash couldn't really get assimp's git information. Add a new option IGNORE_GIT_HASH to skip branch and commit hash retrieval.

Add IGNORE_GIT_HASH.

---

port/AssimpNET/Readme.md

After the exchange on twitter, I noticed that this readme never actually had a link pointing to the bitbucket repository that I maintain (originally the googlecode one, and then a fork of the googlecode one that I didn't know about).
This is very confusing for people who report issues, and I would like them to make sure they can report on a tracker that I keep tabs on.

Update AssimpNet redirect

---

code/glTF2Importer.cpp

In glTF2Exporter, roughnessFactor = 1 - normalizedShininess = 1 - someFunc(sqrt(shininess / 1000)). But in gltf2Importer, roughnessAsShininess = (1 - roughnessFactor) * 1000. No sqr there. So if save a shininess to a gltf2 and load it back, the value changed.
This fix add a square to importer to make sure the consistency.

Make gltf2's roughnessAsShininess matches between importer and exporter.

---

code/MaterialSystem.cpp

It only happens on C interface, not aiMaterial::Get(). If a return buffer length is < sizeof(int32_t), it won't be copied to the output parameter.
Fix issue #1492 .

Fix the wrong results when calling aiGetMaterialInteger on bool type properties, such as AI_MATKEY_TWOSIDED

---

code/BlenderScene.cpp

Amended the key "flags" -> "flag". The field key("flags") was not matching the key("flag") in the BlendDNA. It was annoying during debug mode since the exception prompt for the mismatching key towards the DNA database.

Amended the "Key" for the database ReadField

---

code/MDLLoader.cpp

`error C4703: potentially uninitialized local pointer variable 'pcFirstFrame'` in debug mode

C4703 workaround for msvc++

---

code/D3MFImporter.cpp

Same issue as #1253 but for D3MFImporter.  The 3mf importer has its `aiImporterDesc` completely unnecessarily initialized from the value of an `std::string`, even though `std::string` cannot be initialized at constant initialization time.  This fixes a crash for us.

Fix static init ordering issue in 3mf importer

---

code/glTF2Asset.inl

Skins aren't always referenced by other nodes but may still be needed. Fixes #2227

Fix skins not always being loaded in GlTF2

---

port/PyAssimp/scripts/3d_viewer_py3.py

This was causing `SyntaxError` in python 3.7 (Windows 10)
And should now conform to the new syntax: https://www.python.org/dev/peps/pep-3110/

Fix: except `SyntaxError` for py3 viewer

---

code/CMakeLists.txt
code/ColladaLoader.cpp
code/ConvertToLHProcess.cpp
code/DefaultIOSystem.cpp
code/FBXAnimation.cpp
code/FBXConverter.cpp
code/FBXConverter.h
code/FBXDeformer.cpp
code/FBXDocument.cpp
code/FBXDocument.h
code/FBXMeshGeometry.cpp
code/FBXMeshGeometry.h
code/Importer/IFC/IFCLoader.cpp
code/ObjFileParser.cpp
code/glTF2Importer.cpp
include/assimp/IOStreamBuffer.h
include/assimp/mesh.h

Added animMesh name assignment at ColladaLoader
Fixed animMesh post-processing on ConvertToLhProcess (blend-shapes weren't being affected by post-processing)
Added WindowsStore define. This is used to change some incompatible WinRT methods
Added FBX blend-shapes and blend-shapes animations support
Added Maya FBX specific texture slots parsing
Added extra FBX metadata parsing
Added GLTF2 vertex color parsing
Fixed IFC-Loader zip-buffer reading rountine
Fixed OBJ file parsing line-breaker bug
Fixed IOStreamBuffer cache over-read bug
Added mName field to aiAnimMesh
Reverted EmissiveFactor, TransparencyFactor and SpecularFactor assignment on FBXConverter. Really, the commit #817 breaks a lot of old code.

Various additions/fixes (FBX blend-shapes support added)

---

code/Importer.cpp
include/assimp/MemoryIOWrapper.h

Goal is to support cases where the initial file has already been loaded (hence a desire to use `ReadFileFromMemory`) but there may be other files necessary to resolve.

MemoryIOSystem delegates to existing IOSystem

---

code/glTF2Exporter.cpp

Hello,
The glTF2 export crashed when there were no texture coordinates, so I added a test before reading texture coordinates.
I also fixed a warning (explicit cast from size_t to unsigned int).
Loïc

Fix glTF2 export with no texture coordinates

---

code/glTF2Asset.h
code/glTF2Asset.inl
code/glTF2Exporter.cpp
code/glTF2Importer.cpp
code/glTFAsset.h
code/glTFAsset.inl

Buffer grow changes:
The exporting of relatively large data (aprox. 7.2Gb) could take a few days, because of reallocation of a buffer every time for a few new bytes is overkill. I've introduced standard capacity member for the buffer and growth it by 1.5 times every time it needs to grow. That helps a lot, decreases exporting to a minute (from a few days).
Large file support:
glTF is a json file, all lengths and offsets don't have a type, just numbers, but code was always reading it as uint32, this doesn't work for files bigger than int32 (almost all files we have as an example). So, I've changed it to be reading as size_t. Specification doesn't specify the type for it, so it's not against spec.

glTF/glTF2 Buffer grow changes and large files support

---

code/glTF2AssetWriter.inl

This pull request fixes issue #2327 (master was not building on clang-7.0.1)
It seems that calling addMember with second parameter of type size_t is ambiguous, changed to unsigned int

Bugfix issue: #2327 Build broken on clang-7.0.1

---

code/ColladaLoader.cpp

In ColladaLoader in version 3.2.0 (release est. 2015) the name assignment was based on name attribute (xml) with optional fallbacks to id and sid. Over time this was changed to fix a bug and support for names was removed, only to be later (re)added using an optional `useColladaName` setting. We discovered a problem that with when using the name based assignment it doesn't assign automatically generated names like what it did in the logic in v3.2.0 and on the id based approach on current master.
We discovered this causes problems with matching the aiCamera and aiLight. So we rectified this problem by auto-generating names also on the name based method.

Fix automatic name assignment for ColladaLoader when using name based assignment

---

code/ValidateDataStructure.cpp
test/unit/utValidateDataStructure.cpp

I was debugging some code and noticed that the ValidationDSProcess code could give me more info than it was with a few minor tweaks (e.g. telling me what the name of the aiNode missing a parent is, etc). I thought these improvements might be handy to others.
I did notice that there doesn't appear to be a unit test for the validation code and was considering starting one. I was wondering if that'd be useful. I'm thinking something along the lines of constructing objects with exactly 1 check that should fail, and then running those objects through the validator to make sure they do. It'd be a fair bit of work, and I'm not sure I'd do all of it at once, but given that it looks like to me that basically every unit test depends on that file to make sure there are no errors, it might be effort …

Improve ValidateDataStructure error reporting

---

code/PostStepRegistry.cpp

When using aiProcess_PreTransformVertices and aiProcess_GlobalScale  at the same time, you can directly get the desired value without transforming twice.

fix: change ScaleProcess priority

---

code/ObjFileData.h
code/ObjFileImporter.cpp
code/ObjFileParser.cpp
code/ObjFileParser.h

mNumUVComponents used to be set to 2 irrespective of loaded data. This fix tracks the number of loaded uv coordinates and propagates it.

fix loading 3D uvs from obj

---

code/CMakeLists.txt

Mimics the `ASSIMP_BUILD_ALL_IMPORTERS_BY_DEFAULT` / `ASSIMP_BUILD_XXX_IMPORTER` code but for exporters:
`ASSIMP_BUILD_ALL_EXPORTERS_BY_DEFAULT` / `ASSIMP_BUILD_XXX_EXPORTER`
This works exactly the same way with one exception - `ASSIMP_NO_EXPORT` still overrides everything and turns off all exporting.
Fixes #2377

Add a way to select which exporters you want to compile in

---

CMakeLists.txt

The AMD64 option causes a build failure on MSVC (#1760) and the ASM builds seem to have problems:
https://github.com/madler/zlib/issues/41#issuecomment-125848075
This change also prevents these options from "polluting" the cmake options if assimp is being included as a submodule.

{cmake} Explicitly turn off ASM686 & AMD64 options when ASSIMP_BUILD_ZLIB is on

---

port/PyAssimp/pyassimp/core.py
port/PyAssimp/pyassimp/formats.py
port/PyAssimp/pyassimp/helper.py
port/PyAssimp/pyassimp/postprocess.py
port/PyAssimp/pyassimp/structs.py
port/PyAssimp/scripts/fixed_pipeline_3d_viewer.py
port/PyAssimp/scripts/sample.py
scripts/BlenderImporter/genblenddna.py
scripts/StepImporter/CppGenerator.py
scripts/StepImporter/ExpressReader.py

Fix a number of lgtm alerts:
* port/PyAssimp/pyassimp/core.py: use correct raise RuntimeError(string) rather than deprecated/removed raise string
* Fix apparent typo in scripts/StepImporter/CppGenerator.py. @kimkulling may want to review this one - it appears to have been a typo that went uncaught in get_hierarchy because I guess that method is never called in the tests. But I could be missing something here, I didn't write the original code. I just noticed that lgtm noted an error, and the error was that a method was called with 1 argument, e.hierarchy, whereas the related methods are all called with arguments e, hierarchy
* More to come

Fix lgtm alerts

---

code/AssxmlExporter.cpp
code/BlenderDNA.h
code/COBLoader.cpp
code/D3MFOpcPackage.cpp
code/FBXConverter.cpp
code/FBXMaterial.cpp
code/IRRLoader.cpp
code/Importer/STEPParser/STEPFileReader.cpp
code/MD5Loader.cpp
code/STLExporter.cpp
code/glTFExporter.cpp
tools/assimp_cmd/ImageExtractor.cpp

BlenderDNA.h:
* Fix rethrow that would crash the program.
* QUESTION: am I throwing the right exception here.
COBLoader.cpp:
* catch exception by const ref
* fix equality checks using strncmp that weren't actually checking equality
FBXMaterial.cpp:
* Catch exception by const ref (+ Debug log that it did so)
FBXConverter.cpp:
* Rename local variables to avoid shadowing parameter
*  Another shadowed variable fix
ImageExtractor.cpp:
* Remove duplicated/unreachable code
IRRLoader.cpp:
* Rename local variable to avoid shadowing parameter
* Removed empty else statement
* Added minor note to the documentation about possibly unused Animation functionality 
MD5Loader.cpp:
* Fix 2 shadowed variables
STLExporter.cpp:
* Throw error instead of silently ignoring unimplemented option
Misc empty blocks …

Fix more LGTM Alerts

---

code/FBXConverter.cpp
include/assimp/material.h

We are switching from FBXSDK to Assimp. FBXSDK already has a way of fetching the "TransparencyFactor" from a material, which we need to support some models that don't use standard materials (exported from CAD software). We needed the same in Assimp, and there might be other users who need it too. I think it's good to expose this property since it's something FBX SDK already does.
See the description here: https://github.com/assimp/assimp/issues/2393

issue_2393: Added AI_MATKEY_TRANSPARENCYFACTOR

---

code/FBXMaterial.cpp

If available, use "Scaling" and "Translation" instead of "ModelUVScaling" and "ModelUVTranslation". This seems to be what 3DS Max and FBX SDK use.
See comment here: https://github.com/assimp/assimp/issues/2043
> I have done some testing, and as far as I can see "ModelUVScaling" and "ModelUVTranslation" have no effect on 3DS Max. When exporting from 3DS Max these are always set to the default values (scale: 1,1; offset: 0,0).
So all models I export from 3DS Max get the wrong UV scale when using Assimp. However, when using FBX SDK I can fetch the correct UV scale using FbxTexture::GetUVScaling(). The value returned is the one stored in "Scaling".
So far I haven't seen any models where  "ModelUVScaling" and "ModelUVTranslation" are used.
Please let me know if you have any information and …

Suggested fix for issue 2043

---

include/assimp/color4.inl

The element access operator of `aiColor4D` doesn't point to the alpha component by index 3. Instead, it points to the red component, which is not the expected behavior I believe. This is because [the operator is missing a case for index 3](https://github.com/assimp/assimp/blob/55cdf1d37c4ecd973c2a2e134e213cf32a772635/include/assimp/color4.inl#L94-L107). This PR fixes it by adding the missing case.

Fix element access operator of aiColor4D

---

code/FBXCommon.h
code/FBXExportNode.cpp
code/FBXExportNode.h
code/FBXExportProperty.cpp
code/FBXExportProperty.h
code/FBXExporter.cpp
code/FBXUtil.cpp
code/FBXUtil.h
include/assimp/scene.h

Added support for embedded textures to the FBXExporter (both binary and ASCII).
Also made the FBX-namespaces more consistent (we had both Assimp::FBX:: and FBX::).
Since we seem to support two types of embedded texture references (both asterisk+texture_id and filepath) I made the exporter use aiScene::GetEmbeddedTexture for looking up texture reference and integrated @loebl 's modification of the function to support the old ("*1") type of references (https://github.com/loebl/assimp/commit/e217358)
See https://github.com/assimp/assimp/issues/1838 for more info about this.
**This fixes the following issues:**
https://github.com/assimp/assimp/issues/1280
https://github.com/assimp/assimp/issues/1838

FBXExporter: Embedded texture support

---

code/FBXExportNode.cpp

**The fix:**
Don't call PutString with an empty string. Both DumpChildrenAscii and EndAscii can return without modifyting the string, so we need to check the string before calling PutString.
This used to cause a crash.

Fix for crash in StreamWriter::PutString when exporting ASCII FBX

---

code/res/assimp.rc

assimp.rc contains an include with a double-parent header search.
In a default build configuration, this is resolved via the
configuration header path generated for in-tree zlib.
When external zlib is used, this header search path is not provided
to the RC compiler, therefore fails to find revision.h.
This is solved by simply including "revision.h" since the root of
the binary directory is already used as a search path.

Fix Windows build with external zlib

---

code/CMakeLists.txt

These properties allow assimp to be installed as a static library along with its PDB. The dynamic PDB will continue to take precedence unless the builder has disabled BUILD_SHARED_LIBS.

Set directory and name properties for installing static lib PDB

---

code/FBXMaterial.cpp

It throws an exception too many times just 3 lines below
`const Token& token = GetRequiredToken(*Content, 0);`
though we can easily avoid it to check if there is any token to process.

Exception spam fix for FBXMaterial

---

.gitignore
include/assimp/defs.h

- allows the use of noexcept in MSVC versions >= 1915 (previous was == 1915??)
- adds some more visual studio build detritus to gitignore

quality-of-life improvements for Visual Studio

---

code/FBXParser.cpp

It casts to float and loses precision for large coordinates even if ASSIMP_DOUBLE_PRECISION defined

FBX Importer double precision fix

---

port/PyAssimp/pyassimp/core.py

Verify that there is something there before inspecting it.
Fixes the error below:
```
File "C:\Users\micro\build2\boxwin_external_libs\pyassimp\core.py", line 320, in load
scene = _init(model.contents)
File "C:\Users\micro\build2\boxwin_external_libs\pyassimp\core.py", line 206, in _init
raise e
File "C:\Users\micro\build2\boxwin_external_libs\pyassimp\core.py", line 187, in _init
call_init(e, target)
File "C:\Users\micro\build2\boxwin_external_libs\pyassimp\core.py", line 80, in call_init
_init(obj.contents, obj, caller)
File "C:\Users\micro\build2\boxwin_external_libs\pyassimp\core.py", line 214, in _init
if _is_init_type(obj):
File "C:\Users\micro\build2\boxwin_external_libs\pyassimp\core.py", line 86, in _is_init_type
if helper.hasattr_silent(obj,'contents'): #pointer
File …
```

Ensure obj is not null before using hasattr

---

code/Common/Importer.cpp

Issue #2518 
Adds an Import property "importerIndex" that contains the index of the importer that was selected, or -1 if none of the importers matched the provided file/blob.

API: Add active importer identification

---

code/FBX/FBXConverter.cpp
test/unit/utFBXImporterExporter.cpp

`FBXConverter::GetTexturePath` returns RelativeFilename() for all textures (this is stored in the material $tex.name), but `FBXConverter::ConvertVideo` returns FileName() as a texture name, so it's very hard to match both strings in run-time to figure out which embedded texture it is.
I propose to use relative path everywhere, that helps a lot.

All textures use relative path except embedded textures, this is a fix for it

---

include/assimp/types.h

```
assimp/include/assimp/material.inl: In member function 'aiReturn aiMaterial::Get(const char*, unsigned int, unsigned int, aiColor3D&) const':
assimp/include/assimp/material.inl:176:33: error: implicitly-declared 'aiColor3D& aiColor3D::operator=(const aiColor3D&)' is deprecated [-Werror=deprecated-copy]
176 |     pOut = aiColor3D(c.r,c.g,c.b);
```

Fix a GCC 9 warning:

---

code/FBX/FBXConverter.cpp

Thank you @kimkulling so much for making the blendshapes work with the multi-material meshes, your work is amazing and has helped us tremendously! I found a few minor issues, but I've been able to fix these myself.
- Fixed anim meshes generated from blendshapes not being copied to output for multi-material meshes
- Fixed first vertex of each blendshape on a multi-material mesh having all unmapped vertice offsets being added to it
- Fixed blendshapes not importing for multi-material FBX meshes with no bones

Some FBX multi-material mesh fixes

---

code/Obj/ObjFileParser.cpp
test/unit/utObjImportExport.cpp

Hi,
This fix to the OBJ parser reverts a faulty line from a January [commit](https://github.com/assimp/assimp/commit/35a044bda37b2bad50a41746622c746acd139631).
Some OBJ files have backslashes for line continuations, like in [this documentation](http://paulbourke.net/dataformats/obj/) or in OBJ files exported from Rhino for instance.
In such cases
`v 0.00000000001 0.00000000002 \`
`0.00000000003`
is equivalent to
`v 0.00000000001 0.00000000002 0.00000000003`
Assimp's OBJ parser dealt successfully with this case via the [getNextDataLine()](https://github.com/assimp/assimp/blob/475e51d157e7826bdcbc0d88e6a73b1764960e0a/include/assimp/IOStreamBuffer.h#L244) method which role is specifically to join lines separated by a continuation character (`\` in our case).
However, its usage was changed in …

Fix line continuations in OBJ files

---

code/FBX/FBXConverter.cpp
code/FBX/FBXConverter.h
code/FBX/FBXDocument.cpp
code/FBX/FBXExporter.cpp
code/FBX/FBXMeshGeometry.cpp

This also fixes issue with root bone overwritten - which should not happen as it is a hack.
Before the behaviour would create an additional bone which would end up breaking animations completely on import.
Additionally this fixes required bones being removed.
Co-authored-by: K. S. Ernest (iFire) Lee <ernest.lee@chibifire.com>

FBX importer armature fixes and root bone fixes - animations should now work for more models.

---

code/X3D/X3DImporter.cpp

std::iterator is deprecated in C++17. When using /std:c++17 in MSVC, WordIterator generates some warnings. Remove the usage of std::iterator to avoid future compilation problems.

Remove the usage of std::iterator

---

code/glTF2/glTF2Asset.h
code/glTF2/glTF2Asset.inl
code/glTF2/glTF2AssetWriter.inl
code/glTF2/glTF2Importer.cpp

Importing of lights according to glTF 2.0 extension KHR_lights_punctual https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_lights_punctual
Since glTF lights are based on PBR they use different attenuation model than conventional lights supported by assimp. It is possible to use attenuation factors in assimp to describe inverse square law fallof. But the light structure does not provide means to save range property. Therefore I resorted to use of metadata. When range parameter is present, I put it into 'PBR_LightRange' metadata of light's node. Please, see comment in glTF2Importer file.

glTF 2.0 Lights import

---

.github/FUNDING.yml

Changes proposed in this request:
- Adds the GitHub sponsors button. Here's an example with playnite:
https://github.com/JosefNemec/Playnite
Info from GitHub on this below:
```
.github/FUNDING.yml shows the community how to support this project. Please see our repository funding links [documentation ](https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository) for more information on formatting and what is and isn't allowed in this file.
Please note that funding links are currently disabled on this repository. Visit repository settings to enable display of your funding links.
```

Add GitHub sponsors button to feature patreon

---

code/FBX/FBXImporter.cpp
code/FBX/FBXMeshGeometry.cpp

This is an urgent hotfix for an issue with FBX reading.
This fixes scaling being off by 100 units, apologies testing methodology was wrong and has now been corrected. (FBXExporter doesn't file UnitScale therefore this was broken when I was testing)
I tested by importing model into Godot and seeing the visual scaling results.
I will submit a bug for the meta data missing on FBX Export (it's not handled at the moment / not implemented)

[WIP] Fix FBX units not being converted from CM to application scale

---

code/FBX/FBXMeshGeometry.cpp

Fixes segfault with models with missing faces.
This can be a common thing if a modeller makes a mistake so unfortunately we must not crash the entire importer because this means you can't import some models.
This ensures compatibility even with bad modelling practices because humans aren't perfect.

Fix segfault #2614

---

code/Common/BaseImporter.cpp
code/FBX/FBXConverter.cpp
code/FBX/FBXConverter.h
code/FBX/FBXImporter.cpp
include/assimp/BaseImporter.h

This is hotfix for FBX scaling issues we were experiencing in godot. This is another urgent fix.
Before the compiled scale was not processed properly.
I also removed depreciated scaling code from the FBX system.
I have tested this code with 5 models and seems to be okay with CM to M scaling, and various other units.

FIX missing File Scale and Application scale fixes for all conversions 

---

code/Common/Exporter.cpp
code/PostProcessing/MakeVerboseFormat.cpp
code/PostProcessing/MakeVerboseFormat.h

This trivial change allows IsVerboseCheck to be called outside the exporter, and means that it's possible for other code to check for verbose format without having to reimplement the logic.

Make IsVerbose accessible outside the exporter

---

code/FBX/FBXConverter.cpp
include/assimp/material.h

This is to support Maya materials properly from FBX Importer.
This adds the following texture types:
- BASE_COLOR
- NORMAL_CAMERA
- EMISSION_COLOR
- METALNESS
- DIFFUSE_ROUGHNESS
- AMBIENT_OCCLUSION
Here is an example of the work in use:
https://github.com/godotengine/godot/pull/32019
Reuses existing API as it is fairly simple to use.
The existing 'ambient', 'normal' maps are not the same shading method, therefore I opted to implement proper enums for them, as they're for the legacy format only, which is easier to support than the PBR / PBS route.

FBX Implemented basic PBR material textures

---

code/X/XFileParser.cpp

Closes #2603 
Normal face indices added to end of already resized vector, so normal faces did not match position faces.
Use vector index rather than push.

Issue 2603

---

code/Collada/ColladaExporter.cpp

This PR fixes issues #2551 , where a separator is missing in the textures export path.

fix issue #2551

---

code/PostProcessing/ComputeUVMappingProcess.cpp

The projection of textures along z axis is currently projecting along the x axis.

Fix UV texture coords generation along Z Axis

---

Build.md
Readme.md

Assimp is available as a port in vcpkg. Adding installation instructions will help users get started by providing a single set of commands they can use to build assimp and include it into their projects

Add vcpkg installation instructions

---

code/Common/Version.cpp
test/unit/utVersion.cpp

closes https://github.com/assimp/assimp/issues/2693 .
Fix version mismatch.

Enginmanap issue 2693

---

cmake-modules/Findassimp.cmake

Add /usr/lib64 and /usr/lib directory hints to cmake module
libassimp.so library installs in /usr/lib for 32bit or
in /usr/lib64 for 64bit distros.
All linux distros apply custom patch to extend cmake HINTs to
systems /usr/lib and /usr/lib64
(see https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/assimp/files/findassimp-3.3.1.patch)
Signed-off-by: Maksym Sditanov <msditanov@200volts.com>

Findassimp.cmake: add hint for lib search path for Linux

---

assimpTargets.cmake.in

Using CMake 3.15 & Visual Studio 2019 to build on windows produced a cmake configuration which was unable to be used by clients.  Investigating this I was eventually able to determine this was caused by a mismatch in the target properties.  Specifically, it was setting the TYPE property to STATIC_LIBRARY even though it was building as a SHARED_LIBRARY.  
This in turn was because the if clause on line `if(@BUILD_SHARED_LIBS@)` of this file was evaluating to `if (ON)` which was then not properly evaluated while under the CMake 2.6 policy.  Explicitly setting the `CMP0012` policy to NEW fixes the problem.
Fixes bug #2721

Fix CMake import

---

code/FBX/FBXCompileConfig.h
code/FBX/FBXConverter.cpp
code/FBX/FBXConverter.h
code/FBX/FBXDocument.h
test/models/FBX/box_orphant_embedded_texture.fbx
test/unit/utFBXImporterExporter.cpp

Embedded textures in FBX could be connected to nothing but to itself,
for instance a `Texture` -> `Video` connection only but no connection to the main graph,
It is fixes #2742
the idea here is to traverse all objects to find these Textures and convert them,
so later during material conversion it will find converted texture in the textures_converted array.
I added unit test as well.
Bonus change: I replaced some `std::map` to `std::unordered_map` that significantly speed up the import stage.

FBX orphan embedded textures fix

---

code/Common/DefaultIOStream.cpp
code/FBX/FBXCommon.h
code/FBX/FBXExportNode.cpp
code/FBX/FBXExporter.cpp

Here are two issues fixed:
1. It fixes #2749 , on Windows with 64-bit it now uses `ftelli64` and `fseeki64` to fix a `long` type is being 4 bytes on Windows
2. it fixes #2750 , FBX Exporter uses a version 7.4 by default that not supports 64-bit offsets, I changed the version to 7.5 and fixed relevant code, so now it's possible to export FBX bigger than 2GB and it is very small overhead to use 64-bit offsets in general.

Fix for exporting fbx bigger than 2GB

---

include/assimp/defs.h

For C++98 setups, the compilation of some projects depending on assimp is failing due to the use of `noexcept` keyword on non-Windows compilers. This PR fixes the issue.

BUG - use noexcept only for C++11 and more

---

code/Common/Version.cpp
include/assimp/version.h

Hello,
Currently it is only possible to display "Assimp 5.0 (commit XXXXXXX)". The patch version (3rd number) is missing. This pull request just adds a function to be able to display "Assimp 5.0.0 (commit XXXXXXX)" (or "Assimp 4.0.1 (commit eb8639d)" like the Git tag of 28th July 2017).
Loïc

Add function aiGetVersionPatch() to be able to display Assimp version as in Git tags

---

assimpTargets-release.cmake.in

When on macOS, reverse the shared lib naming convention (as compared to
Linux) to put the version number before the the lib extension.
Fixes #2760

Fix shared lib name on macOS

---

code/Common/Importer.cpp
code/FBX/FBXConverter.cpp
code/FBX/FBXConverter.h
code/glTF/glTFImporter.cpp
code/glTF/glTFImporter.h
code/glTF2/glTF2Importer.cpp
code/glTF2/glTF2Importer.h
include/assimp/commonMetaData.h
include/assimp/metadata.h
test/unit/utFBXImporterExporter.cpp
test/unit/utglTF2ImportExport.cpp
test/unit/utglTFImportExport.cpp

Many asset formats carry informative metadata, such as a record of the software used to generate them. In the same spirit, this change adds metadata to the aiScene about the format the file was imported from, and also preserves the generator information, when available.
The "SourceAsset_Format" metadata is the name of the importer. Since that is available in one common place, I set it for all formats. The other two metadata values need to be populated by the importers themselves. I've only done this for FBX and GLTF (version 1 and 2). Support for other formats can be added as needed.
Unit tests for FBX and GLTF are included in this PR.

Modeller meta data

---

code/Collada/ColladaHelper.h
code/Collada/ColladaLoader.cpp

Hello,
We were experiencing problems with the Collada importer when dealing with files that had more than one single-channel animation. The problem was that Assimp was combining all single-channel animations, without checking if the channel was the same.
This PR adds a check to properly avoid combining the single-channel animations when they are animating the same channel. When they are animating different channels, they are still being combined as expected.

fix: Don't combine Collada animations when channels are shared

---

code/Ply/PlyExporter.cpp

The Ply format standard doesn't preclude Ply files from containing faces with 0 vertices. In the current existing code, faces with 0 vertices are being written incorrectly because the for loop would never write the endline character if the number of indices was 0. 
This change fixes that behavior by writing a space character before each index and then adding the endline character outside of the loop.

Fix PlyExporter to support faces with 0 vertices

---

code/glTF2/glTF2Exporter.cpp

Hello,
The glTF2 exporter crashes if the scene has no metadata (since commit 986b6780 on 9th december). I have just added a check to avoid that.
Loïc

Fix possible null pointer exception on scene metadata when exporting a glTF2 file

---

code/glTF/glTFAsset.inl
code/glTF/glTFExporter.cpp
code/glTF/glTFExporter.h
code/glTF2/glTF2Asset.inl
code/glTF2/glTF2Exporter.cpp

1. There are some memory leak, the root cause is that exporters take ownership of data when texture is not embedded and do not take ownership when texture is embedded.
2. gltf exporter duplicates scene but not frees it.
3. Check null pointer before use it.

Fix: gltf exporting memory leak

---

code/MDL/MDLLoader.cpp

This is needed since it's possible to have an MDL sequence group file that has a size less than the Quake 1 MDL header.

[MDL] Updated header to use when checking file size. (Redone)

---

code/MDL/MDLLoader.cpp

If an exception is propagated from one of the MDL implementations and is uncaught, or because of an unknown MDL format, the memory allocated at **mBuffer** may never be freed.

Fixed memory leak in MDL importer.

---

code/FBX/FBXConverter.cpp

Fixes MSVC++ warning C4101: 'e': unreferenced local variable

Removed name of unreferenced local variable in catch block

---

test/unit/utBlenderImportExport.cpp

Many of these currently fail and at least some of them appear to be unchanged from when they were added to the repository. I tried some of them in Blender 2.80 with mixed results. `Bob.blend` crashes blender whereas `TorusLightsCams_250_compressed.blend` loads successfullly in Blender but not in assimp. I have no idea what's going on here and have just codified the current behavior as expected. At least now we'll notice if their status changes.

Add all shipped .blend files to unit tests

---

test/CMakeLists.txt
test/unit/ImportExport/utMD3Importer.cpp
test/unit/ImportExport/utXGLImportExport.cpp
test/unit/ut3DImportExport.cpp
test/unit/utACImportExport.cpp
test/unit/utXImporterExporter.cpp

There's a test for `dwarf.x` but it's disabled until #2935 is fixed.

Add more unit tests

---

code/Common/SceneCombiner.cpp

`dest` is allocated from `aiMetadata::Alloc`, which returns an `aiMetadata` instance will all members allocated, including `dest->mValues`. See the following code below.
https://github.com/assimp/assimp/blob/78b074ac5aa3ff3573675d49d154b358ba8e9700/code/Common/SceneCombiner.cpp#L1312-L1315
`dest->mValues` is allocated again, which makes it lose track of the previously allocated memory and results in a memory leak.

Fixed mValues allocated twice in SceneCombiner.cpp.

---

code/COB/COBLoader.cpp
code/Importer/IFC/IFCCurve.cpp
code/MDL/MDLLoader.cpp
code/XGL/XGLLoader.cpp

1. Fix misleading indentation warnings.
2. Fix creating a temporary const copy when iterating over a map (thanks to range analysis warnings)
3. Fix creating a copy when iterating over a range without reference qualifier (also thanks to range analysis warnings)
Closes #2975

Fixed a bunch of clang warnings

---

code/CMakeLists.txt
code/Common/material.cpp
code/PostProcessing/ProcessHelper.cpp
code/PostProcessing/ProcessHelper.h
include/assimp/material.h
tools/assimp_cmd/Info.cpp
tools/assimp_cmd/WriteDump.cpp

[Link to issue](https://github.com/assimp/assimp/issues/2964).
- Moved TextureTypeToString to it's own file.
- Added new file to CMakeLists.txt.
- Added 6 missing values in TextureTypeToString.
- Added 6 missing aiTextureType enum values in assimp_cmd/Info.cpp.

Fixed TextureTypeToString defined multiple times.

---

code/FBX/FBXMeshGeometry.cpp

In the _"ByVertice"_ case, `tempData.size()` needs to be equal to `mapping_offsets.size()`, not equal to `vertex_count`.
This is hopefully the last PR on this topic.

Fixed size check to use correct value

---

code/glTF2/glTF2Importer.cpp

In gltf2, camera positions are specified in nodes by transforms, whilst other data such as projection and perspective are stored in the camera part itself. This sets the `aiCamera.mPosition` to be the translation specified in the camera's node, if any. An example of a file which might do this can be seen [here](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Cameras/glTF/Cameras.gltf)

Use the translation matrix in gltf2 cameras for aiCamera.mPosition

---

samples/SimpleTexturedOpenGL/CMakeLists.txt
samples/SimpleTexturedOpenGL/SimpleTexturedOpenGL/src/model_loading.cpp

Several places in the sample's code were calling Unicode versions of Win32 functions with "multibyte" strings. A few changes were required to fix it.
I added a class **UTFConverter**, which handles calls to unicode/multibyte string conversions. This should help minimize the impacts on code change in case C++'s codecvt_utf8 ever changes.
In addition, seveal memory leaks have been found, but these fixes will come in another PR because it goes beyond the scope of this PR.
DevIL.lib was removed in CMakeFiles.txt, as it is unused in the sample.
Here is a list of the changes:
- Fixed MB string calls to Unicode functions.
- Added class UTFConverter to handle string conversions.
- Removed reference to DevIL.lib.
- Fixed compile warnings.

Fixed SimpleTexturedOpenGL sample.

---

.clang-format

-  Update clang.format to keep formatting of hashes in include file to optimize readabilaty.

Keep post-processor intentions

---

code/Common/SplitByBoneCountProcess.cpp

Fix for #3037 infinite loop.
Basically if single face requires more than `mMaxBoneCount` then splitting cannot be performed.

Fix for #3037 [FATAL] SplitByBoneCountProcess::SplitMesh goes into infinite loop

---

include/assimp/matrix3x3.h
include/assimp/matrix3x3.inl

The class `aiMatrix3x3t` has 2 operator overloading methods as well as an `Equal` method, which all take an `aiMatrix4x4t` as the input parameter. Please correct me if I am wrong, but I believe it was rather meant to be an `aiMatrix3x3t`.
See the files below:
https://github.com/assimp/assimp/blob/1e2c3c9c016d7a557a364161ac3cd8fbee16c72d/include/assimp/matrix3x3.h#L96-L99
https://github.com/assimp/assimp/blob/1e2c3c9c016d7a557a364161ac3cd8fbee16c72d/include/assimp/matrix3x3.inl#L144-L148
The following changes were tested with the following projects:
* assimp
* assimp_cmd
* assimp_simpleogl
* assimp_simpletextureddirectx11
* assimp_simpletexturedogl
* assimp_viewer
* unit

Fixed wrong matrix type used in aiMatrix3x3t comparison operators.

---

port/PyAssimp/pyassimp/core.py

This PR fixes an odd error I ran into. I attempted to load the
`african_head.obj` model from
[here](https://github.com/vahidk/tf.rasterizer/tree/a257e168033e34921bf2b184bf4ba5f5ef41296e/data/african_head)
using the following snippet:
```
git clone https://github.com/vahidk/tf.rasterizer
cd tf.rasterizer
python3 -c 'import pyassimp; mesh = pyassimp.load("data/african_head/african_head.obj")'
```
This resulted in an error with a strange backtrace:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/bb/ml/shawwn-gpt-2-watchdog/venv/lib/python3.7/site-packages/pyassimp/core.py", line 324, in load
scene = _init(model.contents)
File "/Users/bb/ml/shawwn-gpt-2-watchdog/venv/lib/python3.7/site-packages/pyassimp/core.py", line 219, in _init
call_init(obj, …
```

Only try to initialize members whose name starts with 'm' followed by an uppercase character

---

CMakeLists.txt
code/CMakeLists.txt
contrib/CMakeLists.txt

When libraries are included as submodules in large projects, having an option with a generic name like "BUILD_DOCS" is not very helpful. (e.g. one project I work on includes many libraries as submodules)
It can also clash with options from other libraries which can break things.
So prefix externally-visible options with "ASSIMP_".
(Also fixes a small capitalization error - "DIsable" - in ASSIMP_INSTALL.)

{cmake} Prefix options to avoid pollution when included as a submodule

---

code/Common/Assimp.cpp
include/assimp/cimport.h
include/assimp/quaternion.h
include/assimp/quaternion.inl

[Link to issue](https://github.com/assimp/assimp/issues/3059).
I wrote several tests to ensure the API functions return the same result as the C++ methods. A new pull request containing the tests will be submitted after the current changes are merged.
The C API functions that have been added are the following:
2D vector functions:
- aiVector2AreEqual
- aiVector2AreEqualEpsilon
- aiVector2Add
- aiVector2Subtract
- aiVector2Scale
- aiVector2SymMul
- aiVector2DivideByScalar
- aiVector2DivideByVector
- aiVector2Length
- aiVector2SquareLength
- aiVector2Negate
- aiVector2DotProduct
- aiVector2Normalize
3D vector functions:
- aiVector3AreEqual
- aiVector3AreEqualEpsilon
- aiVector3LessThan
- aiVector3Add
- aiVector3Subtract
- aiVector3Scale
- aiVector3SymMul
- aiVector3DivideByScalar
- …

Added missing functionalities to C API.

---

code/FBX/FBXConverter.cpp
code/FBX/FBXConverter.h

Added pre and post rotation handling to FBXConverter::GenerateSimpleNodeAnim. Fixed quaternion interpolation flip. Cleaned code.

Fixed FBX simple anim pre/post rotation handling

---

test/unit/ImportExport/utCOBImportExport.cpp
test/unit/ImportExport/utOFFImportExport.cpp
test/unit/ImportExport/utOgreImportExport.cpp
test/unit/ImportExport/utQ3BSPFileImportExport.cpp
test/unit/ut3DSImportExport.cpp
test/unit/utAMFImportExport.cpp
test/unit/utASEImportExport.cpp
test/unit/utArmaturePopulate.cpp
test/unit/utAssbinImportExport.cpp
test/unit/utB3DImportExport.cpp
test/unit/utDXFImporterExporter.cpp
test/unit/utFBXImporterExporter.cpp
test/unit/utM3DImportExport.cpp
test/unit/utPMXImporter.cpp
test/unit/utSTLImportExport.cpp
test/unit/utX3DImportExport.cpp
test/unit/utXImporterExporter.cpp

The header [SceneDiffer.h](https://github.com/assimp/assimp/blob/master/test/unit/SceneDiffer.h) is included in several unit test files, but these tests do not make use of the **SceneDiffer** class.

Removed unneeded SceneDiffer.h includes.

---

CMakeLists.txt
assimp.pc.in
assimpTargets-debug.cmake.in
assimpTargets-release.cmake.in
assimpTargets.cmake.in

Emulate the `CMAKE_INSTALL_FULL_*` variables on non-Unix systems and disable redefining FHS-mandated install locations via user-editable `ASSIMP_*_INSTALL_DIR` variables. Instead, if it REALLY proves necessary, Unix users can edit the advanced, canonical `CMAKE_INSTALL_*` variables.

use GNUInstallDirs where possible

---

samples/SimpleOpenGL/Sample_SimpleOpenGL.c

[Link to issue](https://github.com/assimp/assimp/issues/3123).
The following changes fix compile warnings for sample project SimpleOpenGL.

Fixed /W4 compile warnings in sample SimpleOpenGL.

---

samples/SimpleTexturedDirectx11/SimpleTexturedDirectx11/Mesh.h
samples/SimpleTexturedDirectx11/SimpleTexturedDirectx11/ModelLoader.cpp
samples/SimpleTexturedDirectx11/SimpleTexturedDirectx11/ModelLoader.h
samples/SimpleTexturedDirectx11/SimpleTexturedDirectx11/main.cpp

[Link to issue](https://github.com/assimp/assimp/issues/3123).
The following changes fix compile warnings for sample project SimpleTexturedDirectx11.
A few notes about the changes:
- Several class member variables have been renamed to reduce the risk of running into name conflicts in the future.

Fixed /W4 compile warnings in sample SimpleTexturedDirectx11.

---

CMakeLists.txt
assimp.pc.in
assimpTargets-debug.cmake.in
assimpTargets-release.cmake.in
assimpTargets.cmake.in

Emulate the `CMAKE_INSTALL_FULL_*` variables on non-Unix systems and disable redefining FHS-mandated install locations via user-editable `ASSIMP_*_INSTALL_DIR` variables. Instead, if it REALLY proves necessary, Unix users can edit the advanced, canonical `CMAKE_INSTALL_*` variables.
This is cherry-picked from the `assimp_5.0_release` branch, but there were some conflicts, so I'd advise integration testing this, as well. I can only say that it builds on Gentoo box ;-)

use GNUInstallDirs where possible (master branch)

---

tools/assimp_view/Display.cpp
tools/assimp_view/LogWindow.cpp
tools/assimp_view/Material.cpp
tools/assimp_view/MessageProc.cpp
tools/assimp_view/assimp_view.cpp

[Link to issue](https://github.com/assimp/assimp/issues/3123).
The following changes fix compile warnings for project Assimp viewer.
These changes have been tested in 32 bit and 64 bit builds, and compared against a build from master. Both appear to show similar results.
The following models were used for testing:
- test/models/OBJ/spider.obj
- test/models-nonbsd/MD5/Bob.md5mesh
The following functionalities were tested:
**Menu / Toolbar**
[Viewer]
*Note: Import settings were left to default.*
- Open asset
- Close asset
- Reload
- Reset view
- Memory consumption
- Clear history
- Save Screenshot
[Tools]
- Log window
- Clear log
- Original normals
- Hard normals
- Smooth normals
- Flip normals
- Stereo view
[Background]
- Set color
- Load texture
- Clear background
**Control panel** …

Fixed /W4 compile warnings in Assimp viewer.

---

contrib/stb_image/stb_image.h
samples/SimpleTexturedOpenGL/SimpleTexturedOpenGL/src/model_loading.cpp

[Link to issue](https://github.com/assimp/assimp/issues/3123).
The following changes fix compile warnings for sample project SimpleTexturedOpenGL.

Fixed /W4 compile warnings in sample SimpleTexturedOpenGL.

---

assimpTargets-debug.cmake.in
assimpTargets-release.cmake.in

These seem to have survived from the migration to GNUInstallDirs in
9fb81c3be6dc30139ea32c92046c9794dca0e73e
_INSTALL_PREFIX was not set anywhere and resolved to empty value, which
in turn caused some paths in the installed lib config CMake files to
start from '/', effectively causing the failure of the "do the installed
files exist" checks.
After complete replacement of all uses of the _INSTALL_PREFIX with
GNUInstallDirs equivalents, the LIBSUFFIX variable has become unused
and can be removed too.
This is an amendment to PR #3126.

Erase the remaining _INSTALL_PREFIX and LIBSUFFIX in CMake files

---

code/glTF2/glTF2Asset.inl
code/glTF2/glTF2Importer.cpp
include/assimp/camera.h

Merge to fix missing orthographic camera data in glTF2. Fixes #3028.

Fix to read orthographic camera data

---

.github/workflows/ccpp.yml
CMakeLists.txt
code/ASE/ASEParser.cpp
code/Blender/BlenderBMesh.cpp
code/CApi/AssimpCExport.cpp
code/CMakeLists.txt
code/Common/SceneCombiner.cpp
code/M3D/m3d.h
contrib/irrXML/irrString.h

- Enable building with `gcc` on Linux;
- Fix warning (mostly uninit'ed data);
- Remove some explicit flags specific for `gcc` with CMake "portable" ones;
- Use warning as error only on `assimp` target, not on 3rd party dependencies;

Enable gcc on Linux on CI, fix warnings

---

code/AssetLib/glTF2/glTF2Asset.inl

This is to fix gltf2 import bug: blendshapes (morph targets) are missing. 
It seems an index i (refers to primitive) is wrongly used as target index. Thus one primitive eventually only has one target.
This pr just change the target index to the right one.

Fix for issue# 3206: GLTF2 blendshape import missing shapes https://github.com/assimp/assimp/issues/3206

---

code/CMakeLists.txt

Without this patch building framework for macOS fails with the following error:
```
$ cmake CMakeLists.txt
$ make -j4
...
...
...
Copying OS X content bin/assimp.framework/Versions/C/Headers/config.h
[ 90%] Linking CXX shared library ../bin/assimp.framework/assimp
Copying public ./Compiler/ header files to framework bundle's Headers/Compiler/
Error copying directory from "../../include/assimp/Compiler" to "assimp.framework/Headers/Compiler".
make[2]: *** [code/CMakeFiles/assimp.dir/build.make:3316: bin/assimp.framework/Versions/C/assimp] Error 1
make[2]: *** Deleting file 'bin/assimp.framework/Versions/C/assimp'
make[1]: *** [CMakeFiles/Makefile2:208: code/CMakeFiles/assimp.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```

fix incorrect header path on framework build

---

code/AssetLib/FBX/FBXConverter.cpp

Hello,
I am working on the [Radium-Engine libraries](https://github.com/STORM-IRIT/Radium-Engine) and we are using AssImp as a file loader for more than 3 years now.
We recently ran into an issue with FBX files loading regarding the rotation interpolation for animations.
This comes from a recent cleaning update of AssImp, i.e. merge of PR #3086 where some code has been cleaned a bit too much in file `code/FBX/FBXConverter.cpp` at line 3317:
```
quat.x = -quat.x;
quat.y = -quat.y;
quat.z = -quat.z;
quat.w = -quat.w;
```
became:
```
quat.Conjugate();
```
thus missing the `w` component.
Thanks for considering this PR

Fix fbx rotation ;

---

code/PostProcessing/FindInvalidDataProcess.cpp

In debug builds, there's no issues, but in release, an invalid mesh that
is deleted in FindInvalidDataProcess will be double free'd when the
parent scene is destroyed.

Fix double free caused in FindInvalidDataProcess

---

code/AssetLib/BVH/BVHLoader.cpp

This bug has been present since after the 4.10 release.
It fixes the issue "play the bvh error" #2187
Almost all bvh files are affected, such as any of the CMU library.
The bug is caused by the introduction of channelMap in the BVHLoader.cpp - function void BVHLoader::CreateAnimation(aiScene *pScene).  The channelMap loses the rotation order present in the BVH file, and always applies the rotations in X,Y,Z order.

Fixed rotation order bug in BVH Loader

---

port/PyAssimp/README.md
port/PyAssimp/README.rst
port/PyAssimp/pyassimp/core.py

Thought it was more elegant to implement the load function with a contextmanager so that you can use it like "with open('/file.txt') as f: ..." and don't have to remember releasing it.
I also updated the examples in the README.md/README.rst.

Pyassimp - contextmanager for load function

---

code/AssetLib/FBX/FBXConverter.cpp

Current blendshape name loses channel information, only keeps the shape info.
This pr supports importing channel name in blendshape name.  
The aiAnimMesh mName data will respect names in fbx file, in the following format:
**channelName.shapeName**
Both information is included.

Fbx Import: support channel name in blendshape name

---

code/AssetLib/glTF2/glTF2AssetWriter.inl
code/AssetLib/glTF2/glTF2Exporter.cpp

This pr exports blendshape names for gltf2 format. It follows the gltf2 specification:
The blendshape names are mesh.extras.targetNames. 
E.g.
{
"meshes": [
{
"primitives": [
{
"attributes": {
"POSITION": 0
},
"targets": [
{
"POSITION": 1
},
{
"POSITION": 2
}
],
"extras": {
"targetNames": [
"Happy",
"Sad"
]
}
}
]
}
]
}
It is tested and blendshape names show up in 3rd party gltf viewer.

Gltf2 Export Target Names for Blendshapes

---

code/PostProcessing/LimitBoneWeightsProcess.cpp

assimp should not error out even when asset has invalid vertex id for bone weight.  Just ignoring it seems fine.
How to reproduce:
1. Download following glTF file [crash.glb](https://github.com/infosia/themachinery-issues/blob/master/0001/crash.glb)
2. Check if glTF file is valid (i.e. Open it with Windows 3D Viewer)
3. Load the glTF file in assimp
4. assimp errors out because of std::vector out of range.
Expected: assimp should not error out even when asset has invalid vertex id. Just ignoring it seems fine.

Check invalid vertex id for bone weight

---

code/AssetLib/MDL/HalfLife/HL1MDLLoader.cpp

Commit 7e5a0acc48efc54d7aa7900c36cd63db1fbeec9b made changes to HL1MDLLoader.cpp - Several variables have been renamed. A loop variable `i` was renamed to `faceIdx`, but one reference was left unchanged. This would break polygon winding order. Please see line 832 below.
https://github.com/assimp/assimp/blob/4ff5a06ef441e1df782906878d0dbf96251206d3/code/AssetLib/MDL/HalfLife/HL1MDLLoader.cpp#L831-L845

Fixed variable in loop - HL1MDLLoader.cpp

---

code/Common/Assimp.cpp
code/Common/SpatialSort.cpp
code/PostProcessing/ProcessHelper.h
include/assimp/cimport.h
test/unit/AssimpAPITest_aiMatrix4x4.cpp

Tested:
```sh
$ cmake -DASSIMP_DOUBLE_PRECISION=1 -DASSIMP_BUILD_MDL_IMPORTER=0 ..; make
```
The MDL importer is disabled due to the fact that there is some float-only code in MDL. This also means bin/assimp and bin/unit would not link successfully with the above build flags.

Fix build when ASSIMP_DOUBLE_PRECISION is on.

---

code/Common/SpatialSort.cpp

The constant 0x80000000 is specific to 32 bit types. Make the bit mask according to the size of types.

Improve ToBinary() for double precision.

---

code/AssetLib/FBX/FBXExporter.cpp

I've been writing an internal tool to modify FBX data, and the models I'm working on have non-standard axes settings and scale.
This modifies WriteGlobalSettings to re-output the available non-animation related metadata keys instead of a static default.
I didn't want to modify the FBXExporter header so I created some internal helper functions.

FBXExporter: Use scene metadata for global settings

---

code/Common/Importer.cpp

Fix invalid pointer for bone animation. 
How to reproduce:
1. Download following glTF file [RiggedFigure.out.glb](https://github.com/infosia/themachinery-issues/blob/master/0002/RiggedFigure.out.glb)
2. Check if glTF file is valid (i.e. Open it with Windows 3D Viewer)
3. Load the glTF file in assimp
4. assimp crashes because of bad pointer
Expected: assimp should not crash.

fix invalid pointer for bone animation

---

code/AssetLib/FBX/FBXExporter.cpp

A [comment](https://github.com/assimp/assimp/commit/6619ec82531e76ebb926d0ba9e90bc31623b765e) popped up yesterday regarding #3292. This adds a check if `mMetaData` is null.

FBXExport: Fix crash if scene->mMetaData is null

---

code/Common/Importer.cpp
code/Common/Version.cpp
include/assimp/version.h

- add single or double precision 
- add missing compilers.

closes https://github.com/assimp/assimp/issues/2992: detect double support 

---

code/AssetLib/NFF/NFFLoader.cpp
code/AssetLib/NFF/NFFLoader.h

The NFF importer parses values to floats, which aren't correctly written to doubles inside an `aiVector3D` when compiling with **ASSIMP_DOUBLE_PRECISION=ON**.
There is no 'normal' float to double conversion possible since the double (`f` in the line below, which lives in an `aiVector3D`) is incorrectly referenced as a float. Because of this incorrect reference, the parsed float is written to the double _as if the double was a float_, causing corrupt values.
https://github.com/assimp/assimp/blob/9fc00cbf74abcdae4fb5fdd8b64b5c58f8fce368/code/AssetLib/NFF/NFFLoader.cpp#L99
The issue is fixed by changing the parsed value from float to ai_real, which matches the ai_real inside the `aiVector3D`.

NFF importer double precision support

---

port/jassimp/jassimp/src/jassimp/AiTextureType.java

The newer PBR enums are missing, making it impossible to import many models.

Update Jassimp's AiTextureType.java

---

code/AssetLib/FBX/FBXImporter.cpp
code/AssetLib/Obj/ObjFileImporter.cpp

This fixes a crash when using a custom IOSystem/IOStream implementation. `IOSystem::Open` is supposed to return an `IOStream` implementation, but the memory management is ambiguous. In some places within the loader code, here for example:
```c++
IOStream * fileIO = pimpl->mIOHandler->Open( pFile );
uint32_t fileSize = 0;
if (fileIO)
{
fileSize = static_cast<uint32_t>(fileIO->FileSize());
pimpl->mIOHandler->Close( fileIO );
}
```
The `IOStream` pointer is acquired, closed, and never touched again. We get the pointer by calling `IOSystem::Open`, and then release it by calling `Close`. Later, in the .fbx and .obj loaders, I found this:
```c++
std::unique_ptr<IOStream> fileStream(pIOHandler->Open(file, mode));
```
When this goes out of scope, it calls `delete`. This works perfectly fine for a …

Fix Bad Ownership Acquisition

---

code/AssetLib/M3D/M3DWrapper.cpp

Happens when not building M3D exporter - unused argument warnings.

Fix for build break due to warnings-as-errors.

---

code/AssetLib/XGL/XGLLoader.cpp

Add const to avoid creating a temporary copy.
This should fix the cmake compilation error on XGLLoader.cpp shown in bug #3445
The fix is similar to commit bbe6f7f213b5e2ee689146df5c068dc1a55ea919

Fix for issue #3445

---

cmake/assimp-hunter-config.cmake.in

I tried to add the newest Assimp to Hunter but tests failed: https://github.com/cpp-pm/hunter/pull/288
I realize that is because I forgot to update the generated config with `pugixml`. That is fixed in this PR.

Hotfix for Hunter builds

---

code/AssetLib/FBX/FBXConverter.cpp

If you are loading in non-strict mode and the texture reference in the input FBX is malformed (for example, if the RelativeFilename is not a string) then the returned texture value is null. 
This change just prevents the value being dereferenced if the value is null.

Prevent crash with malformed texture reference

---

code/AssetLib/glTF2/glTF2Asset.h
code/AssetLib/glTF2/glTF2Asset.inl
code/AssetLib/glTF2/glTF2Importer.cpp
include/assimp/scene.h

Primarily to provide access to the "name" member of glTF2 scenes.

Added mName to aiScene.

---

code/AssetLib/FBX/FBXParser.cpp

This Pull-Request solves 2 issues w.r.t. FBXParser:
1. Handle potential integer overflow when calculating the amount of data to be read from buffer
- i.e. count = INT_MAX
2. Raises ParseError in the case whereby trying to read more data than available in buffer
- this issue can arise from corrupted FBX or maliciously modified files

FBXParser.cpp - handle buffer over-read correctly

---

code/AssetLib/glTF2/glTF2Importer.cpp
code/Common/CreateAnimMesh.cpp
include/assimp/CreateAnimMesh.h

For glTF2 morph animation,
assimp always makes morph targets' attributes based on the original mesh.
This patch prevents to make redundant morph targets.

Prevent to generate redundant morph targets for glTF2

---

code/AssetLib/FBX/FBXConverter.cpp
code/AssetLib/FBX/FBXConverter.h
code/AssetLib/FBX/FBXDocument.h

In #2741, the keys of the textures_converted map were switched to Video objects rather than pointers. I don't think that's necessary:
* The video object are owned by the document
* In all the code I've looked at, the video objects are always const, so the keys always continue to match the objects they were copied from. 
All unit tests, including the one provided with that PR, still pass when pointers are used. (And the tests we use internally also pass.)
I thought I needed this PR for another change, but that is no longer true. However, I'll leave it here as an optional simplification.

Simplification: textures_converted keys can just be pointers

---

code/Common/ScenePreprocessor.cpp

Potential memory leak when allocating dummy Position, Rotation, Scaling tracks for the animation channel.
Ensures keys arrays are free'd before allocating the dummy arrays.

Sceneprecessor - potential memory leak

---

code/AssetLib/FBX/FBXConverter.cpp
code/AssetLib/FBX/FBXConverter.h

An exception in the FBXConvertor can lead to a crash when deleting the node chains. 
The crash occurs because assimp tries to destroy a vector of objects where there is already an ownership relationship between them, leading to double deletes.
I've adjusted the code so the node chains carry an object which may or may not own its node. The diff looks messy, but the changes are pretty minor.

Fbx exception safety

---

code/PostProcessing/SplitByBoneCountProcess.cpp

Proposed fix for https://github.com/assimp/assimp/issues/3489

Fix for 3489 | Preserve morph targets when splitting by bone count

---

code/AssetLib/FBX/FBXConverter.cpp
code/PostProcessing/SortByPTypeProcess.cpp

FBX animations were recorded by framenumber, not by time.
This patch will change it as a base of milliseconds.

FBXConverter : Fix timescales of FBX animations

---

code/AssetLib/glTF2/glTF2Exporter.cpp

In the GLTF 2 exporter, when we build the animation samplers, we check that the animation channel has at least one key, otherwise no need to add it.
The problem is that in this case, we don't initialize the sampler but we add them anyway which causes a crash at the time of writing.
The solution is simply not to add the animation channel in this case.

Fixed a crash of the Gltf 2 exporter in the case of an animation without scale animation key.

---

code/AssetLib/glTF/glTFAsset.inl
code/AssetLib/glTF2/glTF2Asset.inl

This is my first time exploring the source code and contributing. I've been looking around for hours trying to fix this and I came across these two commits which could have interfered:
- https://github.com/assimp/assimp/commit/d2ed36756c7b844268367fdcde27e0f1846102e2
- https://github.com/assimp/assimp/commit/0357333c8185ef7a4446502cebc9ef239564c67a
I eventually figured out the problem was with:
`mCurrentAssetDir = glTFCommon::getCurrentAssetDir(pFile);`
When trying to load a .gltf with a custom IO handler (for my purpose, loading assets through http and custom protocols), it will eventually request the .bin file. If loaded from memory, it will use `MemoryIOWrapper` and run function `MemoryIOWrapper::Open`
However, before my commit, it would send  `$$$___magic___$$$scene.bin` as `const …

Fix glTF from memory loading .bin with a custom IOHandler

---

contrib/Open3DGC/o3dgcArithmeticCodec.cpp
contrib/openddlparser/code/OpenDDLParser.cpp

according to the c ++ standard, operator new cannot return null, but will throw a std :: bad_alloc () exception.
therefore AC_Error will not be called.
The best solution, of course, is to use an exception handler, but it seems to me that the exception should be handled above.
therefore, I suggest the simplest thing - to remove these checks.

fix of an unattainable condition.

---

code/Common/ZipArchiveIOSystem.cpp

This is a partial revert of 54be7ac582599df9f32503ed435b65911a6ebc8b (2020-12-24 Update unzip contrib)
Fixes the following build failure seen when compiling under Linux x86_64 using GCC 10.2.0:
/usr/src/git/assimp/code/Common/ZipArchiveIOSystem.cpp: In static member function 'static zlib_filefunc_def Assimp::IOSystem2Unzip::get(Assimp::IOSystem*)':
/usr/src/git/assimp/code/Common/ZipArchiveIOSystem.cpp:155:28: error: 'error_file_func' was not declared in this scope; did you mean 'testerror_file_func'?
155 |     mapping.zerror_file = (error_file_func)testerror;
|                            ^~~~~~~~~~~~~~~
|                            testerror_file_func
make[2]: *** [code/CMakeFiles/assimp.dir/build.make:186: code/CMakeFiles/assimp.dir/Common/ZipArchiveIOSystem.cpp.o] 
Error 1

Fix build failure on Linux

---

.gitignore

VS2019 has improved native support for cmake projects, opened via "Open Folder".
This creates some extra files in-tree:
- "CMakeSettings.json" file with your VS settings (toolchain, enabled configurations etc)
- ".vs/" folder for Visual Studio's Intellisense database
- "out/" folder for the build artifacts.
This PR adds these to gitignore to avoid accidentally committing any of these

Update gitignore for default VS2019 behaviour

---

code/AssetLib/M3D/m3d.h

The array `tc16[3]` in ` code/AssetLib/M3D/m3d.h:1645` is not initialized and may cause `maybe-uninitialized` warnings when building release version of the library.

Eliminate maybe-uninitialized warnings which are treated as errors

---

code/AssetLib/Obj/ObjFileMtlImporter.cpp

- The alpha value in materials using the Tr format must be inverted
- closes https://github.com/assimp/assimp/issues/3645

Fix apha value

---

code/AssetLib/3MF/D3MFImporter.cpp

Silence  uninitialized variable warning in 3MF importer
```
code/AssetLib/3MF/D3MFImporter.cpp:435:58: error: ‘pid’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
435 |                     auto it = mResourcesDictionnary.find(pid);
```
This is a false positive (`pid` is only used if `getNodeAttribute` set it and returned true) but the compiler can't see that.

Silence uninitialized variable warning in 3MF importer

---

code/PostProcessing/ArmaturePopulate.cpp

- Remove assertion test for empty nodestacks when no meshes are in the node. Just return from the function.
- closes https://github.com/assimp/assimp/issues/3664

Remove buggy assert

---

code/AssetLib/glTF2/glTF2Importer.cpp

This change adds checks to ensure that the normal count and tangent count match the vertex count. If they don't match we ignore the data and emit a warning. This prevents problems further down the line, as all code assumes these arrays are the same size.

Check that normal count and tangent count match vertex count.

---

CMakeLists.txt

- DRACO is disabled as the default
- Use ASSIMP_BUILD_DRACO=ON to reenable it
- Workaround for https://github.com/assimp/assimp/issues/3663

Workaround for VS2019

---

code/PostProcessing/ComputeUVMappingProcess.cpp

Small is seen as a type with some options so this fixes the errors starting with:
code\PostProcessing\ComputeUVMappingProcess.cpp(125): error C2632: 'int' followed by 'char' is illegal

Compile fix for MSVC 2019

---

code/AssetLib/glTF2/glTF2Asset.inl

The destructor of LazyDict uses `delete` but `delete` was not used for objects removed by LazyDict::Remove.

Fix a memory leak in glTF2.

---

code/AssetLib/3DS/3DSExporter.cpp

and therefore omitting the transform aggregation in the CHUNK_VERTLIST. A similar bug has been posted already (see #3450) but unsure if the @copycd meant the same issue.
Found while comparing the 3DS exporter implementations of Blender see [export_3ds.py](https://github.com/blender/blender-addons-contrib/blob/f948f658ba33eb670a65e0bba058d43138abea7e/io_scene_3ds/export_3ds.py#L1034) to Assimp.

Fixing CHUNK_TRMATRIX translation sub chunk

---

code/AssetLib/3DS/3DSLoader.cpp

Fixing wrong transformation matrix import for 3DS in alignment with 3DS exporter.

Fixing 3DS import for CHUNK_TRMATRIX translation vector.

---

code/AssetLib/FBX/FBXExporter.cpp

Kitbashed blendshape exports into the exporter, works well on the example glbs I have here (multi material, 30-40 blendshapes per mesh). Not 100% sure on the normals, however, but FBX normals are a bit iffy in general, anyway.

Added Blendshape Support to FBX Export

---

CMakeLists.txt

Hello.
This patch fixes zlibstatic being missing from export set when zlib is used as a static lib with assimp. Otherwise I get the error like this:
```
CMake Error: install(EXPORT "assimpTargets" ...) includes target "assimp" which requires target "zlibstatic" that is not in the export set.
```

Add zlibstatic to the list of exported targets

---

include/assimp/MathFunctions.h
test/unit/AssimpAPITest_aiMatrix4x4.cpp
test/unit/AssimpAPITest_aiQuaternion.cpp
test/unit/MathTest.cpp

Fixes #3310
This change renames the function PI to aiPi to avoid having it clash with the common macro convention of ALL_UPPERCASE_LETTERS. Because the function PI was included in a public header (that then got included everywhere), it would occasionally get stomped on if included in a translation unit that _also_ defined the macro PI (a fairly common definition I'd wager).
I chose `aiPi` over `ai_pi` as it seemed to better match some existing types I saw? If we want it to be `ai_pi` just let me know. :)

Renaming PI to aiPi.

---

Readme.md

- Will now use the official repo at https://bitbucket.org/Starnick/assimpnet/src/master/
- The githob mirror is now archived and no longer supported

Update repo for assimp-net

---

code/AssetLib/MDC/MDCLoader.cpp

placement new was clearing input buffer by constructor, which was nothing to do with adequate parsing
changes are not analyzed in depth, but at least test model and models of Wolf:ET are loading and not crashing

Fix MDC loader

---

code/AssetLib/FBX/FBXCompileConfig.h
code/AssetLib/Step/STEPFile.h
code/AssetLib/Step/StepExporter.cpp
code/AssetLib/glTF/glTFAsset.h
code/AssetLib/glTF/glTFCommon.h
code/AssetLib/glTF2/glTF2Asset.h

Non-TR1 version would be the default now, across all compilers. For MSVC the behavior stays the same.
Note that due to the typo `__GNUC___` above, GCC/Clang is not using unordered containers as of now.

Flip the check on _MSC_VER for using TR1 containers.

---

code/AssetLib/3MF/D3MFOpcPackage.cpp
code/AssetLib/Ogre/OgreBinarySerializer.cpp

Ogre and 3MF imports threw `DeadlyExportError`s under some circumstances. Bad for people who assumed that they only needed to catch `DeadlyImportError`s. Changed them to `DeadlyImportError`s.

fixed export exceptions on import

---

code/AssetLib/Blender/BlenderLoader.cpp

Addresses #3797.
Re-submitting this as a quick fix to the immediate issue while I think about the website field (#3799).

Remove newline from name of Blender importer.

---

code/Common/DefaultIOStream.cpp

- This is a valid option so crash shall not happen

Fix crash when reading 0 bytes

---

code/AssetLib/glTF2/glTF2Asset.inl
code/AssetLib/glTF2/glTF2Importer.cpp
code/PostProcessing/SortByPTypeProcess.cpp

These address a few issues where Assimp asserts or crashes when importing invalid files:
* Throw instead of assert on invalid file input
* Check JSON object type before accessing members
* Ensure samplers input and output references are set before accessing them

Importer improvements

---

port/PyAssimp/pyassimp/structs.py

Found this in the ctypes documentation:
"For a general character pointer that may also point to binary data,
POINTER(c_char) must be used." c_char_p is for a zero-terminated string.
Reference: https://docs.python.org/3/library/ctypes.html#ctypes.c_char_p
Applying this change to the 4.1.4 release fixes #2339 for me in Ubuntu.
The issue isn't consistent since I can't reproduce it with master, but this
still appears to be a correct change since it does fix the 4.1.4 released code for me.
To confirm mPrivate points to binary data and not a string, it is set like this [here](https://github.com/assimp/assimp/blob/3fead344ad06446ce2dca9ea528fcca7b6948e35/code/Common/Version.cpp#L139):
`mPrivate(new Assimp::ScenePrivateData())`

Use POINTER(char) for binary data. For pyassimp issue #2339: Can't load OBJ

---

code/AssetLib/3DS/3DSLoader.cpp
code/AssetLib/AMF/AMFImporter.cpp
code/AssetLib/Assbin/AssbinLoader.cpp
code/AssetLib/COB/COBLoader.cpp
code/AssetLib/Irr/IRRLoader.cpp
code/AssetLib/Irr/IRRMeshLoader.cpp
code/AssetLib/MS3D/MS3DLoader.cpp
code/AssetLib/NDO/NDOLoader.cpp
code/AssetLib/Q3D/Q3DLoader.cpp
code/AssetLib/SIB/SIBImporter.cpp
code/AssetLib/XGL/XGLLoader.cpp

Addresses #3888.
Affects importers: amf, 3ds, cob, ms3d, nendo, quick3d, sib, assbin, irr, irrmesh, xgl.
Does *not* address #3849 (CanRead). That is addressed by #3850.
This PR does not have any dependencies.

Fix importer ReadFile issues on file open error or when opening empty files

---

code/AssetLib/AMF/AMFImporter.cpp

This change was part of PR #3890, but was later lost in a merge. I kind of suspected this would happen, because of a minor conflict between two of my PRs. 
This PR reapplies the fix. Original commit was https://github.com/assimp/assimp/pull/3890/commits/785cca1bb43f9e6047cb566a910fcd0e3d49951f
---
Fix double free of mXmlParser (deleted but not reset in ParseFile, then deleted again in ~AMFImporter).

Reapply [amf] Fix crash when file could not be parsed.

---

code/AssetLib/Blender/BlenderDNA.cpp
code/AssetLib/Blender/BlenderDNA.h

This is one possible solution; feel free to reject. Discussion at #3886.
Developers who want to enable it can either:
- *Temporarily* set ASSIMP_BUILD_BLENDER_DEBUG_DNA=1 in BlenderDNA.h, or
- *Temporarily* define ASSIMP_BUILD_BLENDER_DEBUG_DNA=1 on the build command line.
Addresses #3886.

[blender] Disable creation of "dna.txt"

---

port/PyAssimp/pyassimp/helper.py

The helper function which locates assimp for the python port fails on arm64 simply because it's only looking in the x86_64 directory.  This simple add makes pyassimp properly work on aarch64.

Add support for arm 64 bit

---

code/Common/DefaultLogger.cpp

Logs a notification instead of silently dropping long log messages, which can complicate debugging.
This way, if you don't see a message you expect to see, you'll immediately know why.
The *correct* approach would be to eliminate length filtering here entirely and use `snprintf` or whatever appropriately (also there's a tiny -- probably negligible -- performance hit here in calling `strlen` regardless of whether or not the verbosity level matches). Failing that, the second best option is to copy and truncate messages here. However, for now, this should be OK.

[Logger] Log a notification instead of silently dropping long log messages.

---

code/AssetLib/Ply/PlyParser.cpp

Hi,
This PR tries to fix #3711
The problem is, that the pointer for the current symbol parsing points is on a newline ('\n') when the header was written with windows line endings (' \r\n'). Instead, if should point to the first byte of the binary data after the header.
With this PR, the header parser first checks if the end token of a PLY header is a windows new line and, if not, if it has a normal new line (which is in assimp defined as '\n' or '\r'). 
We cannot check if the current pointer is a new line and skip, as the binary representation can be, by accident, be a new line while the header was not decoded with ' \r\n'. Therefore the fix should work on the following possibilities for the header ending:
- windows new-line: "header_end\r\nB" 
- -> after header reading, the current …

Fix non skipped CR in header parsing for binary PLY

---

CMakeLists.txt

Currently, the variables that control the library, runtime, and archive output directories are normal variables.
Changing them to cache variables would allow a parent project to set the output directories if desired.
I think this would be nicer than having to copy the files with a post-build step.

Change the Assimp output directory vars to cached vars

---

code/AssetLib/FBX/FBXExporter.cpp

When I export a FBX file from the following code, the exported cube is not visible in Visual Studio 2019.
1. In FBXExporter::WriteDefinitions(), count_nodes() - 1 is 0 even if the root node contains meshes. Model definitions are not written to the exported file.
2. In FBXExporter::WriteModelNodes(), model objects should have "Shading: T" or "Culling: "CullingOff"" line to show meshes
```
void FBXExportTest()
{
// modified from  https://github.com/assimp/assimp/issues/203
aiScene scene;
scene.mRootNode = new aiNode();
scene.mMaterials = new aiMaterial*[ 1 ];
scene.mMaterials[ 0 ] = nullptr;
scene.mNumMaterials = 1;
scene.mMaterials[ 0 ] = new aiMaterial();
scene.mMeshes = new aiMesh*[ 1 ];
scene.mMeshes[ 0 ] = nullptr;
scene.mNumMeshes = 1;
scene.mMeshes[ 0 ] = new aiMesh();
scene.mMeshes[ …
```

Fix fbx exporter bug if root node contains meshes.

---

include/assimp/material.h

- The aiGetMaterialFloat() and aiGetMaterialInteger() C preprocessor definitions were broken because:
- They had a space before the opening parenthesis
- Using material key definitions expanding 1 to argument into 3 breaks the invocation of macros expecting 5 parameters

include/material.h: Fixed broken C support

---

code/AssetLib/FBX/FBXConverter.cpp
code/AssetLib/FBX/FBXDocument.h
code/AssetLib/FBX/FBXExporter.cpp
code/AssetLib/FBX/FBXMaterial.cpp

1. FBX import is unable to read the texture UV rotation angle.
2. FBX export is unable to write the texture UV rotation angle.

FBX module unable to read uv rotation angle and write all the uv transformation data.

---

code/AssetLib/glTF2/glTF2Exporter.cpp
code/AssetLib/glTF2/glTF2Importer.cpp

- Exporter: Writing opacity to pbrMetallicRoughness.baseColorFactor[3] even when alphaMode is set
- Importer: Setting AI_MATKEY_OPACITY from pbrMetallicRoughness.baseColorFactor[3]

glTF2: Improved support for AI_MATKEY_OPACITY

---

code/AssetLib/glTF2/glTF2Asset.h
code/AssetLib/glTF2/glTF2Asset.inl
code/AssetLib/glTF2/glTF2Importer.cpp

glTF2 allows nodes (as well as other objects) to have custom properties assigned to them, under the "extras" sub-object. These are used, for example, when exporting a Blender scene that uses its Custom Properties. This PR parses that data for nodes and exposes it under the assimp metadata. This is built on top of the work in #3298 with a few minor tweaks, and finishes the rest of the requested improvements from #3025.

Added support for custom properties ("extras") in glTF2 importer

---

.gitignore

Hi this folder is generated by build was causing me some trouble when working with git (not sure if its created by unreal engine build tools , cmake or vs ?) .

Update Gitignore exclude x64 folder generated by build

---

code/AssetLib/Ply/PlyParser.cpp

Correction from issue #3711
The deduction was correct but the correction didn't work on the solidworks.ply test file from the issue.
This change force the skip the /n char in the beginning of the buffer when it's present.

Manage /R/N lines ends correctly on binary files, tested with solidworks PLY export

---

code/AssetLib/M3D/M3DWrapper.h

- closes https://github.com/assimp/assimp/issues/3974
- Check for nullptr before dereferencing name in m3d-data-instance.

Fix fuzzer issue in m3d-importer

---

code/AssetLib/glTF2/glTF2Importer.cpp

f6b4370f6ac1bf2db0ef9edeb0ff1ce8c7e61aab and 7c822f23bd075d3621d2e2f33188e1659f657b31 introduced raw loops on data types with heavy nesting; range-based for suits better here

more range-based for

---

code/AssetLib/FBX/FBXConverter.cpp

Fix issue of incorrect reading of PBR properties such as base and emissive color in FBX. In FBXConverter.cpp method GetColorPropertyFromMaterial adds unnecessary(for PBR properties) "Color" string to property name.

Fix: incorrect reading of PBR properties in FBX

---

code/AssetLib/Assbin/AssbinFileWriter.cpp

Mingw release build is failed, because it seems `t` as an unused variable.

Mingw build fix

---

code/AssetLib/M3D/M3DImporter.cpp
test/unit/utM3DImportExport.cpp

The same default material pointer was assigned to all the materials in the scene, so poor destructor tried to free the same pointer multiple times.

Fix M3D import crash and memory leak.

---

code/AssetLib/XGL/XGLLoader.cpp
code/AssetLib/XGL/XGLLoader.h

Fix the -Werror=unused-but-set-parameter warning by removing the skipFirst variable.
From what I could see in blame this has been unused for a while.

XGLImporter: Compiler warning fix

---

include/assimp/scene.h

changed comment for the ending brace in scene.h to the same comment as used in mesh.h (changing explanation from 'end of namespace' to 'end of extern c section')

fixed incorrect/misleading comment at end of scene.h

---

include/assimp/Importer.hpp

When compiling on Linux, it was spitting out a error at include/assimp/Importer.hpp. Idk why "_#include <exception>_" was commented out, but I undid that comment.
I'm new to opensource btw, I don't really know what I'm doing.

including <exception>

---

code/AssetLib/Obj/ObjFileMtlImporter.cpp

* Return 0.0f for empty buffer
* closes https://github.com/assimp/assimp/issues/3442

Fix possible nullptr dereferencing in material parsing

---

code/AssetLib/Obj/ObjFileMtlImporter.cpp

- get compatible to tinyobjloader and other importers
- closes https://github.com/assimp/assimp/issues/3726

Add support for normal maps, the classic way

---

code/PostProcessing/EmbedTexturesProcess.cpp

`aiString` length was not updated when the texture path was replaced with the embedded path (i.e. `*0`) after performing the EmbedTextures postprocess task. 
This created all sort of problems when performing string manipulation using the `aiString::length` field instead of interpreting `aiString::data` as c-string (think of applications using UTF8 strings). 
I also wrote a small unit test for this change, but decided against pushing it because I don't know in which file to put it.
Let me know if I should add it to the pr.

Fix aiString length not updated in the EmbedTextures postprocess task

---

code/AssetLib/STEPParser/STEPFileReader.cpp

I ran clang-tidy on the most recent RC, and found a performance bug. There was a const qualifier on a return value which prevented the compiler from doing an automatic move of the shared_ptr return value.

Remove optimization fence preventing automatic move

---

code/AssetLib/Collada/ColladaParser.cpp
include/assimp/XmlParser.h
test/unit/utColladaExport.cpp

Some less-common Collada properties were misconverted when changing from IrrXML to pugixml.
These are values, not attributes.
Fixes #4179

Collada: Read value, not attribute

---

code/AssetLib/glTF2/glTF2Asset.inl

This turned up during fuzz testing. Corrupted data would make assimp write to random memory locations, leading to subsequent crashes.

Prevent out-of-range memory writes by sparse accessors

---

code/AssetLib/FBX/FBXConverter.cpp
code/AssetLib/FBX/FBXConverter.h

FBX uses euler rotation but assimp library's base type is
quaternion. When assimp convert FBX some animation information
can be lost.
This patch interpolates euler-angle rotations and insert
additional keyframes for the FBX format.
#4215

Interpolate euler rotations for quaternion animations

---

code/AssetLib/X3D/X3DImporter.cpp
code/AssetLib/X3D/X3DImporter_Group.cpp
code/AssetLib/X3D/X3DImporter_Macro.hpp

using the pre-existing and well-tested GetExtension() (which happens to also normalize the extension), rather than attempting a new buggy implementation of the same thing...
Closes: https://github.com/assimp/assimp/issues/4177

Fix file-extension check for X3D-files

---

code/AssetLib/FBX/FBXConverter.cpp

The previous patch was made by misunderstanding about mTime.
It is not real time value, but time ticks.
This reverts commit b8bf1eac041f0bbb406019a28f310509dad51b86.

Revert "FBXConverter : Fix timescales of FBX animations"

---

code/Common/SceneCombiner.cpp
include/assimp/SceneCombiner.h
test/unit/Common/uiScene.cpp

Copy `mTextureCoordsNames` when copying a mesh.

Bug: Export crashes when any of the meshes contains texture coordinate names #4243

---

assimpTargets-release.cmake.in

This problem was discovered by the vsgXchange project (see https://github.com/vsg-dev/vsgXchange/issues/65#issuecomment-984677582)

cmake: fix incorrect usage of 'lib' sub dir in assimpTargets-release.cmake.in on x64

---

code/Common/BaseImporter.cpp

- During UTF32 LE with BOM make sure that the byteswap operation will have enough space when iterating through the text buffer, which shall get encoded.
- closes https://github.com/assimp/assimp/issues/4230

Make sure no overflow can happen

---

code/AssetLib/LWS/LWSLoader.cpp

- Fix invalid access to string pointer when string token is empty
- closes https://github.com/assimp/assimp/issues/4222

LWS-Import: Avoid access to empty string token

---

code/AssetLib/MDL/MDLMaterialLoader.cpp

- When an embedded texture is empty, skip it instead of trying to copy it. This must fail.
- closes https://github.com/assimp/assimp/issues/4238
- Found from the Google fuzzer.

MDL: Do not try to copy empty embedded texture

---

include/assimp/mesh.h

- Add link to enum which describes the used morphing method in an instance of an aiMesh for the case, that this instance will be used as an AnimMesh-instance.
- closes https://github.com/assimp/assimp/issues/4320

Add link to used enum for a better understandability

---

code/AssetLib/glTF2/glTF2Exporter.cpp

I'm not entirely sure what's going on here but this seems to fix a crash I encountered with some models

Fix bone fitted check in gltf2 exporter

---

code/AssetLib/ASE/ASEParser.cpp

- Fuzzer error found when material access get's an out-of-bound access.
- Break parsing when material index gets out of range.
- closes https://github.com/assimp/assimp/issues/4232

ASE: Fix material parsing

---

include/assimp/ByteSwapper.h

the `AI_SWAP4` macros and friends assume that they are called in a context that resolves the `Assimp` namespace.
rather than adding an explicit namespace to the macro-invocation whereever it is used (as suggested in #4360), this PR modifies the macros themselves so they are expanded with the full namespace.
Closes: https://github.com/assimp/assimp/issues/4358

use fully qualified namespace in byteswap macros

---

code/Common/Compression.h

gcc11 seems to have changed some internal includes:
```
[ 10%] Building CXX object externals/assimp/assimp/code/CMakeFiles/assimp.dir/Common/Compression.cpp.o
In file included from /home/runner/work/cage/cage/externals/assimp/assimp/code/Common/Compression.cpp:42:
/home/runner/work/cage/cage/externals/assimp/assimp/code/Common/Compression.h:73:5: error: ‘size_t’ does not name a type
73 |     size_t decompress(unsigned char *data, size_t in, std::vector<unsigned char> &uncompressed);
|     ^~~~~~
/home/runner/work/cage/cage/externals/assimp/assimp/code/Common/Compression.h:45:1: note: ‘size_t’ is defined in header ‘<cstddef>’; did you forget to ‘#include <cstddef>’?
44 | #include <vector>
+++ |+#include <cstddef>
45 | 
```

fix missing include for size_t

---

CMakeLists.txt

- Reenable fix to ensure that stat works correctly on 32-bit linuxes again
- stat will return 32-bit inodes when checking a file. So when this call will be used on a 64-bit linux this will cause errors like:
Error writing to foo: Value too large for defined data type
File I/O error: foo
- closes https://github.com/assimp/assimp/issues/4390

Fix stat for 32-biut linuxes

---

BUILDBINARIES_EXAMPLE.bat

udpate build script to fit "Visual Studio 16 2019" Generator

udpate build script to fit "Visual Studio 16 2019" Generator

---

code/AssetLib/Obj/ObjFileData.h
code/AssetLib/Obj/ObjFileImporter.cpp
code/AssetLib/Obj/ObjFileMtlImporter.cpp
include/assimp/ObjMaterial.h

Hi,
I've added Obj model support for the bump map -bm #### multiplier. I've attempted to follow the gltf use of "$tex.scale" as a guide for making it available.
An example Obj line with the parameter:
`map_Bump -bm 0.398056 textures\main_normal.png`
These changes will load the 0.398056 factor into a material property for either Normal or Height maps (ie: Obj map_Bump). The property is only set if the scalar is not 1.0.
The property can be retrieved like so:
`aiMaterial* mtl = scene->mMaterials[m];`
`ai_real bm = 1.0;`
`aiReturn rc = aiReturn_SUCCESS;`
`if( mtl->GetTexture(aiTextureType_NORMALS, texIndex, &path) == AI_SUCCESS) { `
`rc = aiGetMaterialFloat(mtl, AI_MATKEY_OBJ_BUMPMULT_NORMALS(0), &bm);`
`}`
`else if(mtl->GetTexture(aiTextureType_HEIGHT, texIndex, &path) == AI_SUCCESS) {`
` …

Added support for "map_Bump -bm"

---

code/AssetLib/Obj/ObjFileImporter.cpp
include/assimp/ObjMaterial.h

This commit exposes the original Obj model  `illum` value (illumination_model) as a material property. 
The `illum` value is defined in a .mtl material file like so:
`illum 3`
Background:
`ObjFileImporter::createMaterials` in `ObjFileImporter.cpp` partially interprets the illum value as an `aiShadingMode` enum and stores it in the `AI_MATKEY_SHADING_MODEL` material property. Illumination model values 3 thru 10 are lost in the interpretation. Exposing the original illum value allows user interpretation of the intended model.
Example accessor usage:
`    aiScene* scene = ...`
`    int illum = 1;`
`    aiMaterial* mtl = scene->mMaterials[m];`
`    aiGetMaterialInteger(mtl, AI_MATKEY_OBJ_ILLUM, &illum);`

Expose the original OBJ "illum" value

---

code/AssetLib/FBX/FBXConverter.cpp

This problem may cause memory explosion.
In FBXConvert.cpp::ConvertMeshMultiMaterial, the number of mesh vertices after splitting has been preprocessed in advance, but the number of original mesh vertices was incorrectly used when allocating memory later.

Optimize the problem of excessive memory allocation in FBX import

---

code/Common/ZipArchiveIOSystem.cpp

If 'disk_filename' does not contain a dot (.) then 'i' would overflow.
Making 'i' an int makes sure the for loop works as intended.

Fix 'i >= 0' always true bug

---

CMakeLists.txt

Allow user to choose C runtime library version, on Windows
This PR adds an option to cmake, `USE_STATIC_CRT`.
The default is OFF, which has no changes to the current build.

Add USE_STATIC_CRT option

---

code/AssetLib/MDL/MDLLoader.cpp

- Check if we have any texture coordinates before calculating them
- closes https://github.com/assimp/assimp/issues/4445

Fix nullptr dereferencing

---

code/AssetLib/MDL/MDLMaterialLoader.cpp

- Use correct len to copy filename.
- Closes https://github.com/assimp/assimp/issues/4447

Fix stack-overflow in MDLLoader

---

code/AssetLib/glTF2/glTF2Asset.inl

Fixing mistakes in attribute names for GLTF. This causes attribute index to not be parsed out correctly (e.g. JOINTS_1) and fails the scene load. See https://github.com/assimp/assimp/blob/a916a0eda5dfa5c9d1a6f0c4657af6d40886f0a8/code/AssetLib/glTF2/glTF2Asset.inl#L1380 for where the parsing breaks.

GLTF2 attribute name/parse bug fix

---

code/AssetLib/FBX/FBXConverter.cpp

Matches the logic used by Blender's own FBX exporter / importer.

Detect Roughness factor exported by Blender

---

code/AssetLib/FBX/FBXConverter.cpp
code/AssetLib/FBX/FBXConverter.h

For some FBX files, there is an incorrect calculation of _mOffsetMatrix_ of bones. According to those 2 FBX files  "**box_bone_animation.FBX**" and  "**box_bone_animation_moved.FBX**"(you can find them in [primitives.zip](https://github.com/assimp/assimp/files/8506104/primitives.zip) archive), they both have the same box with skeleton animation, but in the file "**box_bone_animation_moved.FBX**"  box is moved by 50 by the x-axis. After converting them into the Assimp Scene, in the first example and the second example Assimp Scenes have different _mOffsetMatrix_ of their bones, but they should have the same.
I have found that there is another parameter "_Transform_" in "_SubDeformer::Cluster_" in FBX file that contains the exact matrix that corresponds to _mOffsetMatrix_ that should be. …

FbxConverter: update bone mOffsetMatrix 

---

code/CMakeLists.txt

This is a supplement for my previous PR #4481. I couldn't figure out how to set the library names correctly. This fixes that.

Fixed library names for MinGW/MSYS2

---

code/AssetLib/3MF/XmlSerializer.cpp
code/AssetLib/Blender/BlenderLoader.cpp
code/AssetLib/Blender/BlenderLoader.h
code/AssetLib/IFC/IFCOpenings.cpp
code/AssetLib/X3D/X3DImporter.cpp

* Apply fixes from clang-tidy (mostly just ensuring that values that should use const ref end up doing so).

Clang-Tidy performance fixes (make values const-ref where needed).

---

contrib/unzip/crypt.c
contrib/unzip/ioapi.c
contrib/unzip/unzip.c

Using pragma warning caused builds using MinGW bundled with the latest version of CLion (2022.1.2). Removing it seems to build correctly and fix the problem.

Pragma warnings cause build fail with MinGW

---

code/AssetLib/glTF2/glTF2Exporter.cpp

The only thing preventing GCC v12 compatibility is the new array-compare warning.

Add support for GCC v12

---

code/res/assimp.rc

- mingw is using a different include to win32-specific resource files.
- closes https://github.com/assimp/assimp/issues/4586

Use mingw.include

---

code/AssetLib/Collada/ColladaHelper.h
test/models/Collada/box_nested_animation.dae
test/unit/utColladaImportExport.cpp

Hi!
This PR fixes an issue with the name of the animation being empty when parsing nested collada animations. I also added a unit test that fails without the change and succeeds with.
Specifically, the tested collada file has the following animation library:
```
<library_animations>
<animation id="action_container-Armature" name="Armature">
<animation id="Armature_ArmatureAction_transform" name="Armature">
[...]
```
Without the change, the animation name is empty, with the change it it set to `Armature`.

Fix nested animation name being lost in Collada

---

Build.md

Fix typo in installation instructions for ubuntu.

---

code/Common/ZipArchiveIOSystem.cpp

From v5.1.6 onwards Assimp fails to build on my Ubuntu 21.10 system's default minizip install.  Looking at Issues tracker, #4334, others have the same build problem on a range of Linux distos.   I've added a #ifdef check around the problematic line to keep things compiling.
Unfortunately this #ifdef approach looks like it'll disable the functionality that caused this break in the build - I don't know how intrusive this would be as I'm not familiar with the wider code, there may well be more changes that would need disabling or handling to more elegantly handle these features that can't be implemented against minizip.
I provide this build fix so that others who are hitting up against the same problem can at least get Assimp built.

Build fix for compiling against minizip.

---

code/AssetLib/Obj/ObjFileParser.cpp

Fixes Heap-buffer-overflow in Assimp::ObjFileParser::getFace revealed by fuzzing:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=40589
The root cause is that `const int iVal(::atoi(&(*m_DataIt)));` reads beyond of `m_DataItEnd` if the string is not null terminated.

Fixes Heap-buffer-overflow in Assimp::ObjFileParser::getFace

---

code/AssetLib/DXF/DXFLoader.cpp

Fixes Heap-use-after-free in Assimp::DXFImporter::ExpandBlockReferences revealed by fuzzing:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=42899
The root cause is that `bl_src.lines` and `bl.lines` in `DXFImporter::ExpandBlockReferences` may be the same vector. Iterator may become invalid when new objects are pushed into the same vector.

Fixes Heap-use-after-free in Assimp::DXFImporter::ExpandBlockReferences

---

code/AssetLib/LWS/LWSLoader.cpp

Fixes Heap-buffer-overflow in SuperFastHash revealed by fuzzing:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44964
The root cause is that a call to `ai_snprintf` in `LWSImporter::SetupNodeName` returns the number of characters that would have been written if the buffer had been sufficiently large.
It leads to creation of `aiString` object with incorrect length that causes out of bounds buffer read in `SuperFastHash` later.

Fixes Heap-buffer-overflow in SuperFastHash

---

code/AssetLib/Obj/ObjFileData.h
code/AssetLib/Obj/ObjFileImporter.cpp
code/AssetLib/Obj/ObjFileMtlImporter.cpp
code/AssetLib/Obj/ObjFileParser.cpp
code/AssetLib/Obj/ObjFileParser.h
code/AssetLib/Obj/ObjTools.h

- Avoid creation of std::string to parse integer number from face declaration
- Replace one std::string constant with a character array
- Use std::vector to store pod face types instead of storing pointers to each face

Improvements and optimizations for the obj-parsers.

---

.github/workflows/ccpp.yml

- tre to use -j <number_of_jobs> in github action.

Experiment: try to enable parallel build

---

code/AssetLib/ASE/ASEParser.cpp

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47392
If parsing mesh in `Parser::ParseLV1SoftSkinBlock` reaches a line end in `filePtr`, the `++filePtr;` advances the `filePtr` past the termination `\0` and the follwing call to `SkipSpacesAndLineEnd` attempts to read one byte past the allocated buffer.

Fixes Heap-buffer-overflow READ in Assimp::ASE::Parser::ParseLV1SoftSkinBlock

---

code/AssetLib/FBX/FBXBinaryTokenizer.cpp

The use of qualified std::uint32_t requires including <cstdint> instead
of <stdint.h> on some implementations, and that breaks the build of Qt 6
on GCC 13. Just use the unqualified name everywhere.

Use unqualified uint32_t everywhere in FBXBinaryTokenizer

---

cmake-modules/FindPkgMacros.cmake

`DirectX_LIBRARY` was always clearing, though `DirectX_PREFIX_PATH` was not changed. This is because I had some extra semicolons at begin of `DirectX_PREFIX_PATH` and the macro `clear_if_changed` discarded them. Now it saves all extra semicolons and check passes.

Fix problems setting DirectX_LIBRARY

---

code/AssetLib/glTF/glTFAsset.h
code/AssetLib/glTF/glTFAsset.inl
code/AssetLib/glTF/glTFImporter.cpp

The reason for this PR is that when loading glTF 2.0 scenes, first the glTF importer will be chosen by default and exception will be thrown, which is later resolved in the glTF2 importer.
Example file: https://sketchfab.com/3d-models/griffin-animated-a8852f113416426bb06e6bba49a525a9#download

Remove exception on glTF 2.0 loading

---

code/PostProcessing/JoinVerticesProcess.cpp

If I'm not mistaken. Because this is originally push_back(aniMeshVertex) instead of push_back(v).
And the fact that aniMeshVertex is just getting created and destroyed for nothing.
It need to be replaced with this then? A Clang-tidy syntax to create the same aniMeshVertex.
I found this in pull request #4527 I think it may need to be reviewed too.
Hope it help!

Wrong object is created here!

---

code/AssetLib/MMD/MMDPmdParser.h
code/Common/AssertHandler.cpp
code/Common/AssertHandler.h
code/Common/Base64.cpp
code/Common/BaseImporter.cpp
code/Common/BaseProcess.cpp
code/Common/BaseProcess.h
include/assimp/Base64.hpp
test/CMakeLists.txt
test/unit/Common/utBase64.cpp
test/unit/Common/utBaseProcess.cpp

- Add tests for Base64 edge cases
- Cleanup MMDPmdParser.h after static code analysis von VS2022

[WIP] Code cleanup and some new unittests for edgecases.

---

code/PostProcessing/JoinVerticesProcess.cpp

This bug causes weights to duplicate, i.e. one bone will have several (equal) weights assigned to the same vertex - which then has the potential to cause even bigger problems when combined with `LimitBoneWeightsProcess`.
The fix is not the prettiest but I'm a week before deadline here.

fix vertices being joined duplicating weights

---

code/Common/Maybe.h

Something I should have caught in my review of https://github.com/assimp/assimp/pull/4715 . The val arg should be perfectly forwarded with a universal reference to utMaybe. This allows the value T to be move assigned which allows both can make it more efficient and also allows utMaybe to work with values that are only move assignable. By using perfect forwarding, it will also just pass the reference if T is a reference.
Sorry for not catching this yesterday @kimkulling

Perfect forward val to utMaybe.cpp

---

code/AssetLib/X/XFileImporter.cpp
code/AssetLib/X/XFileImporter.h
code/Common/Compression.h
tools/assimp_cmd/Info.cpp
tools/assimp_cmd/Main.cpp
tools/assimp_cmd/Main.h

- Improve animation in console
- Fix issue with ASCII treeview for window terminals
- closes https://github.com/assimp/assimp/issues/4724

Fix: Use ASCII treeview in assimp-cmd.

---

code/AssetLib/MD5/MD5Parser.cpp
code/AssetLib/MD5/MD5Parser.h

- The MD5-Parser does not check if the end of the imported buffer is reached. So when looking for a line end it can happen that a buffer overrun is caused. This PR introduces the check for the end of the buffer.
- closes https://github.com/assimp/assimp/issues/4695

FIX: Fix head overflow in MD5-parser.

---

code/Common/Assimp.cpp
code/Common/StbCommon.h

This makes it possible to link assimp statically into an executable with another static library that includes stb_image.h without hiding its symbols (be it prefixing names like here, using internal linkage or not exporting in case of shared libraries).
In this particular case prefixing is the only option. Using internal linkage is not efficient because the library is used from multiple translation units. Not exporting is not possible in cases assimp is compiled as a static library.

Prefix symbols from stb_image.h

---

.github/workflows/ccpp.yml
.github/workflows/sanitizer.yml

This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …

GitHub Workflows security hardening

---

test/unit/utglTF2ImportExport.cpp

Fixing std::tuple initial list on old compiler.
compile error log on old compiler
```
/home/sietium/sarah/assimp/test/unit/utglTF2ImportExport.cpp: In member function ‘virtual void utglTF2ImportExport_wrongTypes_Test::TestBody()’:
/home/sietium/sarah/assimp/test/unit/utglTF2ImportExport.cpp:762:5: error: converting to ‘std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with …
```

FIX: C++ std::tuple constexpr initial list on old compiler

---

code/AssetLib/FBX/FBXMeshGeometry.cpp

A customer of ours hit this problem in the "ByPolygonVertex" code path. The same model loads fine in other tools (e.g. Maya viewer) so I think it's worthwhile to make this parsing more robust, also for some other code paths.
Interestingly, a similar fix had been added in this commit:
https://github.com/assimp/assimp/commit/de8adacb54570ca58aa233ed59e5210cefb6f497
...but not for the other code paths.

Make FBX parser resilient to missing data streams

---

Build.md

Commit  #4598 changed the default of building tools from on to off but didn't update the documentation so downstream didn't know to add the flag.

fix incorrect documentation of defaults

---

code/AssetLib/Collada/ColladaParser.cpp
code/AssetLib/FBX/FBXExporter.cpp
code/AssetLib/MD5/MD5Parser.cpp
code/AssetLib/MDL/MDLLoader.cpp
code/PostProcessing/ValidateDataStructure.cpp
contrib/openddlparser/code/OpenDDLExport.cpp

Clang was complaining about a security issue with sprintf and vsprintf, and that they were depreciated and produced a compiler error.

Fixed issue with clang complaining about sprintf and vsprintf being depreciated

---

include/assimp/quaternion.inl

- Use ai_epsilon instead of the estimated one
- closes https://github.com/assimp/assimp/issues/4751

FIX: Use correct epsilon

---

code/AssetLib/Ply/PlyParser.cpp

* fix bug reading ply file in case of presence of "end_header\n<BINARY_DATA>..." with <BINARY_DATA> starting by "\n"

* fix bug reading ply file in case of presence of "end_header\n<BINARY_DATA>..." with <BINARY_DATA> starting by "\n"

---

code/AssetLib/Collada/ColladaExporter.cpp

Fixed error with `\0` symbol in XML structure inside exported collada file, described in #4758

Fixed error with trailing zero symbol as placeholder character

---

code/AssetLib/3MF/XmlSerializer.cpp
code/AssetLib/Blender/BlenderLoader.cpp
code/AssetLib/Collada/ColladaParser.cpp
code/AssetLib/DXF/DXFLoader.cpp
code/AssetLib/FBX/FBXDocument.cpp
code/AssetLib/FBX/FBXExportNode.h
code/AssetLib/FBX/FBXExporter.cpp
code/AssetLib/IFC/IFCBoolean.cpp
code/AssetLib/IFC/IFCGeometry.cpp
code/AssetLib/IFC/IFCLoader.cpp
code/AssetLib/IFC/IFCOpenings.cpp
code/AssetLib/Ply/PlyParser.cpp
code/AssetLib/Ply/PlyParser.h
code/AssetLib/XGL/XGLLoader.cpp
code/AssetLib/glTF/glTFCommon.h
include/assimp/XmlParser.h

Optimize the code by adding a lot of missing std::move and a few std::forwards for perfect forwarding. This PR should reduce the number unnecessary copies and overall increase efficiency.

chore: add missing std moves and perfect forwards

---

code/AssetLib/FBX/FBXDocument.cpp

If an out-of-memory exception is thrown during model import, it is usually trickled up by assimp and we can determine that it is the reason for failure. However, this particular code path in the FBX importer would just blindly swallow all exceptions and simply ignore a part of the mesh. That lead to issues where parts of a mesh or the entire model were skipped and assimp reported successful import.
I'm generally not that happy that code just catches exceptions and claims it's all fine, even though it doesn't even try to figure out what kind of exception this was. IMO this is very fragile.
Though more specifically, an out-of-memory situation should always be treated as a serious error, since it is unlikely that the following code will be able to continue.

Don't hide out-of-memory during FBX import

---

code/AssetLib/glTF2/glTF2Asset.h
code/AssetLib/glTF2/glTF2Asset.inl
code/AssetLib/glTF2/glTF2AssetWriter.h
code/AssetLib/glTF2/glTF2AssetWriter.inl
code/AssetLib/glTF2/glTF2Exporter.cpp
code/AssetLib/glTF2/glTF2Exporter.h
code/AssetLib/glTF2/glTF2Importer.cpp

according to spec: https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_emissive_strength

Added support for KHR_materials_emissive_strength

---

.github/workflows/ccpp.yml

Just use parallel command to improve the readability.

Introduce --parallel instead of .j

---

code/AssetLib/Blender/BlenderDNA.h

It is an ODR violation to use a template specialization for which an explicit specialization is defined somewhere whose declaration is not visible at the point of use.
Found via clang's `-Wundefined-func-template` warning.

[BlenderDNA.h] Declare explicit specializations

---

code/Common/SkeletonMeshBuilder.cpp
code/Common/StandardShapes.cpp

Warnings-as-errors currently breaks on MSVC 2019 Debug X64:
```1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xmemory(681,68): error C2220: the following warning is treated as an error (compiling source file ..\..\assimp\code\Common\StandardShapes.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vector(713): message : see reference to function template instantiation 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,float,double,float>(_Alloc &,_Objty *const ,float &&,double &&,float &&)' being compiled
1>        with
1>        [
1>            _Alloc=std::allocator<aiVector3D>,
1>            _Ty=aiVector3t<ai_real>,
1>            _Objty=aiVector3t<ai_real>
1>        ] …
```

fix warnings-as-errors for msvc 2019 x64

---

code/AssetLib/OFF/OFFLoader.cpp

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49797
The root cause of the crash is that [InternReadFile](https://github.com/assimp/assimp/blob/0fdae2879d78864693ee730610dcf8ee10707875/code/AssetLib/OFF/OFFLoader.cpp#L108) allocates 9 faces.
```cpp
mesh->mNumFaces = numFaces;
aiFace* faces = new aiFace[mesh->mNumFaces];
```
Later in the same function in [`for (unsigned int i = 0; i < numFaces; )`](https://github.com/assimp/assimp/blob/0fdae2879d78864693ee730610dcf8ee10707875/code/AssetLib/OFF/OFFLoader.cpp#L284) loop in goes into
```cpp
if(!idx || idx > 9) {
ASSIMP_LOG_ERROR("OFF: Faces with zero indices aren't allowed");
--mesh->mNumFaces;
continue;
}
```
which decrements the number of faces an continues the loop. Note that the loop doesn't have `i++`, so it repeats the loop with …

Fixes Heap-buffer-overflow READ 4 in Assimp::ScenePreprocessor::ProcssMesh

---

code/AssetLib/MD5/MD5Parser.cpp

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49422 When it reaches the `SkipSpacesAndLineEnd`, `in` already points past `bufferEnd` and it leads to out of bounds memory read.

Fixes Heap-buffer-overflow READ 1 in Assimp::MD5::MD5Parser::ParseHeader

---

code/AssetLib/Obj/ObjFileParser.cpp
code/AssetLib/Obj/ObjTools.h

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=49274
The `m_DataIt` in `void ObjFileParser::getFace` is increased in steps `m_DataIt += iStep;` that may jump over `m_DataItEnd` and then `while (m_DataIt != m_DataItEnd)` continues. This leads to out of bounds memory read access.

Fixes Heap-buffer-overflow READ 1 in Assimp::ObjFileParser::getFace

---

code/AssetLib/FBX/FBXCommon.h
code/AssetLib/FBX/FBXExportNode.cpp

Fixed vector subscript out of range bug when NULL_RECORD is passed to PutString and is actually null (i.e a string "" with size 0). Replaced it with a std::string initialized by '\0' time NumNullRecords. The cause of this issue might be that the std::string constructor gets the correct const char* but stops after seeing that the first element is '\0'.

Fixed bug when exporting binary FBX

---

code/AssetLib/LWO/LWOAnimation.cpp

- closes https://github.com/assimp/assimp/issues/4860

Fix: Fix possible division by zero

---

include/assimp/mesh.h

(Reported in issue #4874)
Improve type safety for `mMethod`:
- change type of `mMethod` from `unsigned int` to `enum aiMorphingMethod`
- add enum value `aiMorphingMethod_UNKNOWN ` to cover the current default assignment

Change mMethod type to enum aiMorphingMethod

---

code/AssetLib/M3D/M3DWrapper.cpp
code/AssetLib/M3D/M3DWrapper.h

`M3DWrapper.h` is designed to omit the definition of `class M3DWrapper` if neither M3D import nor M3D export are compiled. 608bccd9cf3a28c55163c10e84aec025293b7ab0 touched the corresponding preprocessor checks and introduced a bug:
```
#ifndef ASSIMP_BUILD_NO_M3D_IMPORTER
#if !(ASSIMP_BUILD_NO_EXPORT || ASSIMP_BUILD_NO_M3D_EXPORTER)
class M3DWrapper {
```
When compiling
- with M3D import enabled,
- but with either export generally disabled or M3D export disabled specifically, These checks evaluate to the wrong result and skip the definition, leading to a build failure in dependent code.
```
#if 1 // import enabled
#if !(1 || 1) // export disabled and M3D export disabled
```
This commit fixes the check to compile the definition if neither import is disabled.

Fix #4262 Build With M3D Import Only

---

code/AssetLib/Ogre/OgreImporter.h
code/AssetLib/glTF2/glTF2Importer.h

These functions are already marked “override”, and their neighbors had “virtual” removed as well.

Remove Useless “virtual”

---

code/AssetLib/glTF2/glTF2Importer.cpp

Uses the correct math, as detailed in #4435.
This also preserves the behavior that if mAspect == 0, the computed horizontal fov will just pass through the vertical fov unchanged, so that it can be recovered and computed properly according to the gltf2 spec later.
Further math reference [here](https://stackoverflow.com/questions/5504635/computing-fovx-opengl), with a nice visual demo of why this matters [here](https://twgljs.org/examples/fov-checker.html).

Fix: fix incorrect math for calculating the horizontal FOV of a perspective camera in gltf2 import #4435

---

code/AssetLib/MMD/MMDImporter.cpp
code/AssetLib/X3D/X3DGeoHelper.cpp
code/AssetLib/X3D/X3DImporter_Geometry2D.cpp

Several places in the code call `std::vector<aiVector3D>.emplace_back(0, 0, 0)`. The constructor of `aiVector3D` actually expects arguments of the type `ai_real`, (alias of `float` if compiling without `ASSIMP_DOUBLE_PRECISION`) but the literal `0` is of type `int`.
`emplace_back()` does support promotion, but `int` to `float` is a potentially lossy conversion. tl;dr: On warning level 4, MSVC spits out a very deeply nested `warning C4244: 'argument': conversion from '_Ty' to 'TReal', possible loss of data with _Ty=int and TReal=ai_real`.
I used `static_cast<ai_real>()` in the affected places because both `ai_real(0)` and `(ai_real)0` are regarded as C-style casts and frowned upon by various linters, e.g. clang-tidy.

Fix MSVC Warnings With “emplace_back()”

---

code/PostProcessing/GenFaceNormalsProcess.cpp
code/PostProcessing/GenFaceNormalsProcess.h
code/PostProcessing/GenVertexNormalsProcess.cpp
code/PostProcessing/GenVertexNormalsProcess.h

Fixes #3838
When assimp generates normals with aiProcess_GenNormals or aiProcess_GenSmoothNormals it does not take account of aiProcess_MakeLeftHanded, which flips the winding order and requires normals to be flipped.
Previous pull request #3838 fixed the same issue for aiProcess_FlipWindingOrder, but that broke normals for those using both flags (left handed and flipped winding order, typical for DirectX). When both flags are set, no action needs to be taken since the two normal flips cancel out. 
Corrected code flips normals if one or the other flag is set, but not both.

Correctly consider aiProcess_FlipWindingOrder and aiProcess_MakeLeftHanded when generating normals

---

code/AssetLib/FBX/FBXConverter.cpp
include/assimp/mesh.h

This post process step introduced new attributes into `aiSkeletonBone`. Said attributes are only defined with the process enabled, i.e. when the `ASSIMP_BUILD_NO_ARMATUREPOPULATE_PROCESS` macro has not been defined.
Some code, however, accessed the variables unconditionally, leading to build failures if `ASSIMP_BUILD_NO_ARMATUREPOPULATE_PROCESS` was defined.
This commit adds the missing checks.

Fix Build Without ArmaturePopulate Post Process Step

---

.github/workflows/ccpp.yml
CMakeLists.txt

Fails build if `ASSIMP_BUILD_ZLIB=OFF` and zlib is not found. Fixes #3574

Don't build zlib if ASSIMP_BUILD_ZLIB=OFF

---

test/unit/utMetadata.cpp
test/unit/utSharedPPData.cpp

GCC was warning about possibly uninitialized variables. Initialize them and use values which are nonzero and distinct from each other and any real value passed to any set method. This should prevent any false positives from zero initialization.

Unit test warning fixes

---

include/assimp/MemoryIOWrapper.h

As the title says, the the member function `Flush()` of class `MemoryIOStream` need to be marked as override for msvc clang compiling without additional compile flag, otherwise it will not be compiled successfully.
Microsoft Windows 11 (10.0) Professional 64-bit   (Build 22000) 
```console
clang --version
clang version 14.0.5
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin
```
```console
Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/Common/Importer.cpp.obj
FAILED: third-party/assimp/code/CMakeFiles/assimp.dir/Common/Importer.cpp.obj
"D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\Llvm\x64\bin\clang.exe" -DASSIMP_BUILD_NO_C4D_IMPORTER …
```

the member 'Flush()' need to be marked as override for msvc clang compiling

---

CMakeLists.txt
include/assimp/metadata.h
test/unit/utMetadata.cpp

- closes https://github.com/assimp/assimp/issues/4959

Add missing pod types.

---

code/AssetLib/MDL/MDLLoader.cpp
code/AssetLib/SMD/SMDLoader.cpp
code/AssetLib/glTF2/glTF2AssetWriter.inl
contrib/zip/src/miniz.h

These changes fix 'Implicit conversion loses integer precision' errors by explicitly casting to the desired type. I am currently running Apple clang version 14.0.0 (clang-1400.0.29.202) on macOS 13.2.1 (22D68).

Fix implicit conversion errors on macOS

---

code/PostProcessing/JoinVerticesProcess.cpp
code/PostProcessing/JoinVerticesProcess.h

If a bone has too many 'mWeights'(eg : bone->mNumWeights =  50000+), It may takes more than half a minute to adjust bone vertex weights.
We can use mark '0x80000000' to remove the these duplicating weights.
reference commit id: a22aa75bca5da546abb320edefe2da0ae3316535

fix regression in join vertices post process.

---

code/AssetLib/FBX/FBXDocument.cpp

When a duplicate ID is encountered, existing LazyObject is overwritten. Previously allocated instance leaks.
This change deletes the previously allocated instance before overwriting the pointer.

Fix a leak in FBXDocument when duplicate object IDs are found

---

code/Common/Subdivision.cpp
test/unit/utACImportExport.cpp
test/unit/utBlenderImportExport.cpp

Makes subdivision process about 5 - 10% faster. Also improves the unit tests for some subdivision models so it should catch if the process goes wrong somehow.

Optimize subdivision process

---

code/PostProcessing/ValidateDataStructure.cpp
test/unit/ImportExport/MDL/utMDLImporter_HL1_ImportSettings.cpp
test/unit/ImportExport/MDL/utMDLImporter_HL1_Materials.cpp
test/unit/ImportExport/MDL/utMDLImporter_HL1_Nodes.cpp

Add a check that node hierarchy parents point to correct nodes.
This reveals a problem in Half-Life MDL loader and must not be merged until that is fixed.

Validate node hierarchy parents

---

contrib/unzip/crypt.c

After trying a version update from 5.2.5 I discovered some build issues if included in UWP projects.
I come up with a simple solution, skipping just the missing function in windows libraries. There seems to be some system function in UWP to get a similar behavior. 
For me, it doesn't matter if this function is executed that way. If there is a way to just not include unzip code or replace with UWP support, I didn't find it the last days.

Fix link issue in UWP builds without functional replacement

---

code/AssetLib/glTF/glTFAsset.h
code/CMakeLists.txt

Fix the following warnings when `-Wno-nested-anon-types` is removed.
```
D:\workspace\CODE\assimp\code\AssetLib/glTF/glTFAsset.h(518,9): error : anonymous types declared in an anonymous union
are an extension [-Werror,-Wnested-anon-types] [D:\workspace\CODE\assimp\build-msvc-clang\code\assimp.vcxproj]
D:\workspace\CODE\assimp\code\AssetLib/glTF/glTFAsset.h(525,9): error : anonymous types declared in an anonymous union
are an extension [-Werror,-Wnested-anon-types] [D:\workspace\CODE\assimp\build-msvc-clang\code\assimp.vcxproj]
```
The build script is as follows:
```
@echo off
setlocal
set CMAKE_HOME=D:\Tools\cmake-3.26.0-windows-x86_64
set PATH=%CMAKE_HOME%\bin;%PATH%
cmake --version
ninja --version
set SRC=%CD%
set BUILD_ROOT=%SRC%\build-msvc-clang
set BUILD_TARGET=assimp
cmake -B …
```

Fix warning related to nested-anon-types.

---

code/AssetLib/B3D/B3DImporter.cpp
code/AssetLib/LWO/LWOMaterial.cpp
code/CMakeLists.txt
contrib/poly2tri/poly2tri/sweep/sweep.cc

Fix the following warnings when `-Wno-unreachable-code` is removed.
```
D:\workspace\CODE\assimp\code\AssetLib\B3D\B3DImporter.cpp(421,13): error : code will never be executed [-Werror,-Wunre
achable-code] [D:\workspace\CODE\assimp\build-msvc-clang\code\assimp.vcxproj]
D:\workspace\CODE\assimp\code\AssetLib\LWO\LWOMaterial.cpp(348,35): error : code will never be executed [-Werror,-Wunre
achable-code] [D:\workspace\CODE\assimp\build-msvc-clang\code\assimp.vcxproj]
D:\workspace\CODE\assimp\contrib\poly2tri\poly2tri\sweep\sweep.cc(143,9): error : code will never be executed [-Werror,
-Wunreachable-code] [D:\workspace\CODE\assimp\build-msvc-clang\code\assimp.vcxproj]
D:\workspace\CODE\assimp\contrib\poly2tri\poly2tri\sweep\sweep.cc(123,9): error : code will never be executed [-Werror, …
```

Fix warning related to unreachable-code.

---

code/AssetLib/FBX/FBXConverter.cpp
code/AssetLib/FBX/FBXConverter.h
code/PostProcessing/ConvertToLHProcess.cpp
code/PostProcessing/ConvertToLHProcess.h

The viewing direction of cameras should be inverted during conversion to a left handed coordinate system.

ConvertToLHProcess now inverts viewing direction

---

code/AssetLib/Obj/ObjFileImporter.cpp

- closes https://github.com/assimp/assimp/issues/4918

Fix possible dereferencing of invalid pointer.

---

code/AssetLib/Collada/ColladaParser.cpp
code/AssetLib/LWO/LWOBLoader.cpp
code/AssetLib/LWO/LWOLoader.cpp
code/AssetLib/Obj/ObjFileParser.cpp
code/AssetLib/Q3D/Q3DLoader.cpp
code/AssetLib/X/XFileParser.cpp
code/CMakeLists.txt
code/PostProcessing/ValidateDataStructure.cpp

Fix the following warnings when `-Wno-unreachable-code-break` is removed.
```
D:\workspace\CODE\assimp\code\PostProcessing\ValidateDataStructure.cpp(293,17): error : 'break' will never be executed
[-Werror,-Wunreachable-code-break] [D:\workspace\CODE\assimp\build-msvc-clang\code\assimp.vcxproj]
D:\workspace\CODE\assimp\code\AssetLib\Collada\ColladaParser.cpp(1858,13): error : 'break' will never be executed [-Wer
ror,-Wunreachable-code-break] [D:\workspace\CODE\assimp\build-msvc-clang\code\assimp.vcxproj]
```

Fix warning related to unreachable-code-break.

---

CMakeLists.txt

Fixes #5062 https://github.com/assimp/assimp/issues/5062
By allowing default action like prior for building of zlib for specific other platform targets. Recent changes made this occur for win32 only. Unsure why ! ?
Compiles now on iOS / Emscripten with latest master (this)

Build Zlib if missing for other platforms

---

code/AssetLib/Assjson/cencode.c
code/AssetLib/Blender/BlenderCustomData.cpp
code/AssetLib/FBX/FBXMaterial.cpp
code/AssetLib/SIB/SIBImporter.cpp
code/CMakeLists.txt
contrib/unzip/unzip.c

Fix the following warnings when `-Wno-missing-variable-declarations` is removed.
```
D:\workspace\CODE\assimp\code\AssetLib\Blender\BlenderCustomData.cpp(99,1): message : declare 'static' if the variable
is not intended to be used outside of this translation unit [D:\workspace\CODE\assimp\build-msvc-clang\code\assimp.vcxp
roj]
```

Fix warning related to missing-variable-declarations.

---

code/PostProcessing/ConvertToLHProcess.cpp

Add missing cast to prevent template instantiation error with double precision build config.
See the issue [here](https://github.com/assimp/assimp/pull/5057#issuecomment-1527187329]).

Add missing cast

---

code/Common/SceneCombiner.cpp

Metadata with sub-objects failed to copy due to default assertions.
Pushed this, but have not seen that #4658 has the same fix, so this could also be merged.

Fix: Copy aiMetadata in SceneCombiner

---

code/CMakeLists.txt
code/Common/StbCommon.h

Fix the following warnings when `-Wno-unused-function` is removed.
There is a same issue #5065.

Fix warning related to unused-function.

---

contrib/pugixml/src/pugiconfig.hpp
contrib/pugixml/src/pugixml.cpp
contrib/pugixml/src/pugixml.hpp

Release highlights:
xml_attribute::set_value, xml_node::set_value and xml_text::set now have overloads that accept pointer to non-null-terminated string and size Fix error handling in xml_document::save_file that could result in the function succeeding while running out of disk space Fix memory leak during error handling of some out-of-memory conditions during xml_document::load

Update pugiXML library

---

code/PostProcessing/LimitBoneWeightsProcess.cpp
code/PostProcessing/LimitBoneWeightsProcess.h

The post processing step LimitBoneWeightsProcess currently always removes unused bones because the config property AI_CONFIG_IMPORT_REMOVE_EMPTY_BONES has not been used to toggle this behavior on and off.
This change adds a property look up so LimitBoneWeightsProcess won't remove unused bones anymore when the client doesn't want this behavior.

Fixed missing config property lookup for removal of empty bones.

---

CMakeLists.txt

Fix a lot of CVE vulnerabilities
Update abseil to LTFS 20220623.1 by @butteredmonkey in #656 Fix Hunter on Windows MSVC CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE 'ARM64EC' by @ccmvn in #659 openssl: update openssl to the latest 1.1.1t by @res0nance in #660 ceres-solver: per default disable CUDA support by @NeroBurner in #665 update range-v3 to version 0.12.0 by @alex-tdrn in #670 Update 'pybind11' to 2.10.4 by @hjmallon in #667
cli11: update cli11 to 2.3.2 by @res0nance in #669 openssl: update to v3 as 1.1.1 is almost eol by @res0nance in #668 Fix Hunter on Windows MSVC CMAKE_VS_PLATFORM_TOOLSET_HOST_ARCHITECTURE 'ARM64' by @ccmvn in #655 Boost: Fix building b2 (+ headers) on Apple tvOS with Xcode generator by @hjmallon in #647 assimp: add version 5.2.5 by @NovaSurfer in #640 …

Update cpp-pm / hunter

---

code/AssetLib/glTF2/glTF2Importer.cpp
code/AssetLib/glTF2/glTF2Importer.h

This PR fixes an oversight in this PR: https://github.com/assimp/assimp/pull/5003
that caused a regression for some skinned animations in GLTF files.
Rather than backing out the optimization from the original PR, this is a proper fix to it.
Essentially, I forgot to apply the vertex remapping to the skinning weights per vertex.

Skinning weights in gltf were broken by PR#5003 (vertex remapping)

---

code/AssetLib/OFF/OFFLoader.cpp

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=57001
Closes #5069
The crash occures in [SortByPTypeProcess::Execute](https://github.com/assimp/assimp/blob/4180b1fd080b2cab0a2d3a3149eff1f5163ee888/code/PostProcessing/SortByPTypeProcess.cpp#L175) when `pFirstFace->mNumIndices == 0`. The root cause is that the faces are not initialized and skipped (`break`) during the loading.

Fix UNKNOWN WRITE in Assimp::SortByPTypeProcess::Execute

---

CMakeLists.txt

Fix: disabled dangling-reference warning in gcc13

---

port/PyAssimp/pyassimp/core.py

Previously only the first character of the string was passed to c, now it passes the whole extension.

[pyassimp] Fix passing of file extension string.

---

code/AssetLib/Blender/BlenderLoader.cpp
code/AssetLib/Blender/BlenderLoader.h

Previously the `InternReadFile` logic was much more restrictive than the `CanRead` logic, but able to also parse compressed files. With this change the behavior is unified.

Unify way to check readable blender files.

---

code/Common/BaseImporter.cpp
include/assimp/BaseImporter.h

This way we can fix Blender exported files being wrongly detected as obj files, if the filename didn't contain any extension information, e.g. when loading a binary glb file named `blob`.

Extend token search flag from alpha to graph.

---

code/Common/BaseImporter.cpp
code/Common/Importer.cpp
include/assimp/BaseImporter.h

This enables proper checking for all kinds of extensions (including the ones with multiple dots) for all importers and internal usage.
This way we can also benefit from e.g. stripping away versioning information attached behind the actual extension, see also #5156.

Unify extension check for importers.

---

code/AssetLib/glTF2/glTF2Exporter.cpp
test/unit/utglTF2ImportExport.cpp

Currently when exporting as glTF2 the detection of a specular material requires that both `AI_MATKEY_COLOR_SPECULAR` and `AI_MATKEY_SPECULAR_FACTOR` are set. One of them should actually be enough, which I think was also the original intention, according to the comment.

Fix detection of `KHR_materials_specular` on glTF2 export.

---

code/Common/BaseImporter.cpp
test/unit/utImporter.cpp

If a user uses its own `IOSystem`/`IOStream` for handling google cloud storage uris, with this PR the extension will still be correct. Together with #5157 the following will be supported without going over all possible importers and trying to detect the format:
```
Assimp::Importer importer;
importer.SetIOHandler(new GsIOSystem(...));
const aiScene* scene = importer.ReadFile("gs://bucket/model.glb#1234", ...);
...
```

Handle gcs cloud storage file extensions with versioning.

---

CMakeLists.txt

Assimp CMakeLists forcefully adds /W4 /WX flags with MSVC, even when `ASSIMP_WARNINGS_AS_ERRORS` is disabled. This fixes it

Remove /WX from CMakeLists for MSVC

---

code/AssetLib/NDO/NDOLoader.cpp

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58770
In this case `temp` is max unsigned int. `temp + 76` was overflowing the integer and `reader.IncPtr` was reading 75 bytes. However later `std::string(head, temp)` was reading the maximum number of characters, leading to out of bounds read.

Fix UNKNOWN READ in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<ch

---

code/CMakeLists.txt

The previously-specified paths were only correct for a static library build.
I therefore fenced off that code to be specific to static library builds.
For shared library builds, I added a generator-expression-based alternative.
Annoyingly, this won't work with static library builds, so we don't get the concise, reliable version in all circumstances.
I've avoided modifying any of the paths anything ends up at to avoid breaking changes.
Resolves https://github.com/assimp/assimp/issues/4269

Use correct PDB paths

---

code/AssetLib/glTF2/glTF2Importer.cpp

Fixed: https://github.com/assimp/assimp/issues/5211

Ensure that the strength attribute is the same when importing or exporting gltf2

---

code/AssetLib/Collada/ColladaLoader.cpp
code/AssetLib/Collada/ColladaLoader.h
include/assimp/config.h.in

I needed the option to ignore the unit size scaling for Collada imports.
This PR adds a property `AI_CONFIG_IMPORT_COLLADA_IGNORE_UNIT_SIZE` which controls if the unit size scaling is applied to the root node's transform or not. It works similar to the existing `AI_CONFIG_IMPORT_COLLADA_IGNORE_UP_DIRECTION` property.
The default value is false, so the behavior for Collada imports will not change unless explicitly requested.

Collada: added import property to disable unit size scaling

---

code/AssetLib/glTF2/glTF2Exporter.cpp

I am using the assimp exporter and I have noticed that I can't add aiTextureType_DIFFUSE_ROUGHNESS when exporting to  glb2 format. Therefore, I would like to add it.

Add DIFFUSE_ROUGHNESS_TEXTURE for gltf2 exporter

---

code/Common/PolyTools.h
code/PostProcessing/TriangulateProcess.cpp

According to the current Ear Clipping algorithm, point 2 is not within triangle 5, 9, 11, But point 2 is on the edge of 5-11. In this case, the triangle generated will cover the hole on the right.
I modified the `OnLeftSideOfLine2D` function so that it can determine whether it is left or right or on the side.
Here are the results of the test.
And this is the FBX file that I tested.
[double_hold.zip](https://github.com/assimp/assimp/files/12343171/double_hold.zip)

Update Triangulate Process

---

code/AssetLib/DXF/DXFLoader.cpp

In DXF files, negative value is allowed for the "Polyface mesh vertex index" of the VERTEX entity.
https://help.autodesk.com/view/ACD/2024/ENU/?guid=GUID-0741E831-599E-4CBF-91E1-8ADBCFD6556D
> If the index is negative, the edge that begins with that vertex is invisible. 
However, the current implementation of `DXFImporter::ParsePolyLineVertex()` converts negative index to 0 and cannot handle them correctly.
This pull request ensures that negative index is handled correctly by reading their absolute value.

DXF: Support negative index in VERTEX

---

contrib/draco/CMakeLists.txt

Re-fixes the #3663 issue, this was caused by the recent update (https://github.com/assimp/assimp/commit/39efe4c832c02e8e6560b9922b0504716fd3c99c)
#4114 Could re-open this issue if draco is updated again without changing the cmake path to assimp's

Fix draco build path

---

include/assimp/defs.h

When I include `<assimp/scene.h>` in multiple translation units in C it doesn't compile.
```
duplicate symbol '_ai_epsilon' in:
...
```
The bug is been there at least few months. I don't wanna edit `<assimp/defs.h>` in line 295 everytime i create a new project using assimp. Please accept.

ai_epsilon bug fixed in C

---

code/AssetLib/MD5/MD5Parser.cpp
code/AssetLib/MD5/MD5Parser.h

- closes https://github.com/assimp/assimp/issues/5257

Fix: Add check for invalid input argument

---

code/AssetLib/Irr/IRRLoader.cpp

This fixes a compilation error of the lib when `ASSIMP_DOUBLE_PRECISION` is set to `ON`

use size in order to be compatible with float and double

---

code/AssetLib/IFC/IFCLoader.cpp

In latest versions of XCode when building Assimp for ARM processor `Implicit conversion loses integer precision` warning is treated as error.
It happens when we try to assign `unsigned long` value (which is 8 bytes sized) to `int` variable (which is 4 bytes). `static_cast` covers this problem here and it is safe because length check before conversion already exists.

Fix: Implicit Conversion Error

---

code/AssetLib/glTF2/glTF2Asset.inl

This loads target names from the first primitive if available. Names from the mesh root will still overwrite the ones from the primitive.
- closes https://github.com/assimp/assimp/issues/5354

Fix target names not being imported on some gLTF2 models

---

code/AssetLib/3DS/3DSConverter.cpp
code/AssetLib/3DS/3DSLoader.cpp
code/AssetLib/ASE/ASELoader.cpp
code/AssetLib/Blender/BlenderScene.cpp
code/AssetLib/Collada/ColladaParser.cpp
code/AssetLib/FBX/FBXConverter.cpp
code/AssetLib/FBX/FBXDeformer.cpp
tools/assimp_view/assimp_view.cpp

Similar to #5248, this pull request consists entirely of small corrections to comments in C++ source files.

correct grammar/typographic errors in comments (8 files)

---

code/AssetLib/glTF2/glTF2Asset.h
code/AssetLib/glTF2/glTF2Asset.inl
code/AssetLib/glTF2/glTF2AssetWriter.inl
code/AssetLib/glTF2/glTF2Exporter.cpp
code/AssetLib/glTF2/glTF2Importer.cpp

I found 2 issues while exporting the official assets ( https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/SpecularTest)
1. It doesn't provide proper properties for an extension, default values are different in the spec
2. It overrides the Specular texture type (specular and specularColor by the spec are separate)

KHR_materials_specular fixes

---

CMakeLists.txt

- closes https://github.com/assimp/assimp/issues/5340

Build: Disable building zlib for non-windows

---

code/AssetLib/DXF/DXFLoader.cpp

This is a very simple one line change.
In the previous version, if a dfx had multiple inserts that had different scales, assimp would place the insert in xyz space in locations that were incorrect. Outputs from assimp would have files that would be very different from what apps like sketchup or the online autodesk viewer would produce.
The bug was because scaling of the insert was being done before placement, resulting in the placement being placement•scale. For example, the insert would be placed at (pos.x•scale.x),(pos.y•scale.y),(pos.z•scale.z) instead of pos.x, pos.y, pos.z
Moving the line of code responsible for determining placement to before the line of code dealing with scaling fixes this.
I suspect this was an edge-case as the code has been in use for 10 or 12 years now and there …

Fix for issues #5422, #3411, and #5443 -- DXF insert scaling fix and colour fix

---

code/Common/StbCommon.h

This enables C++ API users to statically link Assimp into their projects along with stb_image.

Update StbCommon.h to stay up-to-date with stb_image.h.

---

code/AssetLib/glTF2/glTF2Asset.h
code/AssetLib/glTF2/glTF2Asset.inl

This small PR does not add any features or change in behavior. 
It just makes loading of fuzzed gltf files more secure because it throws more exceptions for index out-of-range cases.
We came across these cases as part of our automated input file fuzzing tests.

More GLTF loading hardening

---

code/AssetLib/FBX/FBXExporter.cpp

When loading a mesh exported from assimp into Blender, it warns that it has an incorrect class. While debugging, I traced it back to this being `Blendshape` where `Geometry` was expected. This is likely because this node describes a `Geometry`, which is used as a blendshape. I'm not sure if any other DCC tools or places to import it expect `Blendshape` instead (i.e. was this code ever tested?), but it fixes its use in Blender.
Fixes #5418 
Test Mesh:
[headblendshape.zip](https://github.com/assimp/assimp/files/13899594/headblendshape.zip)
Note this is actually not the mesh I originally tested on, but the original was proprietary.

`Blendshape`->`Geometry` in FBX Export

---

code/AssetLib/glTF/glTFExporter.cpp
code/AssetLib/glTF/glTFExporter.h
code/AssetLib/glTF2/glTF2Exporter.cpp
code/AssetLib/glTF2/glTF2Exporter.h
include/assimp/config.h.in
include/assimp/matrix4x4.h
include/assimp/matrix4x4.inl
test/unit/AssimpAPITest_aiMatrix4x4.cpp
test/unit/utMatrix4x4.cpp
test/unit/utglTF2ImportExport.cpp

Adds an extra epsilon value to check the matrix4x4 identity. The method is also used to export to GLTF/GLTF2 format to check node transformation matrices. The epsilon value can be set using AI_CONFIG_CHECK_IDENTITY_MATRIX_EPSILON with the default value set to 10e-3f for backward compatibility of legacy code.

Fix identity matrix check

---

contrib/clipper/clipper.cpp

This PR updated some comments in clipper, eliminating the non-ascii characters.
When compiling with MSVC, these non-ascii characters cause warning C4819 which may be treated as error. Deleting these non-ascii makes me build assimp with MSVC successfully in my environment : )

Eliminate non-ascii comments in clipper

---

code/AssetLib/Obj/ObjFileParser.cpp
code/Common/StackAllocator.inl
code/PostProcessing/ProcessHelper.cpp

This PR fixes Assimp compilation for older compilers with lack of C++17 support such as MSVC14.
- `std::min`/`max` were not defined in *StackAllocator.inl*; Also added explicit template arguments to break macro expansion if *Windows.h* is included prior and `NOMINMAX` macro is not present.
- Made `static_assert` statements compatible with C++11 in *ProcessHelper.cpp*.
- Removed unused `string_view` include in *ObjFileParser.cpp*.

Fix compilation for MSVC14.

---

test/unit/UnitTestFileGenerator.h

`utDefaultIOStream.FileSizeTest` fails on MinGW's GCC, since it assumes a *nix OS and tries to [create a temporary file](https://github.com/assimp/assimp/blob/feb861f17bf937fd42e0591b3347b95009033eec/test/unit/utDefaultIOStream.cpp#L63) at `/tmp/rndfp.XXXXXX`. There're many other places which checks for MINGW macros, so I guess it wasn't intentional.
```
[==========] 574 tests from 115 test suites ran. (16450 ms total)
[  PASSED  ] 573 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] utDefaultIOStream.FileSizeTest
1 FAILED TEST
```
[Similar logic](https://github.com/assimp/assimp/blob/master/test/unit/utIOStreamBuffer.cpp#L89) is used in `utIOStreamBuffer.cpp`, although there it just creates the files in the cwd without any `TMP_PATH`.

Fix utDefaultIOStream test under MinGW

---

CMakeLists.txt
code/AssetLib/C4D/C4DImporter.cpp
code/AssetLib/C4D/C4DImporter.h

The [latest Cineware SDK explicitly asserts macOS support in its documentation](https://developers.maxon.net/docs/cw/22_004/page_general_information.html), but Assimp's C4D importer only works with Windows MSVC targets. Let's improve its portability by refactoring importer code to not depend on MSVC-only data types and quirks, and add support for linking against the universal macOS static libraries provided in the Cineware SDK.
Note that the C4D importer still cannot support Linux platforms because Maxon does not provide the necessary precompiled Cineware libraries for that platform. Windows MinGW targets are also out of the question as the MinGW toolchain uses compiled libraries in a different format.

Add initial macOS support to C4D importer

---

code/Common/BaseImporter.cpp
code/Common/BaseProcess.cpp
code/Common/BaseProcess.h
code/Common/Importer.h
code/Common/SGSpatialSort.cpp
code/Common/ScenePreprocessor.h
code/Common/StackAllocator.h
code/Common/StackAllocator.inl
code/Common/Subdivision.cpp
code/Common/TargetAnimation.cpp
code/Common/TargetAnimation.h
code/Common/VertexTriangleAdjacency.cpp
code/Common/ZipArchiveIOSystem.cpp
include/assimp/BaseImporter.h
include/assimp/ByteSwapper.h
include/assimp/IOStream.hpp
include/assimp/IOStreamBuffer.h
include/assimp/Importer.hpp
include/assimp/LineSplitter.h
include/assimp/SGSpatialSort.h
include/assimp/aabb.h
include/assimp/anim.h

- Remove default marked destructors from cpp files
- Unify importer doc
- Make importers final
- Replace typedefs by using statements

Cleanup: Fix review findings

---

CMakeLists.txt
code/CMakeLists.txt

In [Silk.NET](https://github.com/dotnet/Silk.NET) we're packaging Assimp as a native dependency. We'd like to enable Draco in our Assimp build but would also like to avoid having to ship the extra shared library. This patch adds an option `ASSIMP_BUILD_DRACO_STATIC` which allows building and linking Draco statically into Assimp.
This only works when using the bundled Draco since there doesn't seem to be an obvious way to make it work with `find_package()`.
I'm only able to test this on Linux. Hopefully it just works on Windows and macOS in CI...

CMake: Allow linking draco statically if ASSIMP_BUILD_DRACO_STATIC is set.

---

code/PostProcessing/SplitByBoneCountProcess.cpp

Due to a == that should have been a != nodes weren't updated after split.
Fixes #5549

Fix SplitByBoneCount typo that prevented node updates

---

code/PostProcessing/CalcTangentsProcess.cpp

ASSIMP's way of calculating bitangents before commit ad766cb was just fine, but unfortunately it was changed by that commit in February 2022, breaking compatibility to previous code.
It introduces two problems:
- It orthogonalizes bitangents w.r.t. tangents (which is generally wrong for texture-mapped meshes).
- It changes the handedness, which is arguably not totally wrong, but breaks compatibility to previous code which uses ASSIMP.
More detailed explanation why the old code was just fine is given in Q&A #5512 
**Suggestion: Just revert to the old code, which this pull request suggests.**

Reverts the changes introduced by commit ad766cb in February 2022.

---

code/AssetLib/ASE/ASEParser.cpp

code was doing vector[0u - 1] dereference in this case
[example model](https://github.com/assimp/assimp/files/15169736/crack.zip)

fix ASE loader crash when *MATERIAL_COUNT or *NUMSUBMTLS is not specified or is 0

---

code/AssetLib/glTF2/glTF2Importer.cpp

VRM is simply GLTF2 with additional extensions.
This extension is popular in certain areas, so support it.

glTF2Importer: Support .vrm extension

---

code/CMakeLists.txt

Fix for #5592 Disabled maybe-uninitialized error for AssetLib/Obj/ObjFileParser.cpp as it seems to be spurious. Also fixed error message for previous GCC build issue modification.

Fix for #5592 Disabled maybe-uninitialized error for AssetLib/Obj/ObjFileParser.cpp

---

contrib/zip/src/zip.c

Original error during building 
```assimp\contrib\zip\src\zip.c(1239,20): error C2220: the following warning is treated as an error```
```assimp\contrib\zip\src\zip.c(1239,20): warning C4267: 'function': conversion from 'size_t' to 'mz_uint', possible loss of data```

Converted a size_t to mz_uint that was being treated as an error

---

code/AssetLib/FBX/FBXMeshGeometry.cpp

Add a conditional judgment to prevent errors.
this test fbx file:
[pipe7.7_test1.fbx.zip](https://github.com/user-attachments/files/15865385/pipe7.7_test1.fbx.zip)

Some FBXs do not have "Materials" information, which can cause parsing errors

---

code/AssetLib/ASE/ASEParser.cpp

remove ASE parsing break added in c1968823adfb8c997f98671becca51fc54614da7 : original intent was to keep parsing
crash case (iMaterialCount = 0) is handled by 47dbabadcd683724be26109c757ad86f4645d280

remove ASE parsing break

---

code/AssetLib/Obj/ObjFileImporter.cpp
code/AssetLib/Obj/ObjFileImporter.h

Fixes memory leak detected by the fuzzer. 
Relevant Issue: https://github.com/assimp/assimp/issues/4131
Not sure, if I can change the protected interface in ObjFileImporter, in case someone inherits from it.  
If this interface change is not Ok, I can rewrite the fix.

fixes potential memory leak on malformed obj file

---

code/PostProcessing/LimitBoneWeightsProcess.cpp
include/assimp/metadata.h
test/unit/utMetadata.cpp

This PR fixes some bool loads which are not initialized. With ubsan and the "option -fsanitize=bool", this results in a runtime error during test execution.
When running the unittest suite with activated UBSan with Clang 17.0.6, I get 2 runtime errors.
- `mRemoveEmptyBones` is not initialized when running the test "LimitBoneWeightTest". It is not initialized due to missing `SetupProperties` call. I decided to initialize the option with default off, in case someone else calls "processMesh" without setting up the properties first. I decided for default true value, is this seems to be the default value in SetupProperties, when it is not defined
```
this->mRemoveEmptyBones = pImp->GetPropertyInteger(AI_CONFIG_IMPORT_REMOVE_EMPTY_BONES, 1) != 0;
```
- uninit load in "utMetadata.copy_test". …

Fixes some uninit bool loads

---

include/assimp/postprocess.h
port/PyAssimp/pyassimp/postprocess.py
port/dAssimp/assimp/postprocess.d
port/jassimp/jassimp/src/jassimp/AiPostProcessSteps.java

The names of the `aiPrimitiveType` point and line are misspelled with a plural 's' in the docstring of the `aiProcess_FindDegenerates` flag. The enum values are defined in `include/assimp/mesh.h`
Also, I think the docstring for `mMeshes` in https://github.com/assimp/assimp/blob/cdf8394ccc4adac94aae9ac395d09eb03608ef2d/include/assimp/scene.h#L271 might not be correct; shouldnt the last sentence be "... there will always be at least ONE mesh.", since this is the docstring of `mMeshes` and materials are declared later in the file? If someone can confirm this, I will create a separate PR for this minor change.

Fix names of enum values in docstring of aiProcess_FindDegenerates

---

code/Common/StackAllocator.h

Hey there. This fix is very simple but leaves the ability to adjust the StackAllocator. On the BSDs and Mac, when building a static library and building the FBX Importer, on certain configurations, this error can appear: `/usr/local/bin/ld: ../engine/libengine-editor.so: undefined reference to Assimp::StackAllocator::g_maxBytesPerBlock`.
An alternative suggestion can be found here: https://github.com/thunder-engine/thunder/pull/771#discussion_r1661843671

Fix: StackAllocator Undefined Reference fix

---

Dockerfile

- Use --no-install-recommends to avoid getting more deps than needed

Docker: Fix security finding

---

code/AssetLib/MD5/MD5Parser.cpp

Closes #5378
The Heapbuffer overflow can occur, when *sz already points at the endpointer.
Subsequent call of `AI_MD5_SKIP_SPACES` will try to deref the pointer. This crashes, when *sz is further than the endpointer. This happens exactly then, when *sz == endpointer before the increment.

Fix potential heapbuffer overflow in md5 parsing

---

code/AssetLib/Collada/ColladaLoader.cpp
code/PostProcessing/ValidateDataStructure.cpp
include/assimp/mesh.h

This fixes #5632 by reverting undocumented assumption introduced in 2008.
It does not change API, it just explicitly states that empty slots are possible, after 2008 commits made them impossible without any trace of explanation why.
I understand if you don't want to change 16 years old status quo, there is risk of breaking userspace. But then the assumption about ordering of slots should be documented and fix of #5631 reverted.

Allow empty slots in mTextureCoords

---

code/AssetLib/MDL/MDLMaterialLoader.cpp

This bug was discovered using a fuzz test. With this patch the fuzz test passes.
This is likely not the only issue in this file, but i don't have enough expertise or knowledge to improve this further.

Fix a fuzz test heap buffer overflow in mdl material loader

---

code/AssetLib/FBX/FBXExporter.cpp

The FBX exporter currently only handles one vertex color channel; this pull request changes it to support multiple color channels.
Tested with blender, all color channels are correctly visible as color attributes.

FBX exporter - handle multiple vertex color channels

---

contrib/poly2tri/poly2tri/common/dll_symbol.h

It seems that even with `BUILD_SHARED_LIBS` set to "OFF", this line here emits dlimports: https://github.com/assimp/assimp/blob/48c3a0ec46d2d67ad355b2ab727f503f67d9d7ce/contrib/poly2tri/poly2tri/common/dll_symbol.h#L57
I've added a check to see if BUILD_SHARED_LIBS is ON before defining `P2T_DLL_SYMBOL` as `P2T_COMPILER_DLLIMPORT`, and now for static builds this symbol is correctly undefined.

Fixing static builds on Windows

---

code/AssetLib/USD/USDLoaderImplTinyusdz.cpp

Variable name `TAG` was changed to `Tag` during refactor, broke build on android; this PR reverts the name to fix the problem
Fixes #5714

Revert variable name

---

CMakeLists.txt

The following warning occurs when using cmake to build on Windows.
> assimp\contrib\poly2tri\poly2tri\sweep\sweep.h(1,1): warning C4819: The file contains a character that cannot be represented in the current code page (932). Save the file in Unicode format to prevent data loss
The build will fail because warnings are treated as errors.
The cause of the error is that the following line in `contrib/poly2tri/poly2tri/sweep/sweep.h` contains non-ASCII characters.
https://github.com/assimp/assimp/blob/d95a5c60ef4948f52b5bd25de69a6896394a4660/contrib/poly2tri/poly2tri/sweep/sweep.h#L36
This PR solves the problem by adding `/source-charset:utf-8` to the MSVC compile options.
* [/source-charset](https://learn.microsoft.com/en-us/cpp/build/reference/source-charset-set-source-character-set?view=msv …

Add compile option /source-charset:utf-8 for MSVC

---

include/assimp/scene.h

when blender export fbx then embedded texture path have slash and back slash. so GetShortFilename have to check both types of slashes

Fix to check both types of slashes in GetShortFilename

---

code/Common/SceneCombiner.cpp

When copying a scene, it was checking the *destination* for a NULL pointer instead of the *source*. The copy went ahead despite the source being a NULL pointer, causing random core dumps.

Fix copying private data when source pointer is NULL

---

code/AssetLib/3DS/3DSConverter.cpp
code/AssetLib/COB/COBLoader.cpp
code/AssetLib/FBX/FBXConverter.cpp
code/AssetLib/SMD/SMDLoader.cpp
code/PostProcessing/ValidateDataStructure.cpp

Fixes issue #5748
The documentation says that `aiNode::mChildren == nullptr` when `mNumChildren == 0`.
Verify this is the case in the Scene Validation post-processing step so that unit tests should spot this logic error in the future.
Found and fixed in FBX, 3DS, COB and SMD.
No other cases spotted by the current unit tests.

Zero-length mChildren arrays should be nullptr

---

code/CMakeLists.txt

When using CMake subprojects with an existing build of pugixml this prevents Assimp from using its own copy.
We had symbol collisions with a large, statically-linked application that uses pugixml in several places in the source tree.

Allow usage of pugixml from a superproject

---

code/AssetLib/Ply/PlyParser.cpp
test/unit/utPLYImportExport.cpp

Issue: #5729
Hi, 
this is my take on trying to fix the issue.
Prevents the PLY parser from parsing elements which are already defined.
For example when the following occurs in the header:
```
element vertex 6
property ....
element vertex 8
element vertex 5
```
The crash occurs, when the duplicate vertex is bigger than the previous vertex declaration.
Since I cannot find and document which defines how the file format should behave, I choose to throw an error, preventing from loading the mesh since it is ambigious.
It is also compatible with the preivous fix for this issue.

Prevents PLY from parsing duplicate defined elements

---

code/AssetLib/FBX/FBXConverter.cpp
code/AssetLib/FBX/FBXImportSettings.h
code/AssetLib/FBX/FBXImporter.cpp
include/assimp/config.h.in
test/unit/utFBXImporterExporter.cpp

Add option `AI_CONFIG_IMPORT_FBX_IGNORE_UP_DIRECTION`
Default false
Add unit test for both states of this option
Fixes #5753

Add option to ignore FBX custom axes

---

code/PostProcessing/SortByPTypeProcess.cpp

https://github.com/assimp/assimp/issues/5677
This patch should ensure that the pointers `pFirstFace`are valid and before dereferencing
```
==924513==ERROR: AddressSanitizer: SEGV on unknown address 0x1000fea90623 (pc 0x555556b374c7 bp 0x7fffffffca70 sp 0x7fffffffbba0 T0)
==924513==The signal is caused by a READ memory access.
#0 0x555556b374c7 in Assimp::SortByPTypeProcess::Execute(aiScene*) /root/code/PostProcessing/SortByPTypeProcess.cpp:175:17
#1 0x555556a9afdf in Assimp::BaseProcess::ExecuteOnScene(Assimp::Importer*) /root/code/Common/BaseProcess.cpp:82:9
#2 0x5555558d79b2 in Assimp::Importer::ApplyPostProcessing(unsigned int) /root/code/Common/Importer.cpp:841:22
#3 0x5555558d5321 in Assimp::Importer::ReadFile(char …
```

Fix invalid access

---

code/AssetLib/LWS/LWSLoader.cpp
code/AssetLib/LWS/LWSLoader.h

Stack Overflow (https://github.com/assimp/assimp/issues/5464)
This patch will prevent the stack overflow by limiting the recursion depth.
```
==522887==ERROR: AddressSanitizer: stack-overflow on address 0x7fffff7feff8 (pc 0x7ffff731e9c5 bp 0xfffffffffffffff8 sp 0x7fffff7ff000 T0)
#0 0x7ffff731e9c5  build-llvm/tools/clang/stage2-bins/runtimes/runtimes-bins/compiler-rt/lib/asan/asan_thread.cpp:423:45
#1 0x7ffff72796c8 in Allocate build-llvm/tools/clang/stage2-bins/runtimes/runtimes-bins/compiler-rt/lib/asan/asan_allocator.cpp:578:21
#2 0x7ffff72794c7 in asan_malloc build-llvm/tools/clang/stage2-bins/runtimes/runtimes-bins/compiler-rt/lib/asan/asan_allocator.cpp:1000:34
#3 0x7ffff7311803 in malloc …
```

Fix stack overflow

---

code/AssetLib/FBX/FBXConverter.cpp

This fixes: https://github.com/assimp/assimp/issues/5449 and https://github.com/assimp/assimp/issues/5642 by restoring the absolute transformation calculation which is now required due to this change: https://github.com/assimp/assimp/pull/5349.
The original pull request: https://github.com/assimp/assimp/pull/5643 was not properly merged so I have created this pull request again to hopefully fix this ***critical*** issue in the FBX importer.  Please let me know if there are any concerns and I will address them as soon as possible.

FBX Import - Restored Absolute Transform Calculation

---

include/assimp/material.h

This fixes the issue I encountered stemming from this comment #5779  . As I understand the documentation is generated based on these comments so this would fix the online docs aswell.
As this is just a comment-fix I presume no additional checks need to be performed

Fix naming in aiMaterial comment

---

code/AssetLib/FBX/FBXConverter.cpp
code/AssetLib/FBX/FBXMeshGeometry.cpp

Some blendshapes don't have normal transformations, but Assimp currently requires that normals be present. This removes that, and won't populate the normal field.
Fixes: #5772

FBX Blendshapes: Do not require normals

---

code/PostProcessing/SplitLargeMeshes.cpp

- Fix nullptr access when rootnode of the scene is a nullptr. This can happen even if the scene stores any kind of meshes.
- closes https://github.com/assimp/assimp/issues/5791

SplitLargeMeshes: Fix crash

---

code/AssetLib/FBX/FBXConverter.cpp
code/AssetLib/FBX/FBXConverter.h

Closes #5808
FBX armature PR modified how transforms were obtained in recursive `ConvertNodes()` function; instead of passing reference to 4x4 matrix, an `aiNode` was passed and the transform read from that parameter.  But this broke animations on certain FBX 3D model files.  To fix this, the original approach from the commit just prior to `168ae22` has been restored.
<table>
<tr><th rowspan=2>Model</th><th colspan=2>Assimp commit or PR</th><th rowspan=2>Notes</th></tr>
<tr><th><a href="https://github.com/assimp/assimp/commit/9934a8d1cc58d9c5ddc6e0f39da0f86a7091e63b"><tt>9934a8d</tt></a><br>7 Oct 2024</th><th><a href="https://github.com/assimp/assimp/pull/5813"><tt>PR 5813</tt></a></th></tr>
<tr><td><a href="https://renderpeople.com/sample/free/renderpeople_free_animated_people_FBX.zip"><t …

Fix bug introduced in commit 168ae22 of 27 Oct 2019

---

code/AssetLib/USD/USDLoaderImplTinyusdz.cpp

Closes #5767 
Now we call the `LoadUSDxFromFile` or `LoadUSDxFromMemory` functions depending if the file name is `AI_MEMORYIO_MAGIC_FILENAME`

Fix issue 5767: Can't load USD from memory

---

code/AssetLib/FBX/FBXConverter.cpp

Closes #3390 (FBX animation bug introduced with 24 Mar 2020 commit 14b8d12)
Closes #4487
Closes #5719
(H/T @Frooxius for [isolating the commit where the bug was introduced and suggesting the fix](https://github.com/assimp/assimp/issues/3390#issuecomment-767290559))
Fix: remove conditions for pre- and post-rotation added in commit [`14b8d12`](https://github.com/assimp/assimp/commit/14b8d1242b0f32fef9dd8ace0a1d4e8cbd20d88c):
```
if (comp == TransformationComp_Rotation || comp == TransformationComp_Scaling ||
comp == TransformationComp_Translation ||
comp == TransformationComp_PreRotation || comp == TransformationComp_PostRotation) {
```
to reflect state just prior to that commit:
```
if (comp == TransformationComp_Rotation || comp == TransformationComp_Scaling ||
comp == …
```

Fix FBX animation bug (issue 3390)

---

code/AssetLib/LWO/LWOLoader.cpp

Closes #5823
Normals were inadvertently broken for Lightwave importer (lighting calculations failed and models rendered completely black)
Restore lines removed in commit cb22d53 of 4 May 2023 which caused the breakage

[Fix issue 5823] Hotfix for broken lightwave normals

---

code/Common/DefaultLogger.cpp
include/assimp/DefaultLogger.hpp

assigning s_pNullLogger to the parameter "logger" is definitely wrong. However, custom logger previously set from user must not be deleted. The user itself must handle allocation / deallocation.

Fixed bug in DefaultLogger::set

---

test/unit/utX3DImportExport.cpp

Closes #5829
Add unit tests for keyboard and "chevy" models.  The currently broken importer provides incorrect number of meshes for these models; the tests reflect the _incorrect_ mesh count, with `TODO`s so that when the importer is fixed and the tests begin failing, it will be obvious how to restore working test values

Add unit tests for X3D models which were broken at 5 Oct 2020 commit 3b9d4cf

---

code/Common/Importer.cpp

In all other instances where we set mErrorString inside a catch block we also set mException. I think that this was an oversight.

Store current exception when caught in ASSIMP_CATCH_GLOBAL_EXCEPTIONS

---

code/Common/DefaultIOSystem.cpp

If the stat command fails, statbuf is uninitialized.

Fix use of uninitialized value.

---

include/assimp/material.h

- Mark inlined functions as static inline to fix the linkage for c compilers
- closes https://github.com/assimp/assimp/issues/5875

Material: Fix the build for c compiler

---

contrib/clipper/clipper.cpp

If `PopScanbeam` returns false, `topY` may not have been initialized in this function, which can cause a compiler warning/error:
```
/.../assimp/contrib/clipper/clipper.cpp: In member function ‘virtual bool ClipperLib::Clipper::ExecuteInternal()’:
/.../assimp/contrib/clipper/clipper.cpp:1577:32: error: ‘topY’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
1577 |       if (!ProcessIntersections(topY))
|            ~~~~~~~~~~~~~~~~~~~~^~~~~~
```

Fix potential uninitialized variable in clipper

---

.github/workflows/cd.yml

I needed this for myself, so I thought I'd contribute it as well, it's also been requested in the past, see #4356.
Will automatically build and attach the binaries when a new release is created, see [an example release](https://github.com/Saalvage/assimp/releases/tag/0.0.0.1.0.0) and [an example CI run](https://github.com/Saalvage/assimp/actions/runs/11996636350).
New configurations can easily be added as requested.
Some considerations:
- Due to the way MSVC structures its builds, the windows binary archives contain a "Release" folder in which the actual DLL is found. There's also a .pdb file that is significantly larger than the DLL itself included as well. This may not be desirable, but it makes implementation somewhat easier (honestly just saves an extra step of extracting the file we …

Add CI to automatically build and attach binaries to releases

---

code/Common/Assimp.cpp

Fixes https://github.com/assimp/assimp/issues/5788
This patch sets the `nullptr` value for the DefaultStream pointer each time it is deleted in the `LogToCallbackRedirector` destructor. This prevents the reuse of an invalid pointer (UAF).
ASAN report from the issue for reference:
```
==671866==ERROR: AddressSanitizer: heap-use-after-free on address 0x502000000050 at pc 0x55555586385a bp 0x7fffffffc7e0 sp 0x7fffffffc7d8
READ of size 8 at 0x502000000050 thread T0
#0 0x555555863859 in CallbackToLogRedirector(char const*, char*) /root/code/Common/Assimp.cpp:359:8
#1 0x5555558aab77 in LogToCallbackRedirector::write(char const*) /root/code/Common/Assimp.cpp:150:9
#2 0x55555590a4a9 in Assimp::DefaultLogger::WriteToStreams(char …
```

Fix use after free in the CallbackToLogRedirector

---

Readme.md

There have been no updates to AssimpNet in over two years, which means it is stuck on an old version of Assimp and fails to take advantage of some more modern additions to .NET (namely the built-in math types). I've created a fork of the project that updates it to the latest Assimp release, adds better interop with modern C# and includes ARM64 binaries for MacOS. I'm also looking to maintain this fork for the foreseeable future with bug fixes and updates to the latest Assimp versions.

Replace C# port with maintained fork

---

contrib/openddlparser/code/OpenDDLParser.cpp

Fixes https://github.com/assimp/assimp/issues/5906, https://github.com/assimp/assimp/issues/5787
Use `std::string` instead of `const char*` to log not zero-terminated strings. ASAN report for reference:
```
==266231==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x50200000011f at pc 0x55d3f028a8e9 bp 0x7ffca243ab90 sp 0x7ffca243a358
READ of size 1 at 0x50200000011f thread T0
#0 0x55d3f028a8e8 in strlen (assimp/myfuzzing/prefix/bin/assimp_fuzzer+0xb088e8) (BuildId: 13be78bd51af30c410e9d483a4f94497ad869dad)
#1 0x55d3f0245eb8 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::basic_string<std::allocator<char>>(char const*, std::allocator<char> const&) …
```

Fix heap-buffer-overflow in OpenDDLParser

---

code/AssetLib/MD5/MD5Parser.cpp

Fixes https://github.com/assimp/assimp/issues/5860
Added additional check before dereferencing `buffer` pointer: `buffer < bufferEnd`. ASAN report for reference:
```
==1114==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x5020000001c0 at pc 0x55a54b9156b6 bp 0x7ffd02555350 sp 0x7ffd02555348
READ of size 1 at 0x5020000001c0 thread T0
#0 0x55a54b9156b5 in SkipSpacesAndLineEnd /src/assimp/code/AssetLib/MD5/MD5Parser.h:428:13
#1 0x55a54b9156b5 in SkipSpacesAndLineEnd /src/assimp/code/AssetLib/MD5/MD5Parser.h:450:12
#2 0x55a54b9156b5 in Assimp::MD5::MD5Parser::ParseHeader() /src/assimp/code/AssetLib/MD5/MD5Parser.cpp:128:5
#3 0x55a54b9146e1 in Assimp::MD5::MD5Parser::MD5Parser(char*, unsigned int) …
```

Fix buffer overflow in MD5Parser::SkipSpacesAndLineEnd

---

code/AssetLib/glTF/glTFImporter.cpp
code/AssetLib/glTF2/glTF2Importer.cpp

In build https://github.com/assimp/assimp/actions/runs/12403918024/job/34628244451?pr=5928 I hit some building errors because this strncpy functions were copying using the string length, which would remove the null terminator character. I just added a `+1` to ensure the null character is accounted for.

glTF importers: Avoid strncpy truncating away the ' \0' character

---

fuzz/assimp_fuzzer.cc

Using a logger in the fuzzer generates a large amount of output in the OSS-Fuzz project. For instance, [the latest run](https://oss-fuzz-build-logs.storage.googleapis.com/log-ae10e9c1-7390-4e01-a26d-6533a51a4529.txt) produced approximately 5 GB of output, which is generally not very useful This patch disables logging by default (`_DEBUG` is not set in the OSS-Fuzz environment).

Disable logs for fuzzer by default

---

code/AssetLib/LWS/LWSLoader.cpp

The fuzzing test found this issue. Stack overflow can happen if an LWS file contains LoadObject or LoadObjectLayer command with the same file path as the current file.
OSS-Fuzz log (search by `stack-overflow`): https://oss-fuzz-build-logs.storage.googleapis.com/log-64548938-c33e-4161-9cfd-61fe8f85b562.txt
```
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==81==ERROR: UndefinedBehaviorSanitizer: stack-overflow on address 0x7ffeff60afd8 (pc 0x561aef606873 bp 0x7ffeff60b030 sp 0x7ffeff60afe0 T81)
#0 0x561aef606873 in Assimp::FileSystemFilter::Open(char const*, char const*) /src/assimp/code/Common/FileSystemFilter.h:132:33
#1 0x561aef606875 in Assimp::FileSystemFilter::Open(char const*, char const*) /src/assimp/code/Common/FileSystemFilter.h:132:33
#2 0x561aef606875 in …
```

Fix stack overflow in LWS loader

---

contrib/poly2tri/poly2tri/common/shapes.h

Added additional check if it is MSVC, because g++ will raise "unknown-pragmas" warning when used on windows, which will stop build process if warnings are treated as errors. Additionally, intel compiler is excluded since it also defines __MSC_VER, but doesn't support #pragma warning(...) syntax.
One thing to note is that clang also defines _MSC_VER, but I can't find if it has support for MSVC #pragma warning(...), and if yes, which versions of clang support it. Currently, I don't have clang, so I can't directly test this.

pragma warning bug fix when using g++ on windows

---

code/Common/material.cpp

In pull request #5101, user @Sanchikuuus added MayaTextures from the FBX Converter as a valid AiTextureType.
These same AiTextureTypes were not added to the material.cpp file which would result in 'Bug' string outputs when investigating Maya-exported FBXs.
Noticed whilst doing a code read-through.

Updated Material.cpp to Add Missing Texture Types to String

---

Dockerfile
test/unit/utMetadata.cpp

- Copy source from local folder instead of checkit it out
- Use gcc image
- Directly run unittests

Docker: Optimize usage

---

fuzz/assimp_fuzzer.cc

This is a continuation of https://github.com/assimp/assimp/pull/5944#issuecomment-2572952400
The current fuzzer calls `Exporter::ExportToBlob` right after `Importer::ReadFileFromMemory`, which is invoked with the flag `aiProcessPreset_TargetRealtime_Quality`. This flag doesn't include the `aiProcess_ValidateDataStructure` value, which means that aiScene::mRootNode might be NULL. At least, this is what I can conclude after reading the code and documentation.
```
ai_assert failure in /src/assimp/code/Common/SceneCombiner.cpp(1293): nullptr != src
==74== ERROR: libFuzzer: deadly signal
#0 0x56323fdc6b34 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/ubsan/ubsan_diag_standalone.cpp:31:3
#1 0x56323fd45b88 in fuzzer::PrintStackTrace() …
```

Add aiProcess_ValidateDataStructure flag to the fuzzer

---

code/AssetLib/glTF2/glTF2Asset.h
code/AssetLib/glTF2/glTF2Asset.inl
code/AssetLib/glTF2/glTF2AssetWriter.h
code/AssetLib/glTF2/glTF2AssetWriter.inl
code/AssetLib/glTF2/glTF2Exporter.cpp
code/AssetLib/glTF2/glTF2Exporter.h
code/AssetLib/glTF2/glTF2Importer.cpp
include/assimp/material.h
test/unit/utMaterialSystem.cpp

This adds the Extension according to https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_anisotropy/README.md
It also adds an new Texture Type and Material Key into the core Material definitions.

Added GLTF Extension KHR_materials_anisotropy

---

port/PyAssimp/pyassimp/postprocess.py
port/PyAssimp/pyassimp/structs.py

QuatKey and Bone structures are missing certain fields, thus causing corruptions such as grabbing rotation frame data for animations. I have also included the "aiProcess_PopulateArmatureData" bit flag as it was missing from the current PyAssimp distribution.

Fixing PyAssimp misalignment errors with certain structures

---

code/AssetLib/OpenGEX/OpenGEXImporter.cpp

This patch fixes the memory leak in OpenGEXImporter
In OpenGEXIImporter. cpp, OpenGEXIImporter: The file in the InternReadFile function is the IOStream object generated by new, but pIOHandler ->Close (file); Not necessarily deleting files requires manual deletion of files;, Otherwise, there may be memory leaks. Use std:: Unique_ptr<IOStream>Automatically manages file streams to ensure that files are automatically released at the end of the function
==22910==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 40 byte(s) in 1 object(s) allocated from:
#0 0x7fc3a60ead30 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0xead30)
#1 0x5136e9 in Assimp::Intern::AllocateFromAssimpHeap::operator new(unsigned long) …

Fix memory leak in OpenGEXImporter

---

code/Common/SceneCombiner.cpp
contrib/Open3DGC/o3dgcCommon.h
contrib/Open3DGC/o3dgcIndexedFaceSet.h
contrib/Open3DGC/o3dgcSC3DMCEncodeParams.h
contrib/Open3DGC/o3dgcTimer.h

Addresses https://github.com/assimp/assimp/issues/5908. Tested locally using 20.1.0 RC.
@danoli3 
----
@kimkulling The error message suggests casting to void, but I really don't know it is correct fix.

Use std::copy to copy array and remove user destructor to make sure is_trivially_copyable in order to avoid -Wno-error=nontrivial-memcall

---

code/AssetLib/OpenGEX/OpenGEXImporter.cpp

- will set alpha channel to 1.0f, if no alpha channel was found.
- closes https://github.com/assimp/assimp/issues/6039

Fix: Let OpenGEX accept color3 types

---

code/AssetLib/glTF/glTFImporter.cpp

Potential fix for [https://github.com/assimp/assimp/security/code-scanning/63](https://github.com/assimp/assimp/security/code-scanning/63)
To fix the potential use-after-free error, we should set the `mMaterials` pointer to `nullptr` immediately after deleting it. This ensures that any accidental access to `mMaterials` after it has been freed will be caught as a null pointer dereference, which is easier to debug and less dangerous than a use-after-free error.
- Modify the code in the `ImportMaterials` method of the `glTFImporter` class.
- After the `delete[] mScene->mMaterials;` statement on line 155, set `mScene->mMaterials` to `nullptr`.
- This change ensures that any accidental access to `mMaterials` after it has been freed will result in a null pointer dereference.
_Suggested fixes …

Potential fix for code scanning alert no. 63: Potential use after free

---

code/AssetLib/OpenGEX/OpenGEXImporter.cpp

Fixes #6043 
Disable partially implemented light import which is causing model load failure
With this fix, at least bundled [`collada.ogex`](https://github.com/assimp/assimp/blob/master/test/models/OpenGEX/collada.ogex) model able to successfully load (note that this model file contains multiple light and camera nodes/objects)

[OpenGEX] disable partial implementation of light import (causes model load failure)

---

code/AssetLib/C4D/C4DImporter.cpp

#5623 broke the Cinema4D import by forgetting to rename a constant. This commit fixes the invalid name.

Fix Cinema4D Import

---

code/AssetLib/OpenGEX/OpenGEXImporter.h
code/PostProcessing/EmbedTexturesProcess.h
code/PostProcessing/RemoveVCProcess.h
code/PostProcessing/ScaleProcess.h
code/PostProcessing/SplitByBoneCountProcess.h
include/assimp/ZipArchiveIOSystem.h
test/unit/utImporter.cpp

The `override` keyword only applies to virtual functions. Specifying `virtual` again is useless.

Remove Redundant `virtual`

---

include/assimp/scene.h

Renamed and inlined `hasSkeletons()` to `HasSkeletons()` to match the other `Has*()` methods
Added comments to the method.

Renamed and inlined hasSkeletons() to HasSkeletons() for API consistency

---

code/AssetLib/Ply/PlyExporter.cpp
code/AssetLib/Ply/PlyExporter.h

- If the mesh supports more than 2 texture coordinates this was not handled correctly. Now the code will be able to deal with 2 or 3 coords and throws an exception if this value gets invalid.
- closes https://github.com/assimp/assimp/issues/3829

Bugfix: Handling no of texture coordinates correctly

---

code/Common/BaseImporter.cpp

Fixes #6027
Before this PR, only 1 path got checked. The `ConvertToUTF8` did, in case of an error, just return without any error handling and just aborted the conversion.
This PR adds error handling, in case invalid utf32/16 got detected. This will prevent further processing of the data. Currently, the (un-converted) data gets parsed. I am not sure if there is a valid case where it should be possible that the unconverted data should be parsed. I doubt there is, therefore the exceptions.

fix: possible Heap-based Buffer Overflow in ConvertToUTF8 function

---

include/assimp/ParsingUtils.h

In the while loop, when `!IsLineEnd(*buffer)` is true, eventually `*_out++=*buffer++;` writes the last byte before `end` and sets `_out` to `end`. In the current implementation if end is `_out + BufferSize`, the next line `*out = (char_t)'\0';` writes out of bounds of `out[BufferSize]`. This change prevents this out of bounds error by setting `end `one byte before to preserve a byte for writing the trailing `'\0'` byte.

Fix a out of bound buffer access in ParsingUtils GetNextLine

---

code/AssetLib/Ply/PlyParser.cpp

Currently when there isn't any `' '` character inside `pOut->szName`, pos will be `std::string::npos` according to [`find_last_of` documentation](https://en.cppreference.com/w/cpp/string/basic_string/find_last_of). Calling `erase` with  `std::string::npos` throws according to [`erase` documentation](https://en.cppreference.com/w/cpp/string/basic_string/erase).
This PR adds a check before calling erase.

Fix a bug where string erases throws out of range

---

code/AssetLib/glTF2/glTF2Asset.inl

Currently, when importing a glb file with a KTX2 image, the texture object is not recognized.

+ Only the recognition of KTX2 compressed images as texture objects within the glb model is currently handled.

---

cmake-modules/HunterGate.cmake

Looks like docs.hunter.sh is outdated and redirects to some dude's personal blog now which seems totally unrelated.

Fix HUNTER_ERROR_PAGE

---

code/AssetLib/CSM/CSMLoader.cpp

Closes #6012 
description:
issue:
- https://github.com/assimp/assimp/blob/4ad1d2aa3086517816716a50aa122342806736f9/code/AssetLib/CSM/CSMLoader.cpp#L274C1-L275C1
- sometimes the code tried to construct a new 4x4 matrix from a nullptr, thus reading out of bounds
fix:
- added nullptr check
- added array count check
- added default fallback init to identity matrix
fuzz output after fixing:
> sh /home/ubuntu/assimp/test_exploits/CVE-2025-2751.sh
> -- Shared libraries disabled
> -- GCC13 detected disabling "-Wdangling-reference" in Cpp files as it appears to be a false positive
> -- compiling zlib from sources
> -- GCC13 detected disabling "-Warray-bounds and -Wstringop-overflow" for AssetLib/MDL/MDLLoader.cpp as it appears to be a false positive
> -- VRML disabled
> -- tinyusdz disabled
> -- …

Fixes CVE-2025-2751: Out-of-bounds Read in Assimp::CSMImporter::InternReadFile (closes #6012)

---

code/AssetLib/X3D/X3DGeoHelper.cpp

- Check if std::vector is empty before accessing its back
- closes https://github.com/assimp/assimp/issues/6279

X3D: Fix invalid vector::back usage

---

code/AssetLib/AC/ACLoader.cpp
test/models/AC/doubleSidedFace.ac
test/unit/utACImportExport.cpp

The AC format marks double-sided SURF elements with the 0x20 flag, which Assimp ignored. This commit adds support for double-sided faces.
On encountering a double-sided face via the flag mentioned above, the front face is generated as usual but is then duplicated. The winding order of the duplicate is flipped to form a back face. Vertices are duplicated too so that back faces work correctly with normal vector generation and face smoothing.

AC: Support Double-Sided Faces

---

contrib/openddlparser/code/OpenDDLParser.cpp

Fix a `container-overflow` error in `ODDLParser::OpenDDLParser::parseIntegerLiteral` by swapping the order of conditions in a while loop to ensure the end-of-buffer check happens before dereferencing the pointer. This prevents reading past the end of the buffer when lookForNextToken returns the end pointer.
https://oss-fuzz.com/testcase-detail/4980126616780800
https://issues.oss-fuzz.com/issues/42527625

Fixed a `container-overflow` error

---

code/PostProcessing/SortByPTypeProcess.cpp

The process incorrectly deleted original meshes from the scene when cleaning up after an error if those meshes had been added to its output list (`outMeshes`).
The fix ensures proper ownership transfer by nullifying the original mesh pointer in the scene (`pScene->mMeshes[i] = nullptr;`) when the mesh is moved to outMeshes. This prevents the scene destructor from attempting to delete the mesh again later, while allowing the error cleanup path in `SortByPTypeProcess` to correctly delete all meshes it owns (both newly created and transferred originals).

Fixed a `heap-use-after-free` in `SortByPTypeProcess`.

---

test/unit/utProfiler.cpp

Upcoming `gcc-16` improved detection of unused variables as:
test/unit/utProfiler.cpp: In member function 'virtual void utProfiler_addRegion_success_Test::TestBody()':
test/unit/utProfiler.cpp:71:22: error: variable 'j' set but not used [-Werror=unused-but-set-variable=]
71 |         volatile int j=0;
|                      ^
The change is intentional accoring to Andrew Pinski and is not a faalse positive.

test/unit/utProfiler.cpp: fix `gcc-16` build failure

---

code/AssetLib/Blender/BlenderTessellator.cpp

The code already disables the warning on clang. It's also caused on GCC in some circumstances (particularly when building with `-D_GLIBCXX_DEBUG`).

Fix an invalid offsetof warning-as-error
