contrib/poly2tri/poly2tri/sweep/sweep_context.cc
contrib/poly2tri/poly2tri/sweep/sweep_context.h

Revert "Fix warnings under Visual Studio 12"

---

.gitignore
code/3DSLoader.cpp
code/LWOBLoader.cpp
code/LWOLoader.cpp
code/OFFLoader.cpp
code/PlyLoader.cpp
code/STLLoader.cpp
code/XFileParser.cpp

Fixes assorted bugs found with afl http://lcamtuf.coredump.cx/afl/
Do not merge without review. Not regression tested since it doesn't run very well on Linux. Also there's some doubt about what we should do on corrupted input. Try to continue or just give up immediately?
Also there are many more, this is just the first batch.

Fix some bugs found with afl

---

test/regression/gen_db.py
test/regression/run.py
test/regression/utils.py

Regression suite: 2.7 compatibility, force user to specify assimp binary, stable test order.

---

code/3DSConverter.cpp
code/ACLoader.cpp
code/CalcTangentsProcess.cpp
code/FindDegenerates.cpp
code/FindInvalidDataProcess.cpp
code/GenVertexNormalsProcess.cpp
code/ImproveCacheLocality.cpp
code/LWOFileData.h
code/LWOLoader.cpp
code/MD2Loader.cpp
code/NFFLoader.cpp
code/OptimizeMeshes.cpp
code/PlyParser.cpp
code/Q3DLoader.cpp
code/RemoveVCProcess.cpp
code/SortByPTypeProcess.cpp
code/StringComparison.h
code/TerragenLoader.cpp

clang warns: 'register' storage class specifier is deprecated
http://stackoverflow.com/questions/10675072/is-the-register-keyword-still-used

remove "register" keyword:

---

code/SmoothingGroups.inl

remove remaining "register" keyword.
thanks turol!

addition to c4997f16dba72ab82dd4cb0374459b98d7b33a63 (#476)

---

code/ColladaHelper.h
code/ColladaLoader.cpp
code/ColladaParser.cpp

Use material names, it more informative than id
Set default direction to UP_Y, like in specification

Use material names, set default direction to UP_Y, process extra tag

---

port/jassimp/jassimp-native/Android.mk
port/jassimp/jassimp-native/src/jassimp.cpp

(crashes if the model has a lot of meshes...)

no one ever tried this java stuff???

---

.travis.yml

elif added for future use (maybe someone like to split windows and linux build or test cases too)

maybe Fixes assimp/assimp#516

---

port/jassimp/jassimp-native/src/jassimp.cpp
port/jassimp/jassimp-native/src/jassimp.h
port/jassimp/jassimp/src/jassimp/AiMesh.java
port/jassimp/jassimp/src/jassimp/AiNodeAnim.java
port/jassimp/jassimp/src/jassimp/Jassimp.java

added getter for other structs too and make results as "global constants".

Fix java final (afterparty)

---

.travis.yml

and install deb-packages for MinGW + sample apps (for future use).
travis documentation also mentioned install packages in before_install: 
http://docs.travis-ci.com/user/installing-dependencies/
important NOTE: don't put android ndk fetch+extraction onto before_install step then this can produce travis boot-loop!!!
~~ps: can be merged, don't think that it breaks something.~~

catch apt-get problem for wine install 

---

.travis.yml
cmake-modules/MinGW_x86_64.cmake

try to add the travis WINDOWS-build a sense.
i personally not working on any google-code so tests are disabled here, just have some plans to build wine runtime tests later.

Travis mingw

---

test/unit/utImporter.cpp

fix the test utImporter, the file path was wrong

test fail, fix file path

---

code/3DSExporter.cpp
code/FBXParser.cpp
code/IFCCurve.cpp
code/IFCLoader.cpp
code/IFCProfile.cpp
code/OpenGEXImporter.cpp
code/OptimizeMeshes.h
code/PlyExporter.cpp
code/PlyExporter.h
code/STEPFileReader.cpp
code/STLExporter.cpp
code/STLExporter.h
code/StepExporter.cpp
code/XFileExporter.cpp

Fix a bunch of compiler warnings issued by clang.

Fix compiler warnings

---

code/BaseImporter.cpp
code/ColladaExporter.h
code/ColladaHelper.h
code/ColladaLoader.cpp
code/FindInvalidDataProcess.cpp
code/OptimizeGraph.cpp
code/OptimizeMeshes.cpp

- add missing initialization of several class/struct members
- prefer check for empty() over check for size() in OptimizeGraph (empty() is guaranteed to be constant time, size() is not)

Fix inits and a couple of empty checks

---

code/OptimizeMeshes.cpp

One of the two branches should have been rebased before merging since they both touch the same code...

Fix overlapping merges

---

code/ColladaExporter.cpp
code/ColladaExporter.h
code/ColladaLoader.cpp
include/assimp/defs.h
test/CMakeLists.txt
test/models/Collada/cameras.dae
test/models/Collada/lights.dae
test/unit/utColladaExportCamera.cpp
test/unit/utColladaExportLight.cpp

add the ability to export light and camera object in a collada file

Collada export light and camera

---

code/ColladaExporter.cpp
code/ColladaLoader.cpp
code/ColladaLoader.h
code/ComputeUVMappingProcess.cpp
code/FixNormalsStep.cpp
code/ImproveCacheLocality.cpp
code/RemoveVCProcess.cpp
code/SortByPTypeProcess.cpp
code/TextureTransform.cpp
code/ValidateDataStructure.cpp
include/assimp/Exporter.hpp

- add initializers to classes
- fix %i/%u for unsigned ints
- remove unused vars
- pass by reference

Code Cleanups

---

code/3DSConverter.cpp
code/ASEParser.cpp
code/DeboneProcess.cpp
code/DefaultLogger.cpp
code/IRRLoader.cpp
code/LWOLoader.cpp
code/LWSLoader.cpp
code/LimitBoneWeightsProcess.cpp
code/MD3Loader.cpp
code/MD5Parser.cpp
code/MDLLoader.cpp
code/MS3DLoader.cpp
code/NFFLoader.cpp
code/ObjExporter.cpp
code/ObjFileParser.h
code/OgreImporter.h
code/OgreMaterial.cpp
code/OpenGEXImporter.cpp
code/OptimizeGraph.cpp
code/OptimizeMeshes.cpp
code/PretransformVertices.cpp
code/RemoveRedundantMaterials.cpp
code/SMDLoader.cpp
code/StepExporter.cpp
code/UnrealLoader.cpp

Now with the correct commits :)
I did several small code improvements based on a cppcheck result (cppcheck is a static code analyzer). The changes are minimal to prevent any breaking changes. 
For example:
- Usage of pre-inrement in loop instead of post-increment
- Use of correct printf format string
- Usage of .empty() instead of .size() in if statements
- Usage const reference parameter
- Added private constructor for class that should not be copied

Several minor improvements based on cppcheck

---

samples/SimpleOpenGL/Sample_SimpleOpenGL.c

Knows where to look for glut.h on Mac with Clang compilers (command-line compilers under current XCode).

Builds out of the box on mac with ASSIMP_BUILD_SAMPLES turned on.

---

code/ACLoader.cpp
code/MD3Loader.cpp
code/MDLLoader.cpp
code/ObjFileImporter.cpp
code/STLLoader.cpp
include/assimp/defs.h

Fix some random crash bugs which might or might not be in #454.
Add my standard disclaimer about review, regression test etc.
Also it would probably be useful to abstract out that memory allocation check pattern in the last commit. Thoughts?

Random crash fixes

---

port/PyAssimp/pyassimp/core.py
port/PyAssimp/pyassimp/helper.py

if you don't have numpy installed, pyassimp will substitute local operations on raw python lists and allow you to manage data types through another interface.
note: I am not an expert at python, so be aware, there's likely better (faster) ways of doing things.

Added auto-detection of numpy

---

code/ObjFileImporter.cpp
code/ObjFileParser.cpp

Before patch:
```
MyIOStream(assets/raw/models/test_model/test_model.obj)
MyIOStream(test_model.mtl)
```
After patch:
```
MyIOStream(assets/raw/models/test_model/test_model.obj)
MyIOStream(assets/raw/models/test_model/test_model.mtl)
```
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/assimp/assimp/672)

Properly build path to the mtl file when loading obj

---

code/OFFLoader.cpp

A new and better version of #488. This one actually works. I think.
I'll add the testcase in a separate PR to avoid messing with the automatic checks.

Fix OFFLoader to better handle certain malformed files

---

INSTALL

Added actual instructions rather than telling people to go read about where to find the instructions to read. Note that simple Windows instructions should be added as well.

Unix build instructions

---

code/Bitmap.cpp
contrib/clipper/clipper.cpp
contrib/clipper/clipper.hpp
tools/assimp_cmd/CompareDump.cpp

some fixes from the debian packaging

Debian fixes 3.2

---

port/jassimp/jassimp/src/jassimp/AiLightType.java

Jassimp throws IllegalArgumentException without the fix.

Add new light type 'ambient' to match light.h

---

code/ColladaParser.cpp

Fix for https://github.com/assimp/assimp/issues/234

instance_image support for sample2D in Collada 1.5

---

include/assimp/mesh.h
include/assimp/scene.h
tools/assimp_cmd/Main.cpp

Just a few small documentation/message improvements.

Tiny misc fixes for documentation

---

code/ObjFileImporter.cpp
code/ObjFileParser.cpp
code/ObjFileParser.h

There are two stages to this:
1) Processing '\'s - this accounts for 1/3rd of the file import progress.
2) Parsing the file data - this accounts for the other 2/3rds.

ObjImporter: Added better progress reporting during file import.

---

code/ObjFileImporter.cpp
code/ObjFileParser.cpp
code/ObjFileParser.h
code/ObjTools.h

Revert "Fix issue: OBJ import takes forever (#759)"

---

code/BlenderLoader.cpp
code/BlenderScene.cpp
code/BlenderScene.h

This will populate aiCamera with real values. I am still not sure, how to get mAspect from Blender.

Import mClipPlane{Near,Far} and mHorizontalFOV from Blender.

---

code/ObjFileImporter.cpp
code/ObjFileParser.cpp
code/ObjFileParser.h
code/ObjTools.h

OK, fixed the order of evaluation bug, hopefully there are no more.

Fix issue: OBJ import takes forever (#759) (attempt 2)

---

code/ObjFileImporter.cpp
code/ObjFileParser.cpp
code/ObjFileParser.h
code/ObjTools.h

Revert "Fix issue: OBJ import takes forever (#759) (attempt 2)"

---

code/LWOAnimation.cpp

Don't merge yet, I want to see what travis thinks of it.

LWO: Fix division by zero

---

code/SIBImporter.cpp

The validator requires empty scenes to explicitly have NULL pointers.

Validation fix for empty SIB scenes.

---

include/assimp/matrix3x3.inl
test/CMakeLists.txt
test/unit/utMatrix3x3.cpp

The special case of the algorithm is buggy. I've added a test which covers the bug. I've also added a random sample test to check the other case.

Fix special case in aiMatrix3x3t::FromToMatrix.

---

code/MD2Loader.cpp
code/MD3Loader.cpp
code/MDLLoader.cpp

Fix various crashes from #454.

Fix some crashes on malformed input

---

CMakeLists.txt
code/AssbinExporter.cpp
code/AssbinLoader.cpp
code/DefaultIOStream.cpp
code/JoinVerticesProcess.cpp
code/LWOMaterial.cpp
code/STEPFile.h
code/SpatialSort.cpp
tools/assimp_cmd/WriteDumb.cpp

Removed usage of Boost static assert.

---

contrib/poly2tri/poly2tri/common/utils.h
contrib/poly2tri/poly2tri/sweep/sweep.cc

Hi @kimkulling !
This pullrequest should fix the remaining compile errors with MinGW-w64 described in https://github.com/assimp/assimp/issues/855.
Vielen Dank :)
Squareys (Jonathan Hale, University of Konstanz)

Add definition for PI and PI_2

---

contrib/poly2tri/poly2tri/sweep/sweep.cc

Hi @kimkulling !
Sorry again, here is the fix for the error in pullrequest #859. 
Grüße,
Jonathan.

Fix Mistake in last Pullrequest

---

port/PyAssimp/pyassimp/helper.py

otherwise this breaks for no reason if /usr/local/lib is missing.

only check a library folder if it actually exists

---

code/3DSLoader.cpp
code/ASELoader.cpp
code/ColladaLoader.cpp
code/D3MFOpcPackage.cpp
code/FBXConverter.cpp
code/FBXDocument.cpp
code/IRRLoader.cpp
code/LWOLoader.cpp
code/LWOMaterial.cpp
code/MD5Parser.cpp
code/NFFLoader.cpp
code/OgreBinarySerializer.cpp
code/OgreStructs.cpp
code/OgreXmlSerializer.cpp
code/OpenGEXImporter.cpp
code/Q3BSPFileImporter.cpp
code/Q3BSPZipArchive.cpp
code/RawLoader.cpp
code/SplitLargeMeshes.cpp
code/UnrealLoader.cpp

Used clang-modernizer to refactor some for loops and then cleaned up by hand. These are only those which the modernizer considers "safe".

Use C++11 range-based for loops

---

include/assimp/color4.h
include/assimp/matrix3x3.h
include/assimp/matrix4x4.h
include/assimp/vector2.h
include/assimp/vector3.h
test/regression/run.py

anonymous structs are a gnu-extension.

Closes issue888: fix compiler warnings for using a gnu-extension

---

doc/dox_cmd.h

to match the actual code in tools/assimp_cmd/Main.cpp

fix long option name for --om

---

contrib/rapidjson/include/rapidjson/allocators.h
contrib/rapidjson/include/rapidjson/document.h
contrib/rapidjson/include/rapidjson/encodedstream.h
contrib/rapidjson/include/rapidjson/filewritestream.h
contrib/rapidjson/include/rapidjson/internal/biginteger.h
contrib/rapidjson/include/rapidjson/internal/diyfp.h
contrib/rapidjson/include/rapidjson/internal/dtoa.h
contrib/rapidjson/include/rapidjson/internal/ieee754.h
contrib/rapidjson/include/rapidjson/internal/stack.h
contrib/rapidjson/include/rapidjson/internal/strtod.h
contrib/rapidjson/include/rapidjson/rapidjson.h
contrib/rapidjson/include/rapidjson/reader.h
contrib/rapidjson/include/rapidjson/writer.h
contrib/rapidjson/license.txt
contrib/rapidjson/readme.md

This version will fix build issues on several ios-versions.

Update rapidjson to v1.0.2

---

code/FBXConverter.cpp
code/FBXDocument.h
code/FBXMaterial.cpp

1. Storing all the layered textures and blend mode.
2. Some of the FBX files has "SpecularFactor" with specular texture, adding support for that.

adding support to store all the layered textures

---

code/BlenderScene.cpp
code/FBXConverter.cpp
code/HMPLoader.cpp
code/IRRLoader.cpp
code/IRRMeshLoader.cpp
code/LWOLoader.cpp
code/MDLLoader.cpp
code/MDLMaterialLoader.cpp
code/MakeVerboseFormat.cpp
code/NDOLoader.cpp
code/SMDLoader.cpp
code/XFileExporter.cpp
code/XFileExporter.h
include/assimp/metadata.h
test/unit/utBlenderIntermediate.cpp
test/unit/utCoverityTest.cpp

Hi
I try to solve some defect detected by the coverity service, please merge this patch for see if I remove it.
Thanks

Coverity scan fix

---

code/MDLLoader.cpp
code/SMDLoader.cpp

I fixed 2 new defect that I add with the previous pull request

153083/2 Buffer not null terminated

---

code/CMakeLists.txt
code/ImporterRegistry.cpp
code/StandardShapes.cpp
code/X3DImporter.cpp
code/X3DImporter.hpp
code/X3DImporter_Geometry2D.cpp
code/X3DImporter_Geometry3D.cpp
code/X3DImporter_Group.cpp
code/X3DImporter_Light.cpp
code/X3DImporter_Macro.hpp
code/X3DImporter_Metadata.cpp
code/X3DImporter_Networking.cpp
code/X3DImporter_Node.hpp
code/X3DImporter_Postprocess.cpp
code/X3DImporter_Rendering.cpp
code/X3DImporter_Shape.cpp
code/X3DImporter_Texturing.cpp

Importer for X3D files. With some limitations: see source code X3DImporter.hpp.
Yes, also have example models. I will add it with different pull-request.

Import x3d

---

code/AssxmlExporter.cpp
code/BlenderLoader.cpp
code/CalcTangentsProcess.cpp
code/ColladaLoader.cpp
code/ComputeUVMappingProcess.cpp
code/FixNormalsStep.cpp
code/LWOAnimation.cpp
code/LWOMaterial.cpp
code/MD3FileData.h
code/SIBImporter.cpp
code/X3DImporter.cpp
code/X3DImporter_Geometry2D.cpp
code/XGLLoader.cpp
include/assimp/matrix4x4.inl
include/assimp/types.h

I've used a script to find them, I hope I didn't miss any.
Thanks! :)

use cmath and C++ (std::) versions of math functions

---

code/3DSExporter.cpp

... when you have disabled the 3ds importer

Fixes compile issue for 3ds exporter

---

code/3DSHelper.h
code/3DSLoader.cpp
code/AMFImporter_Postprocess.cpp
code/ASEParser.cpp
code/ColladaExporter.cpp
code/ColladaLoader.cpp
code/ColladaParser.cpp
code/ComputeUVMappingProcess.cpp
code/GenVertexNormalsProcess.cpp
code/IRRLoader.cpp
code/IRRLoader.h
code/LWOMaterial.cpp
code/MD3FileData.h
code/MDCLoader.cpp
code/OFFLoader.cpp
code/ObjFileData.h
code/OgreMaterial.cpp
code/PretransformVertices.cpp
code/ProcessHelper.cpp
code/SIBImporter.cpp
code/STLLoader.cpp
code/SkeletonMeshBuilder.cpp
code/StandardShapes.cpp
contrib/Open3DGC/o3dgcCommon.h

Fix lots of compiler warnings related to conversions between float and double related to configured precision.

Fix compiler warnings related to issue 957.

---

include/assimp/Importer.hpp
test/CMakeLists.txt
test/unit/AbstractImportExportBase.cpp
test/unit/AbstractImportExportBase.h
test/unit/SceneDiffer.cpp
test/unit/SceneDiffer.h
test/unit/TestIOSystem.h
test/unit/TestModelFactory.h
test/unit/utObjImportExport.cpp
test/unit/utXImporterExporter.cpp

- New concept for importer unittests
- New test fixure for x-files

New tests for importers.

---

Readme.md

Readme: let readme stats looking more cleaner.

---

code/ObjFileImporter.cpp
code/ObjFileImporter.h

OBJ, added the index to handle clamp option for each cubemap texture

---

code/AMFImporter.cpp
code/ASEParser.cpp
code/LWOMaterial.cpp
code/SMDLoader.cpp
code/SpatialSort.cpp
code/X3DImporter.hpp
code/X3DImporter_Geometry3D.cpp
code/X3DImporter_Node.hpp
contrib/clipper/clipper.cpp
contrib/clipper/clipper.hpp
include/assimp/defs.h
include/assimp/matrix3x3.h
include/assimp/matrix3x3.inl
include/assimp/matrix4x4.inl

As above. All changes made are in comments, so no working code has been changed in this pull request.

Cleared majority of codepage warnings in Visual Studio 2015.

---

code/ObjExporter.cpp
code/ObjFileData.h
code/ObjFileImporter.cpp
code/ObjFileMtlImporter.cpp
test/CMakeLists.txt

These parameters specify the index of refraction and the transmission of a material as described in the [documentation](http://paulbourke.net/dataformats/mtl/).

Added support for parameters Ni and Tf in OBJ/MTL file format.

---

include/assimp/anim.h

Affects Collada files with morph Controller Elements.

Fix memory leak in Collada importer

---

code/DefaultIOStream.cpp

On my FreeBSD/amd64 12.0-CURRENT machine, I need to modify only 1 line to compile.

fix for FreeBSD

---

code/D3MFImporter.cpp
test/CMakeLists.txt
test/unit/utD3MFImportExport.cpp

verbose format flag for import.

Closes https://github.com/assimp/assimp/issues/1128: do not use non

---

code/SIBImporter.cpp

A bug wrt. handling of unconnected edges would create occasional faceted normals in SIB models.

Fix for faceted normals in SIB files

---

port/PyAssimp/pyassimp/core.py

closes https://github.com/assimp/assimp/issues/1211: defensice handling

---

code/glTFAsset.h

Added ComponentType Unsigned int and Error handling

---

code/CMakeLists.txt
port/PyAssimp/pyassimp/helper.py
port/PyAssimp/scripts/3d_viewer.py
port/PyAssimp/setup.py

- Modifying setup.py and helper.py to be able to install the assimp python wrapping inside a virtual environment
- Adding a fallback on shader version 120 when version 130 could not be compiled in 3d_viewer.py
I wrote an email about these two issues https://sourceforge.net/p/assimp/mailman/message/35775932/ . Feel free to answer and/or validate my pull request :-)

Python wrapping improvements

---

code/glTFExporter.cpp

The goal here is to fix https://github.com/assimp/assimp/issues/1164.
The strategy is to basically stretch the shorter arrays to match the length of the larger arrays. So if [1, 2, 3] needs to be stretched to length 8 it will become [1, 1, 1, 2, 2, 2, 3, 3]. Though this could blow up the size of the exported GLTF, it does seem to be a requirement for all the accessors to have the same length.
(According to https://github.com/KhronosGroup/glTF/tree/master/specification/1.0#animations, "All parameters must have the same number of elements.")

GLTF exporter: ensure animation accessors have same count

---

code/glTFExporter.cpp

Since time values in GLTF are measured in seconds:
https://github.com/KhronosGroup/glTF/tree/master/specification/1.0#samplerinput-white_check_mark
and time values in assimp are measured in ticks (I think, though I didn't see this explicitly in the documentation), conversion is necessary.

GLTF exporter: convert animation time from ticks to seconds

---

code/RemoveVCProcess.cpp
test/CMakeLists.txt
test/unit/utRemoveVCProcess.cpp

Instead of delete delete [] must be used.

closes https://github.com/assimp/assimp/issues/1266: fix wrong delete

---

code/OpenGEXImporter.cpp
code/OpenGEXImporter.h
test/CMakeLists.txt
test/models/OpenGEX/light_issue1262.ogex
test/unit/utOpenGEXImportExport.cpp
test/unit/utRemoveVCProcess.cpp

Problem was caused by a not created light source. At the moment the light will be generated when the lightnode to describe the position and orientation of the light-object. In this case no light node was there and no light was generated. When trying to access this not generated light object via pointer a crash occurred.

closes https://github.com/assimp/assimp/issues/1262: fix .

---

code/ObjFileParser.cpp
code/fast_atof.h

Logs an error instead of throwing an exception, which will break the import.

closes https://github.com/assimp/assimp/issues/1244: log error for

---

code/PlyExporter.h
test/unit/utPLYImportExport.cpp

We need to test the exporter as well. SO this pull request will set this up.

ply-exporter: add unittest.

---

code/3DSExporter.cpp
code/AMFImporter_Postprocess.cpp
code/AssimpCExport.cpp
code/BlenderModifier.cpp
code/CMakeLists.txt
code/ColladaExporter.cpp
code/Exporter.cpp
code/IRRLoader.cpp
code/IRRLoader.h
code/LWSLoader.cpp
code/LWSLoader.h
code/MD3Loader.cpp
code/OptimizeGraph.cpp
code/OptimizeMeshes.cpp
code/PretransformVertices.cpp
code/SceneCombiner.cpp
code/StepExporter.cpp
code/Subdivision.cpp
code/XFileExporter.cpp
code/glTFExporter.cpp
include/assimp/SceneCombiner.h

closes https://github.com/assimp/assimp/issues/586

Issue 586 make scenecombiner public

---

include/assimp/material.inl

Fixed bug in material color processing

---

code/X3DExporter.cpp
code/X3DExporter.hpp
code/X3DImporter.cpp
code/X3DImporter.hpp
code/X3DImporter_Networking.cpp
code/X3DImporter_Rendering.cpp

Hi,
I made some fixes to the X3DImporter and the X3DExporter. Would be nice to get them merged back into the main repository.
Thanks,
Patrick

Fixes for X3DImporter/X3DExporter

---

code/AssbinExporter.cpp
code/AssbinLoader.cpp

As the title says, assbin format was not handling metadata. It's not the case anymore.

Added support for metadata in assbin format

---

code/FIReader.cpp

X3D importer: Workaround for buggy Android NDK (issue #1361)

---

code/CMakeLists.txt
code/Exporter.cpp
code/glTF2Asset.h
code/glTF2Asset.inl
code/glTF2AssetWriter.h
code/glTF2AssetWriter.inl
code/glTF2Exporter.cpp
code/glTF2Exporter.h

This is part of https://github.com/assimp/assimp/issues/1301, but certainly not full support since it only includes exporting. I just copied and altered the glTF1 exporter, so there is a lot of duplicate code.

glTF2 export support

---

code/C4DImporter.cpp
code/C4DImporter.h

Fixes to allow the C4D importer to compile correctly. Melange won't link in correctly but hey it's a start

Fixes for C4D importer

---

Readme.md

see https://github.com/assimp/assimp/issues/1381

Replaced out-of-date old repo link with a wiki link to C4D file format build instructions

---

port/PyAssimp/pyassimp/helper.py
port/PyAssimp/scripts/3d_viewer_py3.py

- Installing Assimp from conda-forge will install it in the "lib" of either the **main conda** or the **current conda env**. This check will ensure the library gets loaded from there.
- In python 3 "/" divisions results to float, "//" to int.
- reduce is now deprecated

Detect if Anaconda and fixed 3d_viewer for Python 3

---

code/FBXBinaryTokenizer.cpp

Rickomax master

---

code/OpenGEXImporter.cpp
code/OpenGEXImporter.h

- Adds missing implementation for the missing resolving ofr material references.

closes https://github.com/assimp/assimp/issues/1467.

---

CMakeLists.txt
appveyor.yml

Treat warnings as errors on Appveyor.I haven't actually tested this, let's see if it works...

Treat warnings as errors on Appveyor

---

.travis.sh
.travis.yml
CMakeLists.txt
code/B3DImporter.cpp
code/FBXBinaryTokenizer.cpp
code/IFCBoolean.cpp

Add UBSan option and enable it on Travis. Expecting a failure. Will fix issues before merge.

Undefined Behavior sanitizer

---

port/PyAssimp/pyassimp/helper.py

Search for libassimp.so in LD_LIBRARY_PATH if available.

[pyassimp] Search for libassimp.so in LD_LIBRARY_PATH if available.

---

code/ObjFileParser.cpp
test/unit/utObjImportExport.cpp

Aavenel unittest obj importer

---

code/ColladaExporter.cpp
code/D3MFImporter.cpp
code/FIReader.cpp
code/FindDegenerates.cpp
code/FindInvalidDataProcess.cpp
code/MMDImporter.cpp
code/MMDPmxParser.cpp
code/OpenGEXExporter.cpp
code/STLLoader.cpp
code/glTF2Asset.inl
code/glTF2Exporter.cpp

These commits should fix all warnings on MSVC14 :)

Fix all warnings on MSVC14

---

code/glTF2Asset.h
code/glTF2Asset.inl
code/glTF2Importer.cpp

[glTF2] Add support for tangents in import

---

code/glTF2Importer.cpp

[glTF2] Preserve node names when importing

---

code/MDLLoader.cpp
code/XGLLoader.cpp
include/assimp/vector2.h
include/assimp/vector2.inl
include/assimp/vector3.inl

Disable unaligned pointer access temporary.

---

code/MDLMaterialLoader.cpp
code/MMDImporter.cpp
code/OpenGEXImporter.cpp
code/Q3BSPZipArchive.cpp
code/RawLoader.cpp
code/RemoveComments.cpp
contrib/irrXML/CXMLReaderImpl.h

Fixes various crashes when loading some of the shipped models.

Miscellaneous memory management fixes

---

tools/assimp_qt_viewer/mainwindow.cpp

- Add a dialog to select the exporter
- Export based on exporter id instead of extensions (fix issues like for Collada)
- Message box if there is an error

Qt viewer : Improve exports

---

port/PyAssimp/setup.py

What it says on the tin.  Reference #1659

Version bump pyassimp

---

code/glTF2AssetWriter.inl

[glTF2] Using relative buffers URI

---

doc/dox.h

Small fixes to the documentation which make it IMHO easier to understand.

Fix typos and ease description of coordinate frame

---

code/glTF2Importer.cpp

glTF 2.0: Set camera "look at" to (0.0, 0.0, -1.0).

---

code/3DSHelper.h
code/3DSLoader.cpp
code/ASEParser.cpp
code/ASEParser.h

Fix more thread-safety issue in 3DS and ASE loaders

---

code/BVHLoader.h
code/BaseImporter.cpp
code/CSMLoader.cpp
code/LimitBoneWeightsProcess.h
code/PretransformVertices.cpp
include/assimp/Importer.hpp
include/assimp/anim.h
include/assimp/matrix3x3.inl
include/assimp/mesh.h
include/assimp/types.h

Fix some of the issues from #1739

Miscellaneous fixes

---

include/assimp/MemoryIOWrapper.h

Make MemoryIOStream::Seek accept pos=length as valid

---

code/glTF2Asset.h
include/assimp/pbrmaterial.h

Hi,
This is not a PR itself, but a workaround I'm using to identify PBR parameters and texture channels.
How should we identify those attributes? I had to create this pbrmaterial.h in order to include it from my plugin/exe, outside assimp project.
How is this supposed to be used in the future?
Thanks,

idea: #include <assimp/pbrmaterial.h>

---

tools/assimp_cmd/Info.cpp

just a small addition to the `assimp info` command to print mesh info.

assimp_cmd info: list meshes and print basic mesh stats.

---

code/D3MFExporter.cpp
code/D3MFExporter.h
code/D3MFImporter.cpp
code/Exporter.cpp
code/SceneCombiner.cpp
include/assimp/metadata.h
test/unit/utMetadata.cpp

- Copy metadata of scene for exporters.
- Add copy constructor for metadata + unittest
- Add missing metadata export for 3MF

3mf basematerial support

---

code/FBXMeshGeometry.cpp
code/FBXMeshGeometry.h
include/assimp/IOStreamBuffer.h

Closes https://github.com/assimp/assimp/issues/1527

FBX: fix parse error for uv-coordinates.

---

code/FBXExportProperty.cpp
code/FBXExportProperty.h
code/FBXExporter.cpp
code/FBXExporter.h

supports only node-based animation for now.

Basic animation support in FBX export

---

code/CMakeLists.txt
code/ScenePrivate.h
code/simd.cpp
code/simd.h
test/CMakeLists.txt
test/unit/AbstractImportExportBase.cpp
test/unit/utAnim.cpp
test/unit/utSimd.cpp

Add check for SSE2-support.

---

code/Exporter.cpp
code/PretransformVertices.cpp
code/PretransformVertices.h
code/RemoveRedundantMaterials.h
code/STLExporter.cpp
code/STLExporter.h
code/simd.cpp
include/assimp/Exporter.hpp
include/assimp/GenericProperty.h
include/assimp/cexport.h
include/assimp/config.h.in
test/unit/utPLYImportExport.cpp
test/unit/utSTLImportExport.cpp

- Needs to get enabled by the property AI_CONFIG_EXPORT_POINT_CLOUDS 
- Will currently only work with stl-export
- see utSTLImporterExporter::test_export_pointclouds

Issue 842: Solving for ascii stl point cloud export

---

tools/assimp_cmd/Export.cpp
tools/assimp_cmd/Main.cpp

- check for postprocessing parameter before try to parse -f
- make parser for arguments easier to debug

closes https://github.com/assimp/assimp/issues/1952: 

---

.gitignore
code/FBXBinaryTokenizer.cpp
code/glTF2Exporter.cpp
code/glTF2Exporter.h
test/unit/utglTF2ImportExport.cpp

fix crash on linux during glTF2.0 export.

Issue 1780

---

code/GenVertexNormalsProcess.cpp

previous comparison check was failing for very small smoothing angles (fLimit approaching 1.0) because v dot v not guaranteed to be >= 1.0 for all unit vectors

Fix GenVertexNormals

---

.gitignore
CMakeLists.txt
code/3DSLoader.cpp
code/D3MFExporter.cpp
code/Importer.cpp
code/glTF2Exporter.cpp
test/unit/utMetadata.cpp
test/unit/utSharedPPData.cpp
tools/assimp_qt_viewer/CMakeLists.txt
tools/assimp_qt_viewer/glview.cpp
tools/assimp_qt_viewer/glview.hpp
tools/assimp_qt_viewer/mainwindow.cpp
tools/assimp_qt_viewer/mainwindow.hpp
tools/assimp_qt_viewer/mainwindow.ui

Fixed issues:
https://github.com/assimp/assimp/issues/1171
https://github.com/assimp/assimp/issues/1778

Qt assimp viewer and few fixes in another places

---

CONTRIBUTING.md

This fixes some typos in the contribution guide and improves the markup.

Improve the contribution guide

---

code/FBXConverter.cpp
code/FBXConverter.h

see https://github.com/assimp/assimp/pull/2058

Fix unique names fix ci

---

code/glTF2Exporter.cpp

Hello,
The glTF2 exporter forced the large meshes to be split in small parts (max 65 535 faces/vertices) to use 16-bit indices. I think it is better to allow 32-bit indices because it is possible in the specifications (https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#indicescomponenttype-white_check_mark) and if the user wants the large meshes to be split it is still possible to export with the preprocessing option aiProcess_SplitLargeMeshes.
Forcing 16-bit indices is not efficient for large meshes when the 3D engine can handle 32-bit indices (ex : Unity 2017.3) and the glTF2 exporter in Assimp can be very long when there are a lot of meshes (which is the case when a big mesh is split into many small ones) due to the time complexity in O(n²) of this function called for …

Add support of 32-bit indices for the glTF2 export

---

code/Assimp.cpp
code/Importer.cpp
code/MaterialSystem.cpp
code/STLLoader.cpp
include/assimp/material.h
test/unit/utMaterialSystem.cpp
test/unit/utSTLImportExport.cpp

It's broken as discussed in #2126.
Closes  #2126
Reopen #1724

Remove aiCreateAndRegisterDefaultMaterial

---

code/AssbinExporter.cpp
code/AssbinExporter.h
code/AssbinLoader.cpp
test/CMakeLists.txt
test/unit/utAssbinImportExport.cpp

Assbin: add unittest.

---

code/BlenderLoader.cpp

Fix Blender FOV loading (fixes #1854)

---

code/BlenderScene.cpp

Merged master of https://github.com/assimp/assimp/pull/2183

Ihmc3jn09hk patch 1

---

appveyor.yml
include/assimp/Compiler/pushpack1.h

This PR addresses the issue #2205

add clang to pushpack1.h

---

code/PostStepRegistry.cpp

Still untested, but I guess it won't do anything when never referenced...

added DropFaceNormalsProcess to out vector

---

code/ColladaExporter.cpp

collada export: Use Camera local coordinate system

---

test/CMakeLists.txt
test/unit/ut3DSImportExport.cpp
test/unit/utLWOImportExport.cpp
test/unit/utSTLImportExport.cpp

Nothing too fancy, it's just a few unit tests to increase coverage :)

More unit tests

---

port/jassimp/jassimp/src/jassimp/AiAnimation.java
port/jassimp/jassimp/src/jassimp/AiBone.java
port/jassimp/jassimp/src/jassimp/AiClassLoaderIOSystem.java
port/jassimp/jassimp/src/jassimp/AiColor.java
port/jassimp/jassimp/src/jassimp/AiMaterial.java
port/jassimp/jassimp/src/jassimp/AiMesh.java
port/jassimp/jassimp/src/jassimp/AiNode.java
port/jassimp/jassimp/src/jassimp/AiQuaternion.java
port/jassimp/jassimp/src/jassimp/AiSceneFlag.java
port/jassimp/jassimp/src/jassimp/Jassimp.java

- fix code finding: Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes.
- fix code finding: Use explicit scoping instead of the default package private level

Kimkulling dev

---

port/jassimp/jassimp-native/src/jassimp.cpp
port/jassimp/jassimp-native/src/jassimp.h
port/jassimp/jassimp/src/jassimp/AiMaterial.java
port/jassimp/jassimp/src/jassimp/AiProgressHandler.java
port/jassimp/jassimp/src/jassimp/AiSceneFlag.java
port/jassimp/jassimp/src/jassimp/Jassimp.java

Add ProgressHandler support for progress callback while importing models through jassimp.

Add progresshandler support jassimp

---

code/FBXConverter.cpp
code/FBXConverter.h
code/FBXDocument.cpp
code/FBXDocument.h
code/FBXMeshGeometry.cpp
code/FBXMeshGeometry.h

add FBX Line Element support

---

code/FBXConverter.cpp
code/FBXConverter.h

Those are the changes described in [Issue 2090](https://github.com/assimp/assimp/issues/2090) 
Credit to @griffin2000 for the original code.

Preserve all the material parameters from FBX models

---

port/PyAssimp/setup.py

Main changes:
- Support for metadata fields (Vincent Fazio, Wojciech Matyjewicz)
- added support for aiExportSceneToBlob (Vincent Fazio)
- a few bug fix + code beautification
The pip package has been updated accordingly.

[pyassimp] Bumped to 4.1.4

---

code/ObjFileImporter.cpp
test/unit/utObjImportExport.cpp

See here https://github.com/assimp/assimp/issues/2349 for more details

Obj: we can still import partially incorrect files

---

appveyor.yml

- Enable vs2015 build
- Enable vs2017 build

Reenable vs2015 and vs1017

---

code/AssbinLoader.cpp
code/FBXConverter.cpp
code/FindInstancesProcess.cpp
code/ImproveCacheLocality.cpp
code/MD3FileData.h
code/MD3Loader.cpp
code/SMDLoader.cpp
code/SortByPTypeProcess.cpp
code/StandardShapes.cpp
code/ValidateDataStructure.cpp
test/unit/utSTLImportExport.cpp
tools/assimp_cmd/Info.cpp
tools/assimp_cmd/WriteDumb.cpp
tools/assimp_view/SceneAnimator.cpp

- fix warn-level 3 warnings in vs2017
- fix some warn-level 4 warnings in vs2017
- fix coverity findings.

Fix vs-2017 warnings

---

code/CMakeLists.txt
contrib/zip/.gitignore
contrib/zip/.travis.sh
contrib/zip/.travis.yml
contrib/zip/CMakeLists.txt
contrib/zip/README.md
contrib/zip/appveyor.yml
contrib/zip/cmake/asan-wrapper
contrib/zip/cmake/cmake_uninstall.cmake.in
contrib/zip/src/miniz.h
contrib/zip/src/zip.c
contrib/zip/src/zip.h
contrib/zip/test/CMakeLists.txt
contrib/zip/test/test.c
contrib/zip/test/test_miniz.c

Should close #2388 (may not show up due to github erroneously flagging the poster's account as a bot)
Should also close #2374

zip: Update to latest version

---

code/FBXConverter.cpp
code/FBXConverter.h

My suggested fix for https://github.com/assimp/assimp/issues/2390

FBX: Fix for loading taking a very long time on models with duplicate names

---

code/FBXConverter.cpp
code/FBXConverter.h
code/FBXImportSettings.h
code/FBXImporter.cpp
code/FBXMeshGeometry.cpp
code/FBXParser.cpp
include/assimp/config.h.in

- Add FBX feature to provide conversion from cm to m ( Request from godot ).

Fbx convert to unit

---

code/FindDegenerates.cpp

Triangles with small area had never removed, if there is no other type of degenerates `deg` never been updated

Degenerate triangles with small area removing fix

---

code/LWO/LWOLoader.cpp

Fix for issue:
https://github.com/assimp/assimp/issues/2525

initialize unnamed node uniqueness index outside of loop

---

code/Common/Exporter.cpp

Fix issue #2557

---

code/PostProcessing/CalcTangentsProcess.cpp

Got a runtime undefined behavior error when running with the address sanitizer

fix for div by zero reported by address sanitizer

---

code/PostProcessing/ScaleProcess.cpp
code/PostProcessing/ScaleProcess.h
test/unit/TestModelFactory.h
test/unit/utScaleProcess.cpp
tools/assimp_cmd/Main.cpp

Fixes scaling so that it is more compatible with unit conversion and also has working animation scaling.

ScaleProcess overhauled to improve compatibility

---

samples/SimpleOpenGL/Sample_SimpleOpenGL.c

Extra keyword `struct` causing problems

Fix Sample_SimpleOpenGL.c

---

code/glTF/glTFExporter.cpp

Remove code from ai_assert test, will be removed in release versions.

closes https://github.com/assimp/assimp/issues/2627 - fix typo

---

code/glTF2/glTF2Importer.cpp

Fix: memory leak in gltf2 importer (fixes #2661)

---

code/glTF2/glTF2Importer.cpp

Fix: Mismatched new/free in gltf2 importer (fixes #2668)

---

code/glTF2/glTF2Importer.cpp

Fix: Wrong aiAnimation::mTicksPerSecond for gltf2 imports (fixes #2662)

---

code/Common/SceneCombiner.cpp
code/PostProcessing/ValidateDataStructure.cpp
code/PostProcessing/ValidateDataStructure.h
code/glTF2/glTF2Importer.cpp
include/assimp/SceneCombiner.h

Signed-off-by: Victor Cebollada <v.cebollada@samsung.com>

gltf2.0 importer - Support for mesh morph animations added.

---

code/M3D/m3d.h

Hi,
Updated m3d.h to the latest, most changes are irrelevant to Assimp (as M3DImport uses Assimp's post-processing, the minor performance tweaks in the SDK's doesn't matter), but this patch also solves issue https://github.com/assimp/assimp/issues/2781 about a Clang warning.
Cheers,
bzt

MinGW support, profiling and signed error code

---

code/glTF2/glTF2Importer.cpp

Adding the needed change of coordinates for KHR_texture_transform. This should hopefully complete issue #2119 now.

Migenius fix khrtexturetransform

---

code/B3D/B3DImporter.cpp
code/FBX/FBXConverter.cpp
code/LWO/LWOLoader.cpp
include/assimp/LineSplitter.h

Change the cout calls to ASSIMP_LOG_XXX
Fixes #2797

Remove cout calls from FBX, LWO and B3D

---

code/PostProcessing/ConvertToLHProcess.h
code/PostProcessing/OptimizeGraph.cpp
code/PostProcessing/OptimizeGraph.h
code/PostProcessing/PretransformVertices.cpp
code/PostProcessing/PretransformVertices.h

Fixes #2383 for both OptimizeGraph and PretransformVertices

Backfacing odd negative scale 2383

---

code/FBX/FBXConverter.cpp

Small addition to material import from FBX, to add support for 3DSMax

Add a support for 3DSMax Physically Based Materials for FBX format

---

code/Common/ScenePreprocessor.cpp
code/X/XFileImporter.cpp
test/unit/utXImporterExporter.cpp

Fix memory leak in .X importer

---

code/Assbin/AssbinExporter.cpp
code/Assbin/AssbinLoader.cpp
code/PostProcessing/ValidateDataStructure.cpp
include/assimp/texture.h
tools/assimp_cmd/CompareDump.cpp
tools/assimp_cmd/WriteDumb.cpp

[Link to original PR](https://github.com/assimp/assimp/pull/2947).

Updated places where read/write for achFormatHint (Redone).

---

code/MDL/HalfLife/HL1MDLLoader.cpp
test/unit/ImportExport/utMDLImporter.cpp

[Link to issue](https://github.com/assimp/assimp/issues/2951).

Added support to load HL1 MDL external texture files directly.

---

code/Common/assbin_chunks.h
tools/assimp_cmd/CMakeLists.txt
tools/assimp_cmd/Main.h
tools/assimp_cmd/WriteDump.cpp

This includes as well changes to places referencing WriteDumb.cpp.

Renamed WriteDumb.cpp to WriteDump.cpp

---

CMakeLists.txt

- don't include HunterGate.cmake if you don't enable HUNTER package manager
- don't check for DirectX if you don't build the assimp tools or samples

Small changes in the CMake file

---

code/PostProcessing/ValidateDataStructure.cpp

Similar to https://github.com/assimp/assimp/issues/2964.

Added missing texture types when searching for invalid textures.

---

code/Obj/ObjFileImporter.cpp
code/Obj/ObjFileMtlImporter.cpp
code/Obj/ObjFileParser.cpp
code/Obj/ObjFileParser.h

- make use of range for loops
- make use of empty() method for the std::vector
- removed unnecessary std::string initialization
- use ' ' instead of " " for the find methods (should be "faster")
- simplified some function
- make use of emplace_back instead of push_back (should be "faster")
- other small changes

minor code improvements for the obj code

---

samples/SimpleTexturedOpenGL/SimpleTexturedOpenGL/src/model_loading.cpp

This is a fix for the memory leaks that were found in https://github.com/assimp/assimp/pull/3015.
- Added function "cleanup" to centralize release of resources.
- Added function "freeTextureIds" to free/clear anything texture related.
- Added call to freeTextureIds in LoadGLTextures to free memory before it is allocated again.
- Made several changes in KillGLWindow to prevent certain Win32 handle/resources
from being released more than once.

Fixed memory leaks in SimpleTexturedOpenGL sample.

---

code/glTF2/glTF2Importer.cpp

Fix for #3037 cause glTF2Importer creating bunch of bones with 0 for vertex with index 0

---

samples/SimpleTexturedOpenGL/CMakeLists.txt
samples/SimpleTexturedOpenGL/SimpleTexturedOpenGL/include/boost_includes.h

closes https://github.com/assimp/assimp/pull/3104: 

---

code/Common/Assimp.cpp
code/FBX/FBXImportSettings.h
code/FBX/FBXImporter.cpp
code/FBX/FBXImporter.h
include/assimp/metadata.h
test/unit/utFBXImporterExporter.cpp

- Add missing setter for metadata
- Improved unittest for mtadata-setup
Use this to discuss features for issue 2166

closes https://github.com/assimp/assimp/issues/2166: 

---

tools/assimp_view/Background.cpp
tools/assimp_view/Display.cpp
tools/assimp_view/HelpDialog.cpp
tools/assimp_view/LogDisplay.cpp
tools/assimp_view/LogWindow.cpp
tools/assimp_view/Material.cpp
tools/assimp_view/MessageProc.cpp
tools/assimp_view/assimp_view.cpp

As explained [here](https://github.com/assimp/assimp/pull/3129#issuecomment-609055983), changes are expected to be made in order to replace occurences of NULL pointers by nullptr.
The following changes apply the expected changes to Assimp viewer.
These changes were tested on 32 bits and 64 bits builds.

Replaced NULL with nullptr for pointers in Assimp viewer.

---

samples/SimpleTexturedOpenGL/SimpleTexturedOpenGL/src/model_loading.cpp

As explained [here](https://github.com/assimp/assimp/pull/3129#issuecomment-609055983), changes are expected to be made in order to replace occurences of NULL pointers by nullptr.
The following changes apply the expected changes to sample SimpleTexturedOpenGL.
These changes were tested on 32 bits and 64 bits builds.

Replaced NULL with nullptr for pointers in sample SimpleTexturedOpenGL.

---

code/AssetLib/X3D/X3DImporter_Postprocess.cpp
include/assimp/metadata.h

- check if metadata is already there before allocating new memory.

closes https://github.com/assimp/assimp/issues/3190 : fix leak.

---

test/unit/utTriangulate.cpp

closes https://github.com/assimp/assimp/issues/3186

Remove duplicate flag

---

code/AssetLib/glTF2/glTF2Asset.h
code/AssetLib/glTF2/glTF2Asset.inl

PR to fix merge-conflicts from https://github.com/assimp/assimp/pull/3111

Zyndor master

---

code/AssetLib/glTF2/glTF2Asset.inl

USed to resolve merge conflicts from https://github.com/assimp/assimp/pull/3172.

Migenius migenius fix ortho

---

code/AssetLib/Collada/ColladaLoader.cpp
code/Collada/ColladaExporter.cpp

Used to resolve merge conflicts from https://github.com/assimp/assimp/pull/3169.

Inhosens master

---

code/AssetLib/glTF/glTFCommon.cpp

To resolve merge conflicts from https://github.com/assimp/assimp/pull/3182

Qarmin added check before using

---

code/AssetLib/glTF/glTFAsset.h
code/AssetLib/glTF/glTFCommon.h
code/AssetLib/glTF2/glTF2Asset.h

Tested  by forcing to compile in c++17 and without changing CMakeLists

Added rapidjson define to avoid warnings in c++17

---

code/AssetLib/Blender/BlenderDNA.inl

closes https://github.com/assimp/assimp/issues/3255

Perform sanity check only in debug

---

code/AssetLib/glTF2/glTF2AssetWriter.inl

Loic fr master

---

CMakeLists.txt
assimpTargets-release.cmake.in

Please see the commits for more detailed explanations of the problems.
Please correct the base (if that's possible) to the correct one.
Thanks!

Fixes library finding & dynamic loading on macos

---

code/AssetLib/IFC/IFCReaderGen1_2x3.cpp
code/AssetLib/IFC/IFCReaderGen2_2x3.cpp
code/AssetLib/M3D/m3d.h
code/AssetLib/glTF/glTFExporter.cpp
code/AssetLib/glTF2/glTF2Asset.h

Building the latest master in Hunter worked on a few platforms, but not others.
Before:
https://travis-ci.com/github/rbsheth/hunter/builds/176099736
https://ci.appveyor.com/project/rbsheth/hunter/builds/34163086
After these fixes (with a merge of master), all platforms work through Hunter builds - Linux, Windows, Mac, iOS, and Android:
https://travis-ci.com/github/rbsheth/hunter/builds/177070395
https://ci.appveyor.com/project/rbsheth/hunter/builds/34288660
@kimkulling Would it be worth adding some Github Actions pipelines to replicate these builds? I can do that in a future PR if desired.

Fixing more build warnings

---

code/AssetLib/3DS/3DSExporter.cpp

closes https://github.com/assimp/assimp/issues/3291

Export opacity is 3DS

---

code/Common/DefaultIOStream.cpp
code/PostProcessing/TriangulateProcess.cpp

- closes https://github.com/assimp/assimp/issues/3353
- Move functions into the correct preprocessor branch

Fix wrong function defines

---

code/Common/StandardShapes.cpp
test/CMakeLists.txt
test/unit/Common/utStandardShapes.cpp

closes https://github.com/assimp/assimp/issues/3364

Fix incorrect index

---

code/AssetLib/Collada/ColladaParser.cpp
code/Common/BaseImporter.cpp

closes https://github.com/assimp/assimp/issues/3449

Add handling for source for params

---

code/AssetLib/glTF/glTFAsset.inl
code/AssetLib/glTF2/glTF2Importer.cpp

1. glTF1's orthographic camera is not patched yet
2. glTF2's skinning ignored some bones that do not have weights since a moment.
It is not correct approach because the empty bones can connect a bone with another.

glTF1's orthgraphic camera & glTF2's skinning

---

code/AssetLib/glTF2/glTF2Asset.inl

This fixes crashes when importing a GLTF2 file with wrong data in the JSON (i.e. an invalid file).

Fixes for crashes in GLTF2 Importer

---

code/AssetLib/Obj/ObjFileMtlImporter.cpp

- Add transmission alpha value. if any.

closes https://github.com/assimp/assimp/issues/3448

---

code/AssetLib/LWS/LWSLoader.cpp

Fix envelope handling in lightintensity.

closes https://github.com/assimp/assimp/issues/1044

---

test/CMakeLists.txt

Do not use pthread for android

closes https://github.com/assimp/assimp/issues/3187

---

port/AndroidJNI/README.md

Took me some time to figure out how to build for other ABIs, think it would be helpful to have some information about it on the port documentation.

Update Android port README.md with ABI doc

---

code/AssetLib/glTF/glTFCommon.cpp
code/AssetLib/glTF/glTFCommon.h
code/AssetLib/glTF2/glTF2Asset.h
code/AssetLib/glTF2/glTF2Asset.inl
code/AssetLib/glTF2/glTF2Importer.cpp

* Fixes crash on invalid base64 data
* Improves several error messages
* Throws instead of asserts on invalid file input

GLTF: Fix crash on invalid base64 data + improved error messages

---

code/AssetLib/Collada/ColladaHelper.cpp
code/CMakeLists.txt
code/Common/ZipArchiveIOSystem.cpp
contrib/Open3DGC/o3dgcVector.inl
samples/SimpleTexturedOpenGL/SimpleTexturedOpenGL/src/model_loading.cpp
tools/assimp_view/MeshRenderer.cpp
tools/assimp_view/MessageProc.cpp

Fixes https://github.com/assimp/assimp/issues/3144

Common: Fix GCC error invalid conversion in MINGW.

---

code/AssetLib/3MF/3MFXmlTags.h
code/AssetLib/3MF/D3MFExporter.cpp
code/AssetLib/3MF/D3MFExporter.h
code/AssetLib/3MF/D3MFImporter.cpp
include/assimp/XmlParser.h

This PR fixes the import of materials in the 3MF importer (which caused crashes), and improve it by adding support for basematerials with multiple materials + object material support

3mf improvements

---

code/AssetLib/AC/ACLoader.h

- closes https://github.com/assimp/assimp/issues/3517

Use const instead of constexpr

---

code/AssetLib/glTF2/glTF2Asset.inl

* Check that buffer view has buffer
* Handle integer overflow when calculating byte length
* Minor code cleanup for exception messages

Fixes for GLTF2 buffers

---

include/assimp/vector3.inl

Fix for https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=29655

Fix Divide-by-zero in vector3

---

code/AssetLib/STL/STLExporter.cpp

Fix STL Expoter error.

---

code/AssetLib/IFC/IFCGeometry.cpp

- closes https://github.com/assimp/assimp/issues/3180

Remove redundant statement in if

---

code/AssetLib/Collada/ColladaParser.cpp

closes https://github.com/assimp/assimp/issues/3599

Fix typo in collada parser

---

code/AssetLib/Collada/ColladaParser.cpp

- closes https://github.com/assimp/assimp/issues/3601
- Fix some format issues

Add missing skip

---

code/AssetLib/FBX/FBXMaterial.cpp

- Check https://developercommunity.visualstudio.com/content/problem/1223143/visual-studio-2019-c-program-crash-with-stdstring.html for more details
- closes https://github.com/assimp/assimp/issues/3572

Fix compiler bug for VS2019

---

include/assimp/metadata.h
test/unit/utMetadata.cpp

- closes https://github.com/assimp/assimp/issues/3621

Fixes a mem leak in aiMetadata::Set

---

include/assimp/port/AndroidJNI/BundledAssetIOSystem.h
port/AndroidJNI/BundledAssetIOSystem.cpp
port/AndroidJNI/CMakeLists.txt

implements a DefaultIOSystem that provides read-only access to files bundled with Android Applications
addresses issue  #3633 may also satisfy #822 or  #711

Implements access to files bundled with Android Applications

---

Readme.md

Hi, I have created rust bindings to your library.
If you think that is ok, can I include it on your README?
Thanks.

Rust bindings

---

code/AssetLib/Collada/ColladaParser.cpp
code/AssetLib/MDL/HalfLife/HL1MDLLoader.cpp
code/AssetLib/MDL/HalfLife/HL1MDLLoader.h
code/Pbrt/PbrtExporter.cpp
include/assimp/XmlParser.h

changed float types to ai_real types as needed
addresses issue #3682

workaround for ASSIMP_DOUBLE_PRECISION compile errors

---

include/assimp/importerdesc.h

applied extern "C" guards to importerdesc.h

---

Dockerfile

- closes https://github.com/assimp/assimp/issues/1063

Provide a dockerfile

---

code/AssetLib/HMP/HMPLoader.cpp

closes https://github.com/assimp/assimp/issues/3747

Fix direct leak

---

code/AssetLib/MS3D/MS3DLoader.cpp

These indices are quite bogus. I'm not sure how this was ever working before...

Fix incorrect indices in the MilkShape 3D loader

---

include/assimp/XmlParser.h

closes https://github.com/assimp/assimp/issues/3754

Not resize empty vectors.

---

code/Common/Version.cpp
test/unit/utVersion.cpp

2020 -> 2021
assimp team -> Assimp team

Version string fix (if anyone cares)

---

Readme.md

- Add assimp to codacy
- Add batch to readme

Add Codacy Badge

---

include/assimp/postprocess.h

Addresses #3820, the easy way.

Update aiProcess_PreTransformVertices docs to match behavior.

---

code/AssetLib/3DS/3DSExporter.cpp
code/AssetLib/3MF/3MFXmlTags.h
code/AssetLib/3MF/D3MFExporter.cpp
code/AssetLib/3MF/D3MFImporter.cpp
code/AssetLib/3MF/D3MFOpcPackage.cpp
code/AssetLib/AMF/AMFImporter_Postprocess.cpp
code/CApi/CInterfaceIOWrapper.cpp
contrib/zip/src/zip.c

-Replace std::string my const char

use const chars

---

include/assimp/camera.h

fix issue #2256 
only checked in collada loader source

Fix camera fov comment since full fov is stored

---

code/AssetLib/glTF2/glTF2Asset.inl
code/CMakeLists.txt
include/assimp/TinyFormatter.h

Compilation fixes when building Assimp using GCC 4.9

Fix gcc4.9 compilation

---

Readme.md

- closes https://github.com/assimp/assimp/issues/3872

Update unity plugin to trilib2

---

port/PyAssimp/pyassimp/core.py

- closes https://github.com/assimp/assimp/issues/3887

Use correct attribute name

---

contrib/pugixml/readme.txt
contrib/pugixml/src/pugiconfig.hpp
contrib/pugixml/src/pugixml.cpp
contrib/pugixml/src/pugixml.hpp

- Closes https://github.com/assimp/assimp/issues/3767

update pugi_xml to 1.11

---

code/AssetLib/IFC/IFCBoolean.cpp

Replace swear words in IFCBoolean.cpp

---

cmake/assimp-hunter-config.cmake.in

@kimkulling Oops, I missed this in #3985 which causes a failure when building through Hunter: https://github.com/cpp-pm/hunter/pull/440/checks?check_run_id=3066470709

Find stb for Assimp

---

contrib/openddlparser/code/OpenDDLParser.cpp
contrib/openddlparser/code/Value.cpp
contrib/openddlparser/include/openddlparser/OpenDDLParser.h

- Use latest version of OpenDDL-Parser

closes https://github.com/assimp/assimp/issues/3975: 

---

include/assimp/quaternion.h

- Fix euler angles as descriped here: https://github.com/assimp/assimp/issues/3790
- closes https://github.com/assimp/assimp/issues/3790

Fix euler angles

---

code/AssetLib/C4D/C4DImporter.cpp

- Convert left-handed coordinate system to right-handed coordinate system
- Rescale model by 0.01
- closes https://github.com/assimp/assimp/issues/3760

Fix Issue3760

---

code/AssetLib/Collada/ColladaParser.cpp
code/AssetLib/X/XFileImporter.cpp

removed useless code

---

include/assimp/fast_atof.h

This avoids reading past the length of the input string.

Use strlen() rather than fixed length in fast_atof.h

---

code/AssetLib/FBX/FBXParser.cpp
code/AssetLib/glTF2/glTF2Asset.inl
code/AssetLib/glTF2/glTF2Importer.cpp

This fixes several crashes and asserts when importing invalid files.

Crash fixes

---

code/AssetLib/glTF/glTFExporter.cpp
code/Common/Assimp.cpp
contrib/openddlparser/code/OpenDDLExport.cpp

These were issues that came up when building with Clang 13.0.0.

Add missing diagnostic pragmas and remove unused code

---

samples/SimpleTexturedOpenGL/SimpleTexturedOpenGL/src/model_loading.cpp

modify stb_image header path, fix opengl sample build error.

fix sample build error

---

CMakeLists.txt

- DX will not work with gcc-based builds
- closes git push --set-upstream origin issue_4042

Enable Viewer only for VS-Builds

---

code/AssetLib/HMP/HMPLoader.cpp
code/AssetLib/M3D/m3d.h
code/AssetLib/MDL/MDLLoader.cpp
code/AssetLib/MDL/MDLMaterialLoader.cpp
code/Common/FileSystemFilter.h
code/Common/RemoveComments.cpp
contrib/openddlparser/code/OpenDDLParser.cpp
contrib/openddlparser/include/openddlparser/OpenDDLParserUtils.h
include/assimp/IOStreamBuffer.h

This PR addresses [all but one of the OSS-Fuzz issues](https://bugs.chromium.org/p/oss-fuzz/issues/list?sort=proj&q=Type%3DBug-Security%20label%3ADeadline-Exceeded%20-label%3AStability-UndefinedBehaviorSanitizer%20label%3Areproducible%20proj%3Aassimp&can=2) marked as security relevant.
Fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=33238
Fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24553 (Fix #3425)
Fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24465 (Fix #3348)
Fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=31795
Fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24463 (Fix #3429)
Fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=36594
Fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25401 (Fix #4096)
Fix …

Fix fuzzer crashes

---

CMakeLists.txt
test/unit/utVersion.cpp

- Change version for Version 5.1.0-RC1 to 5.1.0
- closes https://github.com/assimp/assimp/issues/4161

Change version to 5.1.0

---

Readme.md

This is most complete UE assimp plugin that currently wraps  90% of the assimp code to be used in unreal engine blueprints and c++ . I'll be honored if you guys mention this plugin  in readme so we can get more contributions .

Added UE4 plugin

---

code/Common/PolyTools.h

- closes https://github.com/assimp/assimp/issues/4240

Fix division by zero in PointInTriangle2D

---

code/AssetLib/DXF/DXFLoader.cpp

- Finding from fuzzer
- closes https://github.com/assimp/assimp/issues/4237

Fix nullptr dereferencing from std::shared_ptr

---

code/AssetLib/X3D/X3DImporter_Geometry3D.cpp
code/AssetLib/glTF2/glTF2Exporter.cpp
code/AssetLib/glTF2/glTF2Exporter.h
include/assimp/SkeletonMeshBuilder.h
include/assimp/color4.h
include/assimp/light.h
include/assimp/material.inl
include/assimp/texture.h
include/assimp/vector2.h
include/assimp/vector3.inl
test/unit/utMaterialSystem.cpp

- closes https://github.com/assimp/assimp/issues/4248

Use correct XmlParser-methods and add some missing casts

---

CMakeLists.txt

- Enable c++11
- Enable c99 for C-API
- closes https://github.com/assimp/assimp/issues/4257

Enable C++11 and C99

---

code/Common/DefaultProgressHandler.h
code/Common/Importer.cpp
include/assimp/ProgressHandler.hpp
tools/assimp_cmd/Main.cpp

- Commandline-tool assimp will show a progress in the console.
- closes https://github.com/assimp/assimp/issues/963

Add console progresshandler

---

code/AssetLib/X3D/X3DImporter.cpp

- Fix a possible nullptr-exception.

Fix nullptr-dereferencing

---

CMakeLists.txt
test/unit/utVersion.cpp

- Increase minot version to 5.1.6

Update to 5.1.6

---

CMakeLists.txt
code/Common/Version.cpp
test/unit/utVersion.cpp

- Increase minor version
- Update test

Udate version to 5.2.0

---

code/AssetLib/HMP/HMPLoader.cpp

- Fix override
- closes https://github.com/assimp/assimp/issues/4235

HMP: Fix override during copying position data

---

include/assimp/Exceptional.h
include/assimp/TinyFormatter.h

PR with fix as suggested by @KonopaKrzysztof including the comma operator.
fixes #3565
I still get an error with signed/unsigned comparison somewhere inside gtest, but that is for another issue/pr.

fix compilation with clangcl on windows

---

code/AssetLib/LWO/LWOAnimation.cpp

- Check for valid enum values
- closes https://github.com/assimp/assimp/issues/4236

LWO: validate enum value before parsing it

---

code/AssetLib/Assbin/AssbinFileWriter.cpp
code/AssetLib/XGL/XGLLoader.cpp
code/AssetLib/XGL/XGLLoader.h
code/CMakeLists.txt
code/Common/Base64.cpp
code/Common/Compression.cpp
code/Common/Compression.h
code/Common/material.cpp
code/Common/simd.cpp
include/assimp/Base64.hpp

- Introduce interface for compression algorithms
- Test this concept in XGL-importer

Introduce compression class to encapsulate compression via zlib

---

code/PostProcessing/CalcTangentsProcess.cpp

I think the calculation of bitangent needs to negate if the tangent space is TBN.

update the calculation and orthogonalization for bitangent

---

CMakeLists.txt

- Show a cmake-warning if assimp_view shall be build for linux / mac

Show warning when assimp_viewer cannot be build on target platform

---

include/assimp/Hash.h

- Return when the calculated offset gets negative
- closes https://github.com/assimp/assimp/issues/4414

Fix possible negative array access

---

.github/workflows/ccpp.yml
CMakeLists.txt

Update version of Hunter to v0.24.0 that supports VS 2022

---

code/AssetLib/FBX/FBXDocument.cpp
code/AssetLib/FBX/FBXDocument.h
code/AssetLib/FBX/FBXMaterial.cpp
code/AssetLib/FBX/FBXModel.cpp

- Fix missing initializations
- Refactor some fbx-code
- Use using instead of typedef
- Use default destructors
- Reformattings
- Closes https://github.com/assimp/assimp/issues/4429

Fix missing members and do some small refactorings.

---

Readme.md

- closes https://github.com/assimp/assimp/issues/4497

Document fuzz folder

---

code/AssetLib/ASE/ASEParser.cpp

- closes https://github.com/assimp/assimp/issues/4495

Fix out-of-range access in ASE-Parser

---

code/AssetLib/IFC/IFCCurve.cpp

- closes https://github.com/assimp/assimp/issues/4450

Disable assertion tests floating point against inf for Intel oneAPI

---

include/assimp/Hash.h
test/CMakeLists.txt
test/unit/Common/utHash.cpp

- left shift on negative value
- closes https://github.com/assimp/assimp/issues/4531

Add unittest to reproduce undefined behaviour

---

code/AssetLib/glTF2/glTF2Exporter.cpp

- closes https://github.com/assimp/assimp/issues/4418

Fix  possible nullptr exception

---

code/AssetLib/LWO/LWOLoader.cpp

Removed an unused variable that caused build errors in some circumstances.

Remove unused variable.

---

CMakeLists.txt

- closes https://github.com/assimp/assimp/issues/4593

Disable build for tools per default

---

code/AssetLib/3MF/3MFXmlTags.h
code/AssetLib/3MF/XmlSerializer.cpp
code/AssetLib/Irr/IRRLoader.cpp
code/Common/ScenePreprocessor.cpp
include/assimp/XmlParser.h

- Fix leak in TXMLParser::parse
- Refactor code.

Fix a memory leak

---

code/AssetLib/MDL/MDLMaterialLoader.cpp

- Fix possible nullptr dereferencing.
- closes https://github.com/assimp/assimp/issues/4238

Try to fix issue 4238

---

code/AssetLib/Q3D/Q3DLoader.cpp

- Fuzzer finding
- closes https://github.com/assimp/assimp/issues/3417

Fix possible bad_alloc exception for invalid file

---

code/AssetLib/3MF/XmlSerializer.cpp
include/assimp/XmlParser.h

- closes https://github.com/assimp/assimp/issues/4568

Kimkulling/fix texture loading 3MF, reladed issue-4568

---

code/AssetLib/Step/STEPFile.h

- Code cleanup
- closes https://github.com/assimp/assimp/issues/4626

Remove assertion test

---

code/AssetLib/STL/STLLoader.cpp
code/AssetLib/STL/STLLoader.h

I am not sure how often we have STL files of over 4 GB in size. Anyway, let's make them work.

Fix stl for over 4 gb

---

CMakeLists.txt
test/unit/utVersion.cpp

Closes: https://github.com/assimp/assimp/issues/4655
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

Update version tag

---

code/AssetLib/Blender/BlenderDNA.h
code/AssetLib/Blender/BlenderModifier.cpp
code/AssetLib/Blender/BlenderScene.cpp
code/AssetLib/Blender/BlenderScene.h
code/AssetLib/LWO/LWOMaterial.cpp
code/AssetLib/LWS/LWSLoader.cpp
code/AssetLib/Obj/ObjFileParser.cpp
code/AssetLib/X3D/X3DImporter.cpp
code/Common/ScenePreprocessor.cpp
contrib/openddlparser/code/OpenDDLParser.cpp
test/unit/utBlenderImportExport.cpp
tools/assimp_cmd/Info.cpp

Fix loading .blend files and some other miscellaneous fixes I found along the way.
Most shipped .blend files now load. The only one that doesn't is "BlenderDefault_262.blend" but I'm not sure what's wrong with it.

(Mostly) Blender fixes

---

code/AssetLib/Assbin/AssbinFileWriter.cpp

- closes https://github.com/assimp/assimp/issues/4676

[WIP] Use ai_Real to write correct accuracy

---

code/AssetLib/X3D/X3DImporter_Geometry2D.cpp

And add FIXME comment to questionable code. The included test model does not exercise this code. It would be useful to find one that does.

Fix out of bounds reads in X3D importer

---

include/assimp/mesh.h

Fixed the comment on the `mOffsetMatrix` property to be correct.
See https://assimp-docs.readthedocs.io/en/latest/API/API-Documentation.html#_CPPv46aiBone
See also https://stackoverflow.com/a/73603994

Fix aiBone.mOffsetMatrix documentation

---

test/unit/ImportExport/MDL/utMDLImporter_HL1_ImportSettings.cpp

Fix build error: ‘temp’ may be used uninitialized in this function

---

CMakeLists.txt
contrib/openddlparser/CMakeLists.txt

- Update CMakeLists.txt for openddl lib
- Use correct configuration for openddl lib when building static lib
- closes  https://github.com/assimp/assimp/issues/4516

Use correct flags for openddl for static libs

---

code/AssetLib/Assjson/json_exporter.cpp
include/assimp/quaternion.h

- closes https://github.com/assimp/assimp/issues/4677

Fix: Add missing ahndling for double export in json

---

include/assimp/Hash.h

- abs declaration was missing, fixed by adding header
- closes https://github.com/assimp/assimp/issues/4720

Add missing header for Ubuntu 16 and Mac

---

Build.md

Hello! Here is a little pull request to fix some grammar and spelling mistakes made in [Build.md](https://github.com/assimp/assimp/blob/master/Build.md)

Fixed some grammar and spelling mistakes

---

code/Common/ScenePreprocessor.cpp

- closes https://github.com/assimp/assimp/issues/4831

Ensure face pointer is not nullptr

---

include/assimp/material.inl

Error without:
```
assimp\material.inl(101,47): message : error recovery skipped: ') ?'
```
Reference : https://stackoverflow.com/questions/2561368/illegal-token-on-right-side-of

illegal token on right-side-of ::Windows

---

include/assimp/scene.h

- closes https://github.com/assimp/assimp/issues/4854

Fix: Fix signed unsigned mismatch

---

Readme.md

- Remove deprecated references to the doc folder
- Add a link to the Wiki
- Add a link to the reddit community

Update the getting help section

---

code/AssetLib/FBX/FBXTokenizer.h

- closes https://github.com/assimp/assimp/issues/4869

Remove deprecated comment

---

CMakeLists.txt

- closes https://github.com/assimp/assimp/issues/4845

Remove /Zi compiler flag for MSVC, release config

---

code/PostProcessing/LimitBoneWeightsProcess.cpp

Ensure initializer exists

---

port/iOS/build.sh

- closes https://github.com/assimp/assimp/issues/4906

Fix: Remove deprecated dependency.

---

code/AssetLib/Terragen/TerragenLoader.cpp
test/unit/ImportExport/Terragen/utTerragenImportExport.cpp

Fixes https://github.com/assimp/assimp/issues/3093

Fix Terragen loader

---

include/assimp/mesh.h

Add skeleton doc

---

tools/assimp_cmd/Info.cpp

Move string definitions into conditional block to fix unused variable warnings

---

doc/Fileformats.md

- closes https://github.com/assimp/assimp/issues/4973

Fix: Fix typo in doc

---

code/AssetLib/Blender/BlenderScene.cpp

Might fix another case of #2920

Make Blender MVert no field optional

---

test/unit/utASEImportExport.cpp

Now tries to load all ASE test models.

Add more ASE model unit tests

---

test/unit/ut3DImportExport.cpp
test/unit/ut3DSImportExport.cpp
test/unit/utBVHImportExport.cpp
test/unit/utDXFImporterExporter.cpp

Add all .3D, .3DS, .BVH and .DXF files to unit tests.

Test more files

---

code/CMakeLists.txt

Remove unused `-Wno-shadow-field-in-constructor`.

Remove unused -Wno-shadow-field-in-constructor.

---

code/AssetLib/FBX/FBXConverter.cpp

I also encountered this issue for an FBX exported from Blender, this seems to fix the issue as suggested by @jianliang79

Fix Issue #4486 using the fix described by @jianliang79

---

code/AssetLib/glTF2/glTF2Importer.cpp

Fixes issue https://github.com/assimp/assimp/issues/5054

glTF2: Fix incorrect camera position

---

code/AssetLib/FBX/FBXParser.cpp

- closes https://github.com/assimp/assimp/issues/3421

Fix: Fix leak in Scope class, FBX

---

include/assimp/fast_atof.h

- closes https://github.com/assimp/assimp/issues/3424

Fix: Avoid integer overflow in inversion operation

---

code/CMakeLists.txt

Fix: https://github.com/assimp/assimp/issues/4428

Fix librt link

---

code/Common/Exporter.cpp
code/Pbrt/PbrtExporter.cpp
code/Pbrt/PbrtExporter.h

Hey, 
this is what I had to do to get the PBRT exporter to correctly convert from GLTF2 to PBRT scenes for my use case.
Let me know what you think!

Fix pbrt exporter coordinate system and FoV

---

Dockerfile

- Switch to Ubuntu 22.04
- Use ninja
- Install tools into the image

Update_ Use latest ubuntu image and switch to ninja

---

code/AssetLib/Obj/ObjFileImporter.cpp

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=54187

Fix Heap-buffer-overflow WRITE in Assimp::ObjFileImporter::createVertexArray

---

code/AssetLib/MDL/MDLLoader.cpp
code/AssetLib/MDL/MDLMaterialLoader.cpp

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25108
Closes #3440

Fix UNKNOWN READ in aiTexture::~aiTexture

---

code/AssetLib/HMP/HMPLoader.cpp

Related https://github.com/assimp/assimp/pull/5129
The only hypothesis I have why https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=25108 wasn't closed is that the same reproducer file triggers memory leaks with a different sanitizer. The memory leak fix was submitted as a part of [another pull request](https://github.com/assimp/assimp/pull/5120). Extracting it here.

Fix memory leak

---

code/AssetLib/DXF/DXFLoader.cpp
code/AssetLib/DXF/DXFLoader.h
contrib/zlib/CMakeLists.txt

- closes https://github.com/assimp/assimp/issues/2036

Add handling for negative indices.

---

code/AssetLib/FBX/FBXParser.cpp

Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59056

Fix Invalid-free in Assimp::FBX::Scope::Scope

---

include/assimp/mesh.h

- closes https://github.com/assimp/assimp/issues/5203

Fix: Fix compilation for clang 14.0.3

---

port/iOS/build.sh

- closes https://github.com/assimp/assimp/issues/5197

Fix: Remove useless parameter to specify c++ lib

---

test/models-nonbsd/IFC/linklist.txt

- closes https://github.com/assimp/assimp/issues/5240

Doc: Add wiki link

---

CMakeLists.txt

updated cpp-pm/hunter to last version

Updated cpp-pm/hunter into CMakeLists.txt

---

code/PostProcessing/FindInvalidDataProcess.cpp

- closes https://github.com/assimp/assimp/issues/5259

Replace an assert by a error log.

---

include/assimp/mesh.h

- closes https://github.com/assimp/assimp/pull/4944 by merging master

Deep arsdk bone double free

---

code/AssetLib/IFC/IFCOpenings.cpp

Fix Spelling error

---

code/PostProcessing/PretransformVertices.cpp
test/unit/utBlendImportAreaLight.cpp
test/unit/utBlenderWork.cpp

- closes https://github.com/assimp/assimp/issues/5276
- Some minor fixes in unittests

Fix: Add missing transformation for normalized normals.

---

code/AssetLib/X/XFileImporter.cpp
code/AssetLib/X/XFileImporter.h

- closes https://github.com/assimp/assimp/issues/1728

Fix add checks for indices

---

code/AssetLib/Blender/BlenderModifier.cpp

- closes https://github.com/assimp/assimp/issues/1325

Fix: Check if index for mesh access is out of range

---

code/AssetLib/FBX/FBXExporter.cpp

- closes https://github.com/assimp/assimp/issues/4698
- closes https://github.com/assimp/assimp/issues/4954

FBX: Use correct time scaling

---

code/AssetLib/3MF/D3MFImporter.cpp

- closes https://github.com/assimp/assimp/issues/5392

Check validity of archive without parsing

---

code/AssetLib/MDL/MDLMaterialLoader.cpp

- closes https://github.com/assimp/assimp/issues/4930

Fix integer overflow

---

code/AssetLib/FBX/FBXExporter.cpp

FBX Blendshape `FullWeight: Vec<Float>` -> `FullWeight: Vec<Float>`

---

code/AssetLib/Irr/IRRMeshLoader.cpp
code/AssetLib/Irr/IRRMeshLoader.h
code/AssetLib/LWS/LWSLoader.cpp

- Fix warning in LWS-Importer
- Fix possible out-of-range access in IrrMesh-Importer

Static code analysis fixes

---

include/assimp/quaternion.h

- closes https://github.com/assimp/assimp/issues/5428

Include defs in not cpp-section

---

include/assimp/ZipArchiveIOSystem.h

- closes https://github.com/assimp/assimp/issues/5430

Add zlib-header to ZipArchiveIOSystem.h

---

code/AssetLib/FBX/FBXConverter.cpp

- closes https://github.com/assimp/assimp/issues/849

Add correction of fbx model rotation

---

code/AssetLib/Collada/ColladaLoader.cpp
code/AssetLib/Collada/ColladaParser.cpp

fix a collada import bug

---

doc/Fileformats.md

Forgot to mention it here https://github.com/assimp/assimp/pull/4265

mention IQM loader in Fileformats.md

---

code/Common/Assimp.cpp
test/unit/AssimpAPITest.cpp

- closes https://github.com/assimp/assimp/issues/5566

Add checks for invalid buffer and size

---

test/unit/utVersion.cpp

- closes https://github.com/assimp/assimp/issues/5564

Make sure for releases revision will be zero

---

code/Common/Subdivision.cpp

- closes https://github.com/assimp/assimp/issues/5594

Fix possible nullptr dereferencing.

---

code/PostProcessing/TextureTransform.cpp

- closes https://github.com/assimp/assimp/issues/5603

Postprocessing: Fix endless loop

---

contrib/zip/src/miniz.h

- closes https://github.com/assimp/assimp/issues/5601

Build: Fix compilation for VS-2022 debug mode - warning

---

include/assimp/XmlParser.h

- closes https://github.com/assimp/assimp/issues/5591

Add trim to xml string parsing

---

cmake-modules/HunterGate.cmake

removing cmake version control check. The cmake version is always greater than 3.22

clean HunterGate.cmake

---

.github/workflows/inno_setup
code/AssetLib/3DS/3DSConverter.cpp
code/AssetLib/AC/ACLoader.cpp
code/AssetLib/Blender/BlenderLoader.cpp
code/AssetLib/FBX/FBXConverter.cpp
code/AssetLib/FBX/FBXParser.h
code/AssetLib/Irr/IRRLoader.cpp
code/AssetLib/LWS/LWSLoader.cpp
code/AssetLib/MD5/MD5Loader.cpp
code/AssetLib/MDL/MDLLoader.cpp
code/AssetLib/MDL/MDLMaterialLoader.cpp
code/AssetLib/Q3BSP/Q3BSPFileImporter.cpp
code/AssetLib/Q3D/Q3DLoader.cpp
code/AssetLib/SMD/SMDLoader.cpp
code/AssetLib/STL/STLLoader.cpp
code/AssetLib/Unreal/UnrealLoader.cpp
code/AssetLib/glTF/glTFImporter.cpp
code/AssetLib/glTF2/glTF2Importer.cpp
code/Common/SceneCombiner.cpp
code/Material/MaterialSystem.cpp
code/PostProcessing/OptimizeGraph.cpp
code/PostProcessing/PretransformVertices.cpp
code/PostProcessing/RemoveRedundantMaterials.cpp
code/PostProcessing/ValidateDataStructure.cpp
include/assimp/StringUtils.h
include/assimp/types.h
test/unit/utPretransformVertices.cpp
tools/assimp_view/Display.cpp
tools/assimp_view/Material.cpp
tools/assimp_view/MessageProc.cpp

- closes https://github.com/assimp/assimp/issues/5622

Draft: Update init of aiString

---

port/AssimpNET/Readme.md

link https://bitbucket.org/Starnick/assimpnet/src/master/  is deleted. reverto to old link

update dotnet example

---

code/AssetLib/Collada/ColladaParser.cpp

So all information on uv channels was ignored.

Fix collada uv channels - temporary was stored and then updated.

---

code/AssetLib/FBX/FBXExporter.cpp

- closes https://github.com/assimp/assimp/issues/5617

FBX-Exporter: Fix nullptr dereferencing

---

code/AssetLib/3MF/XmlSerializer.cpp
code/AssetLib/AMF/AMFImporter.cpp
code/AssetLib/AMF/AMFImporter.hpp
code/AssetLib/AMF/AMFImporter_Node.hpp
code/AssetLib/AMF/AMFImporter_Postprocess.cpp
code/AssetLib/ASE/ASELoader.cpp
code/AssetLib/ASE/ASELoader.h
code/AssetLib/ASE/ASEParser.cpp
code/AssetLib/ASE/ASEParser.h
code/AssetLib/Ply/PlyLoader.cpp
test/unit/utB3DImportExport.cpp

This PR will fix some critical findings related to **strlen()** usages, where the string to observe may not be null-terminated.

Replace raw pointers by std::string

---

code/AssetLib/glTF2/glTF2Asset.inl
code/AssetLib/glTF2/glTF2AssetWriter.inl

- closes https://github.com/assimp/assimp/issues/5654

Fix compile warning

---

code/PostProcessing/TriangulateProcess.cpp

- closes https://github.com/assimp/assimp/issues/5684

Return false instead of crash

---

.github/workflows/ccpp.yml
code/PostProcessing/ImproveCacheLocality.cpp

- Fix merge issues from https://github.com/assimp/assimp/pull/5643
- Updated to current master

Sparky kitty studios master

---

CMakeLists.txt
test/unit/utVersion.cpp

prepare v5.4.3

---

code/AssetLib/MD3/MD3Loader.cpp

Heap Buffer Overflow (https://github.com/assimp/assimp/issues/5616)
This patch adds bounds checking to ensure that the surfaces and tags do not exceed the allocated buffer size, preventing the heap-buffer-overflow error. The patch has been validated and confirmed to resolve the issue without introducing new bugs.
```
==458124==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x52800000bc50 at pc 0x555555c89c9f bp 0x7fffffffbf10 sp 0x7fffffffbf08
READ of size 4 at 0x52800000bc50 thread T0
#0 0x555555c89c9e in Assimp::MD3Importer::InternReadFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, aiScene*, Assimp::IOSystem*) /root/code/AssetLib/MD3/MD3Loader.cpp:1037:53
#1 …
```

Fix buffer overflow in MD3Loader

---

code/Common/Importer.cpp

For now when you try to build with the `ASSIMP_BUILD_NO_VALIDATEDS_PROCESS` define, you have  `Unknown type name 'ValidateDSProcess'` compilation error at the `importer.cpp`
This PR fix compilation issue

Fix for build with ASSIMP_BUILD_NO_VALIDATEDS_PROCESS

---

Readme.md

- Experimental view to mak the current activity in the project more visible and transparent
- Will create a more easy to get view onto the base activities like issues, PR and contributors

Readme: Add project activity view item

---

code/AssetLib/Obj/ObjFileImporter.cpp

- Fix possible nullptr dereferencings
- Remove assert tests

Obj: Fix Sonarcube findings

---

Readme.md

Readme.md: Add sonarcube q batch

---

CMakeLists.txt

OpenCV and dependencies update to v4.10.0-p0

Update cpp-pm / hunter

---

code/Common/DefaultIOStream.cpp

- closes https://github.com/assimp/assimp/issues/5827

Fix: Fix build for mingw10

---

code/AssetLib/USD/USDLoaderImplTinyusdz.cpp
code/AssetLib/USD/USDLoaderImplTinyusdz.h

- Place meshes into proper node hierarchy; previously all meshes were added to the root node. 
- Adding animation framerate.
Toy drummer now works after being imported by Open 3D Engine
[toy_drummer_idle_reexport.zip](https://github.com/user-attachments/files/18042830/toy_drummer_idle_reexport.zip)
https://github.com/user-attachments/assets/2e18486e-516a-454c-87d3-7b3d1da0653f
Fixes #5886

USD Mesh Node Fix

---

code/AssetLib/USD/USDLoaderImplTinyusdz.cpp
code/AssetLib/USD/USDLoaderImplTinyusdzHelper.h

Fixed conversion warning when compiling without ASSIMP_DOUBLE_PRECISION. Fixed size() <> unsigned warnings

Fixed warnings

---

code/AssetLib/AMF/AMFImporter_Geometry.cpp
code/AssetLib/AMF/AMFImporter_Node.hpp
code/AssetLib/Assbin/AssbinFileWriter.cpp
code/AssetLib/Assxml/AssxmlFileWriter.cpp
code/AssetLib/glTF/glTFImporter.cpp
code/AssetLib/glTF2/glTF2Importer.cpp

- Use VolumeType instead of already used Type in AMF

Fix: Fix name collision

---

code/AssetLib/STL/STLExporter.cpp

- closes https://github.com/assimp/assimp/issues/5961

Avoid exporting all primitives, which are not triangles.

---

include/assimp/texture.h

- closes https://github.com/assimp/assimp/issues/5981

Doc: Make hint clearer

---

Readme.md

- Add the Qt5 Modelviewer to the readme

Update Readme.md: Add new viewer

---

code/AssetLib/IFC/IFCLoader.cpp

- closes https://github.com/assimp/assimp/issues/5798

IFC: Remove redundand check

---

code/Common/Exporter.cpp

- closes https://github.com/assimp/assimp/issues/5514

Obj: remove smooth-normals postprocessing

---

code/AssetLib/ASE/ASELoader.cpp

- closes https://github.com/assimp/assimp/issues/6021

ASE: Fix possible out of bound access.

---

code/AssetLib/MDL/MDLMaterialLoader.cpp

- closes https://github.com/assimp/assimp/issues/6022

MDL: Limit max texture sizes

---

code/AssetLib/MDL/MDLLoader.cpp

- closes https://github.com/assimp/assimp/issues/6009

MDL: Fix overflow check

---

include/assimp/ParsingUtils.h

- closes https://github.com/assimp/assimp/issues/6026

Fix: Avoid override in line parsing

---

code/Common/SceneCombiner.cpp

- closes https://github.com/assimp/assimp/issues/6025

Bugfix: Fix possible nullptr dereferencing

---

code/AssetLib/ASE/ASEParser.cpp

- closes https://github.com/assimp/assimp/issues/6024

ASE: Use correct vertex container

---

code/AssetLib/CSM/CSMLoader.cpp

- closes https://github.com/assimp/assimp/issues/6010

CMS: Fix possible overflow access

---

code/Material/MaterialSystem.cpp

The C++ Interface's function C_Str() from the aiString struct was missing an equivalent function for the C Interface.

feat: created the aiGetStringC_Str() function.

---

code/AssetLib/FBX/FBXExporter.cpp

The application [Autodesk FBX Review](https://www.autodesk.com/products/fbx/fbx-review) displays an error message when the input fbx file include data empty nodes `LayerElementNormal` or `LayerElementColor`.
Objects
┗Geometry
&emsp;┠LayerElementNormal
&emsp;┗LayerElementColor
> ; Object properties
> ;------------------------------------------------------------------
> 
> Objects:  {
> 	Geometry: 1000001, "Geometry::", "Mesh" {
> 		Vertices: *9 {
> 			a: -1.000000,-1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,-1.000000,0.000000
> 		} 
> 		PolygonVertexIndex: *3 {
> 			a: 0,1,-3
> 		} 
> 		GeometryVersion: 124
> 		LayerElementNormal: 0 {
> 			Version: 101
> 			Name: ""
> 			MappingInformationType: "ByPolygonVertex"
> 			ReferenceInformationType: "Direct"
> 			Normals: *0 {
> 				a: …

Not to export empty "LayerElementNormal" or "LayerElementColor" nodes to fbx

---

code/AssetLib/MD3/MD3Loader.cpp
code/AssetLib/Obj/ObjFileParser.cpp
code/AssetLib/Obj/ObjFileParser.h

- closes https://github.com/assimp/assimp/issues/6053

Use unique pointer to fix possible leak

---

code/AssetLib/FBX/FBXExporter.cpp

Refactor of below commit.
https://github.com/assimp/assimp/commit/e68ea14f5624e03a863a1dbfe5c2fea23dc6556a

Refactoring of PR #6092

---

code/AssetLib/OpenGEX/OpenGEXImporter.cpp

- closes https://github.com/assimp/assimp/issues/1341

Fix: Support uint16 indices in OpenGEX as well

---

code/AssetLib/ASE/ASEParser.cpp
code/AssetLib/CSM/CSMLoader.cpp

- Fix crash in ACELoader
- Fix crash in CMSLoader

Fix crashes

---

Build.md

- closes https://github.com/assimp/assimp/issues/3370

Doc: add C++ / c minimum

---

code/Geometry/GeometryUtils.cpp

- Replace c-casts by static_casts
- Add nullptr checks
- Fix formatting

Refactoring: Add nupptr-checks

---

code/PostProcessing/TextureTransform.cpp
code/PostProcessing/TextureTransform.h

Closes https://github.com/assimp/assimp/issues/6236

bugfix: Fixed the memory leak when texture transforming (#6236)

---

contrib/openddlparser/code/OpenDDLParser.cpp

closes https://github.com/assimp/assimp/issues/6302

Fix OOB read in OpenDDLParser::parseReference
